
//------------------------------------------------------------------------------
// <auto-generated>
// BaseUI Generated
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Service.Pattern;
using System.Windows.Forms;
using System.Linq;
using System.Reflection;
using ComponentFactory.Krypton.Toolkit;
using MetroUI.Forms;
using WH.Entity;
using WH.Model;
using WH.Service.Service;
using Util.Pattern;

