//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WH.Entity
{
    using Util.Pattern;
    using System;
    using System.Collections.Generic;
    
    public partial class CHIETKHAULOAIMATHANG : Repository.Pattern.Ef6.Entity
    {
    	//foreign key MACHIETKHAU
        public int MACHIETKHAU { get; set; }
        public Nullable<int> MALOAIMATHANG { get; set; }
        public Nullable<decimal> MUCQUYDINHTU { get; set; }
        public Nullable<decimal> MUCQUYDINHDEN { get; set; }
        public Nullable<double> CHIETKHAU1 { get; set; }
        public Nullable<double> CHIETKHAU2 { get; set; }
        public Nullable<double> CHIETKHAU3 { get; set; }
        public Nullable<bool> ISUSE { get; set; }
    	//Property TIMKIEM
    	public string TIMKIEM
    	{ 
    		get
    		{
    			return ((""+MACHIETKHAU+';'+MALOAIMATHANG+';'+MUCQUYDINHTU+';'+MUCQUYDINHDEN+';'+CHIETKHAU1+';'+CHIETKHAU2+';'+CHIETKHAU3+';'+ISUSE+';')+(""+MACHIETKHAU+';'+MALOAIMATHANG+';'+MUCQUYDINHTU+';'+MUCQUYDINHDEN+';'+CHIETKHAU1+';'+CHIETKHAU2+';'+CHIETKHAU3+';'+ISUSE+';').ToUnsign()).Replace(" ", "").ToLower();
    		}
    	}
       
    	public string TextSearchCoDau
    	{ 
    		get
    		{
    			return (""+MACHIETKHAU+';'+MALOAIMATHANG+';'+MUCQUYDINHTU+';'+MUCQUYDINHDEN+';'+CHIETKHAU1+';'+CHIETKHAU2+';'+CHIETKHAU3+';'+ISUSE+';').Replace(" ", "").ToLower();
    		}
    	}
    	public string IDUnit {get{return (MACHIETKHAU).ToString();}}
    	
        public virtual LOAIMATHANG LOAIMATHANG { get; set; }
    }
}
