//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WH.Entity
{
    using Util.Pattern;
    using System;
    using System.Collections.Generic;
    
    public partial class CHUCNANG : Repository.Pattern.Ef6.Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUCNANG()
        {
            this.NGUOIDUNG_QUYENHAN = new List<NGUOIDUNG_QUYENHAN>();
        }
    	//List Property
    	
    	//foreign key MACHUCNANG
        public int MACHUCNANG { get; set; }
        public string TENCHUCNANG { get; set; }
    	//Property TIMKIEM
    	public string TIMKIEM
    	{ 
    		get
    		{
    			return ((""+MACHUCNANG+';'+TENCHUCNANG+';')+(""+MACHUCNANG+';'+TENCHUCNANG+';').ToUnsign()).Replace(" ", "").ToLower();
    		}
    	}
       
    	public string TextSearchCoDau
    	{ 
    		get
    		{
    			return (""+MACHUCNANG+';'+TENCHUCNANG+';').Replace(" ", "").ToLower();
    		}
    	}
    	public string IDUnit {get{return (MACHUCNANG).ToString();}}
    	
    	//LIST NGUOIDUNG_QUYENHAN
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual IList<NGUOIDUNG_QUYENHAN> NGUOIDUNG_QUYENHAN { get; set; }
    }
}
