//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WH.Entity
{
    using System;
    using System.Collections.Generic;
    using Util.Pattern;

    public partial class HOADONXUATKHO : Repository.Pattern.Ef6.Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONXUATKHO()
        {
            this.HOADONXUATKHOCHITIETs = new List<HOADONXUATKHOCHITIET>();
            this.PHIEUTHUs = new List<PHIEUTHU>();
        }
        //List Property

        //foreign key MAHOADONXUAT
        public string MAHOADONXUAT { get; set; }
        public Nullable<decimal> THANHTIENCHUACK_HD { get; set; }
        public Nullable<decimal> TIENCHIETKHAU_HD { get; set; }
        public Nullable<decimal> TIENKHUYENMAI_HD { get; set; }
        public decimal? SOTIENTHANHTOAN_HD { get; set; }
        public Nullable<decimal> SOTIENKHACHDUA_HD { get; set; }
        public Nullable<int> LOAIHOADON { get; set; }
        public Nullable<System.DateTime> HANTHANHTOAN { get; set; }
        public string GHICHU_HD { get; set; }
        public Nullable<bool> DATHANHTOAN { get; set; }
        public string NGUOITAO { get; set; }
        public Nullable<System.DateTime> NGAYTAOHOADON { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
        public Nullable<System.Guid> MAKHACHHANG { get; set; }
        public Nullable<int> MACA { get; set; }

        //Property TIMKIEM
        public string TIMKIEM
        {
            get
            {
                return (("" + MAHOADONXUAT + ';' + THANHTIENCHUACK_HD + ';' + TIENCHIETKHAU_HD + ';' + TIENKHUYENMAI_HD + ';' + SOTIENTHANHTOAN_HD + ';' + SOTIENKHACHDUA_HD + ';' + LOAIHOADON + ';' + HANTHANHTOAN + ';' + GHICHU_HD + ';' + DATHANHTOAN + ';' + NGUOITAO + ';' + NGAYTAOHOADON + ';' + ISDELETE + ';' + MAKHACHHANG + ';' + MACA + ';') + ("" + MAHOADONXUAT + ';' + THANHTIENCHUACK_HD + ';' + TIENCHIETKHAU_HD + ';' + TIENKHUYENMAI_HD + ';' + SOTIENTHANHTOAN_HD + ';' + SOTIENKHACHDUA_HD + ';' + LOAIHOADON + ';' + HANTHANHTOAN + ';' + GHICHU_HD + ';' + DATHANHTOAN + ';' + NGUOITAO + ';' + NGAYTAOHOADON + ';' + ISDELETE + ';' + MAKHACHHANG + ';' + MACA + ';').ToUnsign()).Replace(" ", "").ToLower();
            }
        }

        public string TextSearchCoDau
        {
            get
            {
                return ("" + MAHOADONXUAT + ';' + THANHTIENCHUACK_HD + ';' + TIENCHIETKHAU_HD + ';' + TIENKHUYENMAI_HD + ';' + SOTIENTHANHTOAN_HD + ';' + SOTIENKHACHDUA_HD + ';' + LOAIHOADON + ';' + HANTHANHTOAN + ';' + GHICHU_HD + ';' + DATHANHTOAN + ';' + NGUOITAO + ';' + NGAYTAOHOADON + ';' + ISDELETE + ';' + MAKHACHHANG + ';' + MACA + ';').Replace(" ", "").ToLower();
            }
        }
        public string IDUnit { get { return (MAHOADONXUAT).ToString(); } }

        public virtual CA CA { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        //LIST HOADONXUATKHOCHITIETs
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual IList<HOADONXUATKHOCHITIET> HOADONXUATKHOCHITIETs { get; set; }
        //LIST PHIEUTHUs
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual IList<PHIEUTHU> PHIEUTHUs { get; set; }
    }
}
