//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WH.Entity
{
    using Util.Pattern;
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANGKHUVUC : Repository.Pattern.Ef6.Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANGKHUVUC()
        {
            this.KHACHHANGs = new List<KHACHHANG>();
        }
    	//List Property
    	
    	//foreign key MAKHUVUC
        public int MAKHUVUC { get; set; }
        public string TEN { get; set; }
        public Nullable<int> QUANGDUONG { get; set; }
        public string GHICHU { get; set; }
        public Nullable<bool> ISUSE { get; set; }
    	//Property TIMKIEM
    	public string TIMKIEM
    	{ 
    		get
    		{
    			return ((""+MAKHUVUC+';'+TEN+';'+QUANGDUONG+';'+GHICHU+';'+ISUSE+';')+(""+MAKHUVUC+';'+TEN+';'+QUANGDUONG+';'+GHICHU+';'+ISUSE+';').ToUnsign()).Replace(" ", "").ToLower();
    		}
    	}
       
    	public string TextSearchCoDau
    	{ 
    		get
    		{
    			return (""+MAKHUVUC+';'+TEN+';'+QUANGDUONG+';'+GHICHU+';'+ISUSE+';').Replace(" ", "").ToLower();
    		}
    	}
    	public string IDUnit {get{return (MAKHUVUC).ToString();}}
    	
    	//LIST KHACHHANGs
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual IList<KHACHHANG> KHACHHANGs { get; set; }
    }
}
