//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WH.Entity
{
    using Util.Pattern;
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIKHACHHANG : Repository.Pattern.Ef6.Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIKHACHHANG()
        {
            this.KHACHHANGs = new List<KHACHHANG>();
        }
    	//List Property
    	
    	//foreign key MALOAI
        public int MALOAI { get; set; }
        public string TENLOAI { get; set; }
        public Nullable<int> DIEMDAT { get; set; }
        public Nullable<bool> ISUSE { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    	//Property TIMKIEM
    	public string TIMKIEM
    	{ 
    		get
    		{
    			return ((""+MALOAI+';'+TENLOAI+';'+DIEMDAT+';'+ISUSE+';'+ISDELETE+';')+(""+MALOAI+';'+TENLOAI+';'+DIEMDAT+';'+ISUSE+';'+ISDELETE+';').ToUnsign()).Replace(" ", "").ToLower();
    		}
    	}
       
    	public string TextSearchCoDau
    	{ 
    		get
    		{
    			return (""+MALOAI+';'+TENLOAI+';'+DIEMDAT+';'+ISUSE+';'+ISDELETE+';').Replace(" ", "").ToLower();
    		}
    	}
    	public string IDUnit {get{return (MALOAI).ToString();}}
    	
    	//LIST KHACHHANGs
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual IList<KHACHHANG> KHACHHANGs { get; set; }
    }
}
