//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WH.Entity
{
    using Util.Pattern;
    using System;
    using System.Collections.Generic;
    
    public partial class MATHANGKHUYENMAI : Repository.Pattern.Ef6.Entity
    {
    	//foreign key MAMATHANG
        public int MAMATHANG { get; set; }
    	//foreign key MAMATHANGKHUYENMAI
        public int MAMATHANGKHUYENMAI { get; set; }
        public Nullable<decimal> SOLUONGMATHANGQUYDOI { get; set; }
        public Nullable<decimal> SOLUONGSI { get; set; }
        public Nullable<decimal> SOLUONGLE { get; set; }
        public Nullable<decimal> TIENKHUYENMAI { get; set; }
        public Nullable<decimal> TONGTIENKHUYENMAI { get; set; }
        public Nullable<bool> ISUSE { get; set; }
    	//Property TIMKIEM
    	public string TIMKIEM
    	{ 
    		get
    		{
    			return ((""+MAMATHANG+';'+MAMATHANGKHUYENMAI+';'+SOLUONGMATHANGQUYDOI+';'+SOLUONGSI+';'+SOLUONGLE+';'+TIENKHUYENMAI+';'+TONGTIENKHUYENMAI+';'+ISUSE+';')+(""+MAMATHANG+';'+MAMATHANGKHUYENMAI+';'+SOLUONGMATHANGQUYDOI+';'+SOLUONGSI+';'+SOLUONGLE+';'+TIENKHUYENMAI+';'+TONGTIENKHUYENMAI+';'+ISUSE+';').ToUnsign()).Replace(" ", "").ToLower();
    		}
    	}
       
    	public string TextSearchCoDau
    	{ 
    		get
    		{
    			return (""+MAMATHANG+';'+MAMATHANGKHUYENMAI+';'+SOLUONGMATHANGQUYDOI+';'+SOLUONGSI+';'+SOLUONGLE+';'+TIENKHUYENMAI+';'+TONGTIENKHUYENMAI+';'+ISUSE+';').Replace(" ", "").ToLower();
    		}
    	}
    	public string IDUnit {get{return (MAMATHANG+"_"+MAMATHANGKHUYENMAI).ToString();}}
    	
        public virtual MATHANG MATHANG { get; set; }
        public virtual MATHANG MATHANG1 { get; set; }
    }
}
