//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WH.Entity
{
    using Util.Pattern;
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG_QUYENHAN : Repository.Pattern.Ef6.Entity
    {
    	//foreign key MANGUOIDUNG
        public string MANGUOIDUNG { get; set; }
    	//foreign key MACHUCNANG
        public int MACHUCNANG { get; set; }
        public Nullable<bool> QUYENXEM { get; set; }
        public Nullable<bool> QUYENSUA { get; set; }
        public Nullable<bool> QUYENXOA { get; set; }
        public Nullable<bool> QUYENTIMKIEM { get; set; }
        public Nullable<bool> QUYENXUATFILE { get; set; }
        public Nullable<bool> QUYENIN { get; set; }
    	//Property TIMKIEM
    	public string TIMKIEM
    	{ 
    		get
    		{
    			return ((""+MANGUOIDUNG+';'+MACHUCNANG+';'+QUYENXEM+';'+QUYENSUA+';'+QUYENXOA+';'+QUYENTIMKIEM+';'+QUYENXUATFILE+';'+QUYENIN+';')+(""+MANGUOIDUNG+';'+MACHUCNANG+';'+QUYENXEM+';'+QUYENSUA+';'+QUYENXOA+';'+QUYENTIMKIEM+';'+QUYENXUATFILE+';'+QUYENIN+';').ToUnsign()).Replace(" ", "").ToLower();
    		}
    	}
       
    	public string TextSearchCoDau
    	{ 
    		get
    		{
    			return (""+MANGUOIDUNG+';'+MACHUCNANG+';'+QUYENXEM+';'+QUYENSUA+';'+QUYENXOA+';'+QUYENTIMKIEM+';'+QUYENXUATFILE+';'+QUYENIN+';').Replace(" ", "").ToLower();
    		}
    	}
    	public string IDUnit {get{return (MANGUOIDUNG+"_"+MACHUCNANG).ToString();}}
    	
        public virtual CHUCNANG CHUCNANG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
