//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WH.Entity
{
    using Util.Pattern;
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG : Repository.Pattern.Ef6.Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOIDUNG()
        {
            this.NGUOIDUNG_QUYENHAN = new List<NGUOIDUNG_QUYENHAN>();
        }
    	//List Property
    	
    	//foreign key MANGUOIDUNG
        public string MANGUOIDUNG { get; set; }
        public Nullable<int> MANHANVIEN { get; set; }
        public string TENNGUOIDUNG { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    	//Property TIMKIEM
    	public string TIMKIEM
    	{ 
    		get
    		{
    			return ((""+MANGUOIDUNG+';'+MANHANVIEN+';'+TENNGUOIDUNG+';'+TENDANGNHAP+';'+MATKHAU+';'+ISDELETE+';')+(""+MANGUOIDUNG+';'+MANHANVIEN+';'+TENNGUOIDUNG+';'+TENDANGNHAP+';'+MATKHAU+';'+ISDELETE+';').ToUnsign()).Replace(" ", "").ToLower();
    		}
    	}
       
    	public string TextSearchCoDau
    	{ 
    		get
    		{
    			return (""+MANGUOIDUNG+';'+MANHANVIEN+';'+TENNGUOIDUNG+';'+TENDANGNHAP+';'+MATKHAU+';'+ISDELETE+';').Replace(" ", "").ToLower();
    		}
    	}
    	public string IDUnit {get{return (MANGUOIDUNG).ToString();}}
    	
    	//LIST NGUOIDUNG_QUYENHAN
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual IList<NGUOIDUNG_QUYENHAN> NGUOIDUNG_QUYENHAN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
