//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WH.Entity
{
    using Util.Pattern;
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN : Repository.Pattern.Ef6.Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.CAs = new List<CA>();
            this.NGUOIDUNGs = new List<NGUOIDUNG>();
        }
    	//List Property
    	
    	//foreign key MANHANVIEN
        public int MANHANVIEN { get; set; }
        public Nullable<int> MALOAI { get; set; }
        public string TENNHANVIEN { get; set; }
        public string CHUCVU { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string CMND { get; set; }
        public string DIACHI { get; set; }
        public string QUEQUAN { get; set; }
        public string DIDONG { get; set; }
        public Nullable<decimal> LUONGCOBAN { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> THEODOI { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public string NGUOITAO { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public string NGUOICAPNHAT { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    	//Property TIMKIEM
    	public string TIMKIEM
    	{ 
    		get
    		{
    			return ((""+MANHANVIEN+';'+MALOAI+';'+TENNHANVIEN+';'+CHUCVU+';'+NGAYSINH+';'+GIOITINH+';'+CMND+';'+DIACHI+';'+QUEQUAN+';'+DIDONG+';'+LUONGCOBAN+';'+EMAIL+';'+THEODOI+';'+NGAYTAO+';'+NGUOITAO+';'+NGAYCAPNHAT+';'+NGUOICAPNHAT+';'+ISDELETE+';')+(""+MANHANVIEN+';'+MALOAI+';'+TENNHANVIEN+';'+CHUCVU+';'+NGAYSINH+';'+GIOITINH+';'+CMND+';'+DIACHI+';'+QUEQUAN+';'+DIDONG+';'+LUONGCOBAN+';'+EMAIL+';'+THEODOI+';'+NGAYTAO+';'+NGUOITAO+';'+NGAYCAPNHAT+';'+NGUOICAPNHAT+';'+ISDELETE+';').ToUnsign()).Replace(" ", "").ToLower();
    		}
    	}
       
    	public string TextSearchCoDau
    	{ 
    		get
    		{
    			return (""+MANHANVIEN+';'+MALOAI+';'+TENNHANVIEN+';'+CHUCVU+';'+NGAYSINH+';'+GIOITINH+';'+CMND+';'+DIACHI+';'+QUEQUAN+';'+DIDONG+';'+LUONGCOBAN+';'+EMAIL+';'+THEODOI+';'+NGAYTAO+';'+NGUOITAO+';'+NGAYCAPNHAT+';'+NGUOICAPNHAT+';'+ISDELETE+';').Replace(" ", "").ToLower();
    		}
    	}
    	public string IDUnit {get{return (MANHANVIEN).ToString();}}
    	
    	//LIST CAs
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual IList<CA> CAs { get; set; }
        public virtual LOAINHANVIEN LOAINHANVIEN { get; set; }
    	//LIST NGUOIDUNGs
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual IList<NGUOIDUNG> NGUOIDUNGs { get; set; }
    }
}
