//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WH.Entity
{
    using Util.Pattern;
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagram : Repository.Pattern.Ef6.Entity
    {
        public string name { get; set; }
        public int principal_id { get; set; }
    	//foreign key diagram_id
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    	//Property TIMKIEM
    	public string TIMKIEM
    	{ 
    		get
    		{
    			return ((""+name+';'+principal_id+';'+diagram_id+';'+version+';'+definition+';')+(""+name+';'+principal_id+';'+diagram_id+';'+version+';'+definition+';').ToUnsign()).Replace(" ", "").ToLower();
    		}
    	}
       
    	public string TextSearchCoDau
    	{ 
    		get
    		{
    			return (""+name+';'+principal_id+';'+diagram_id+';'+version+';'+definition+';').Replace(" ", "").ToLower();
    		}
    	}
    	public string IDUnit {get{return (diagram_id).ToString();}}
    	}
}
