//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WH.Entity
{
    using System;
    using Util.Pattern;

    public partial class TEMP_HOADONXUATKHOCHITIET : Repository.Pattern.Ef6.Entity
    {
        //foreign key MACHITIETHOADON
        public string MACHITIETHOADON { get; set; }
        public string MAHOADON { get; set; }
        public Nullable<System.Guid> MAKHO { get; set; }
        public Nullable<int> MAMATHANG { get; set; }
        public Nullable<decimal> SOLUONGSI { get; set; }
        public Nullable<decimal> SOLUONGLE { get; set; }
        public Nullable<decimal> DONGIASI { get; set; }
        public Nullable<double> CHIETKHAUTHEOPHANTRAM { get; set; }
        public Nullable<decimal> CHIETKHAUTHEOTIEN { get; set; }
        public Nullable<bool> ISCKPHANTRAM { get; set; }
        public Nullable<decimal> THANHTIENTRUOCCHIETKHAU_CT { get; set; }
        public Nullable<decimal> THANHTIENSAUCHIETKHAU_CT { get; set; }
        public string GHICHU { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
        //Property TIMKIEM
        public string TIMKIEM
        {
            get
            {
                return (("" + MACHITIETHOADON + ';' + MAHOADON + ';' + MAKHO + ';' + MAMATHANG + ';' + SOLUONGSI + ';' + SOLUONGLE + ';' + DONGIASI + ';' + CHIETKHAUTHEOPHANTRAM + ';' + CHIETKHAUTHEOTIEN + ';' + ISCKPHANTRAM + ';' + THANHTIENTRUOCCHIETKHAU_CT + ';' + THANHTIENSAUCHIETKHAU_CT + ';' + GHICHU + ';' + ISDELETE + ';') + ("" + MACHITIETHOADON + ';' + MAHOADON + ';' + MAKHO + ';' + MAMATHANG + ';' + SOLUONGSI + ';' + SOLUONGLE + ';' + DONGIASI + ';' + CHIETKHAUTHEOPHANTRAM + ';' + CHIETKHAUTHEOTIEN + ';' + ISCKPHANTRAM + ';' + THANHTIENTRUOCCHIETKHAU_CT + ';' + THANHTIENSAUCHIETKHAU_CT + ';' + GHICHU + ';' + ISDELETE + ';').ToUnsign()).Replace(" ", "").ToLower();
            }
        }

        public string TextSearchCoDau
        {
            get
            {
                return ("" + MACHITIETHOADON + ';' + MAHOADON + ';' + MAKHO + ';' + MAMATHANG + ';' + SOLUONGSI + ';' + SOLUONGLE + ';' + DONGIASI + ';' + CHIETKHAUTHEOPHANTRAM + ';' + CHIETKHAUTHEOTIEN + ';' + ISCKPHANTRAM + ';' + THANHTIENTRUOCCHIETKHAU_CT + ';' + THANHTIENSAUCHIETKHAU_CT + ';' + GHICHU + ';' + ISDELETE + ';').Replace(" ", "").ToLower();
            }
        }
        public string IDUnit { get { return (MACHITIETHOADON).ToString(); } }
    }
}
