//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WH.Entity
{
    using Util.Pattern;
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_HOADONXUATKHO : Repository.Pattern.Ef6.Entity
    {
    	//foreign key MAHOADONXUAT
        public string MAHOADONXUAT { get; set; }
        public Nullable<decimal> THANHTIENCHUACK_HD { get; set; }
        public Nullable<decimal> TIENCHIETKHAU_HD { get; set; }
        public Nullable<decimal> TIENKHUYENMAI_HD { get; set; }
        public Nullable<decimal> SOTIENTHANHTOAN_HD { get; set; }
        public Nullable<decimal> SOTIENKHACHDUA_HD { get; set; }
        public Nullable<int> LOAIHOADON { get; set; }
        public Nullable<System.DateTime> HANTHANHTOAN { get; set; }
        public string GHICHU_HD { get; set; }
        public Nullable<bool> DATHANHTOAN { get; set; }
        public string NGUOITAO { get; set; }
        public Nullable<System.DateTime> NGAYTAOHOADON { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
        public Nullable<System.Guid> MAKHACHHANG { get; set; }
        public Nullable<int> MACA { get; set; }
    	//Property TIMKIEM
    	public string TIMKIEM
    	{ 
    		get
    		{
    			return ((""+MAHOADONXUAT+';'+THANHTIENCHUACK_HD+';'+TIENCHIETKHAU_HD+';'+TIENKHUYENMAI_HD+';'+SOTIENTHANHTOAN_HD+';'+SOTIENKHACHDUA_HD+';'+LOAIHOADON+';'+HANTHANHTOAN+';'+GHICHU_HD+';'+DATHANHTOAN+';'+NGUOITAO+';'+NGAYTAOHOADON+';'+ISDELETE+';'+MAKHACHHANG+';'+MACA+';')+(""+MAHOADONXUAT+';'+THANHTIENCHUACK_HD+';'+TIENCHIETKHAU_HD+';'+TIENKHUYENMAI_HD+';'+SOTIENTHANHTOAN_HD+';'+SOTIENKHACHDUA_HD+';'+LOAIHOADON+';'+HANTHANHTOAN+';'+GHICHU_HD+';'+DATHANHTOAN+';'+NGUOITAO+';'+NGAYTAOHOADON+';'+ISDELETE+';'+MAKHACHHANG+';'+MACA+';').ToUnsign()).Replace(" ", "").ToLower();
    		}
    	}
       
    	public string TextSearchCoDau
    	{ 
    		get
    		{
    			return (""+MAHOADONXUAT+';'+THANHTIENCHUACK_HD+';'+TIENCHIETKHAU_HD+';'+TIENKHUYENMAI_HD+';'+SOTIENTHANHTOAN_HD+';'+SOTIENKHACHDUA_HD+';'+LOAIHOADON+';'+HANTHANHTOAN+';'+GHICHU_HD+';'+DATHANHTOAN+';'+NGUOITAO+';'+NGAYTAOHOADON+';'+ISDELETE+';'+MAKHACHHANG+';'+MACA+';').Replace(" ", "").ToLower();
    		}
    	}
    	public string IDUnit {get{return (MAHOADONXUAT).ToString();}}
    	}
}
