//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WH.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WHEntities : DbContext
    {
        public WHEntities()
            : base("name=WHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CA> CAs { get; set; }
        public virtual DbSet<CHIETKHAULOAIMATHANG> CHIETKHAULOAIMATHANGs { get; set; }
        public virtual DbSet<CHUCNANG> CHUCNANGs { get; set; }
        public virtual DbSet<CONFIG_PRINTER> CONFIG_PRINTER { get; set; }
        public virtual DbSet<DONVI> DONVIs { get; set; }
        public virtual DbSet<HOADONHAPKHOCHITIET> HOADONHAPKHOCHITIETs { get; set; }
        public virtual DbSet<HOADONNHAPKHO> HOADONNHAPKHOes { get; set; }
        public virtual DbSet<HOADONNHAPXUAT> HOADONNHAPXUATs { get; set; }
        public virtual DbSet<HOADONNHAPXUATCHITIET> HOADONNHAPXUATCHITIETs { get; set; }
        public virtual DbSet<HOADONXUATKHO> HOADONXUATKHOes { get; set; }
        public virtual DbSet<HOADONXUATKHOCHITIET> HOADONXUATKHOCHITIETs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHACHHANGKHUVUC> KHACHHANGKHUVUCs { get; set; }
        public virtual DbSet<KHACHHANGNHOM> KHACHHANGNHOMs { get; set; }
        public virtual DbSet<KHACHHANGTHEODOIDOANHTHU> KHACHHANGTHEODOIDOANHTHUs { get; set; }
        public virtual DbSet<KHO> KHOes { get; set; }
        public virtual DbSet<KHOMATHANG> KHOMATHANGs { get; set; }
        public virtual DbSet<LOAIKHACHHANG> LOAIKHACHHANGs { get; set; }
        public virtual DbSet<LOAIMATHANG> LOAIMATHANGs { get; set; }
        public virtual DbSet<LOAINHANVIEN> LOAINHANVIENs { get; set; }
        public virtual DbSet<MATHANG> MATHANGs { get; set; }
        public virtual DbSet<MATHANGKHUYENMAI> MATHANGKHUYENMAIs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<NGUOIDUNG_QUYENHAN> NGUOIDUNG_QUYENHAN { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUCHI> PHIEUCHIs { get; set; }
        public virtual DbSet<PHIEUTHU> PHIEUTHUs { get; set; }
        public virtual DbSet<QUANLYTHETHEOKHACHHANG> QUANLYTHETHEOKHACHHANGs { get; set; }
        public virtual DbSet<SETDATETIME> SETDATETIMEs { get; set; }
        public virtual DbSet<TEMP_HOADONHAPKHOCHITIET> TEMP_HOADONHAPKHOCHITIET { get; set; }
        public virtual DbSet<TEMP_HOADONNHAPKHO> TEMP_HOADONNHAPKHO { get; set; }
        public virtual DbSet<TEMP_HOADONXUATKHO> TEMP_HOADONXUATKHO { get; set; }
        public virtual DbSet<TEMP_HOADONXUATKHOCHITIET> TEMP_HOADONXUATKHOCHITIET { get; set; }
        public virtual DbSet<THONGTINTHE> THONGTINTHEs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
