//------------------------------------------------------------------------------
// <auto-generated>
// Repository Generated
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.DataContext;
using Repository.Pattern.Ef6;
using Repository.Pattern.Repositories;
using Repository.Pattern.UnitOfWork;
using Util.Pattern;
using WH.Entity;
using System;

namespace WH.Service.Repository
{
    public partial interface ICHIETKHAULOAIMATHANGRepository : IRepositoryAsync<CHIETKHAULOAIMATHANG>
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<CHIETKHAULOAIMATHANG, bool>> predicate);
    	CHIETKHAULOAIMATHANG getObject(string id);
    	CHIETKHAULOAIMATHANG getObject(Expression<Func<CHIETKHAULOAIMATHANG, bool>> predicate);
    	
    
    	CHIETKHAULOAIMATHANG CreateNew();
    	CHIETKHAULOAIMATHANG CloneNew(CHIETKHAULOAIMATHANG objCHIETKHAULOAIMATHANG);
    	CHIETKHAULOAIMATHANG CloneUpdate(CHIETKHAULOAIMATHANG objCHIETKHAULOAIMATHANG);
    	CHIETKHAULOAIMATHANG Clone(CHIETKHAULOAIMATHANG objCHIETKHAULOAIMATHANG);
    
    	List< CHIETKHAULOAIMATHANG> Clone(IList<CHIETKHAULOAIMATHANG> listCHIETKHAULOAIMATHANGs);
    	string GetMaxCode();
    	List<CHIETKHAULOAIMATHANG> Search(string textSearch);
    	List<CHIETKHAULOAIMATHANG> Search(Expression<Func<CHIETKHAULOAIMATHANG, bool>> predicate);
    	List<CHIETKHAULOAIMATHANG> Search(Expression<Func<CHIETKHAULOAIMATHANG, bool>> predicate,string textSearch);
    }
    
    public partial class CHIETKHAULOAIMATHANGRepository : Repository<CHIETKHAULOAIMATHANG>, ICHIETKHAULOAIMATHANGRepository
    {
    	public string DefaultCode
        {
    		get { return null; }
        }
    
        public CHIETKHAULOAIMATHANGRepository(IDataContextAsync context, IUnitOfWorkAsync unitOfWork) : base(context, unitOfWork)
        {
        }
    
        public CHIETKHAULOAIMATHANGRepository(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
    	public bool Exist(string id)
        {
    		return QueryableList().Any(p => p.IDUnit == id);
        }
    
    	public bool Exist(Expression<Func<CHIETKHAULOAIMATHANG, bool>> predicate)
    	{
    		return Queryable().Any(predicate);
    	}
    
    	public CHIETKHAULOAIMATHANG CreateNew()
        {
    		
    		CHIETKHAULOAIMATHANG _obj = Create();
    
    				//_obj.LOAIMATHANG = null;//object
    		_obj.MALOAIMATHANG =  null;////Nullable<int>
    									_obj.ISUSE = null;//Nullable<bool>
    							        return _obj;
        }
    
    	public CHIETKHAULOAIMATHANG CloneNew(CHIETKHAULOAIMATHANG objCHIETKHAULOAIMATHANG)
    	{
    		if(objCHIETKHAULOAIMATHANG==null) return null;
    			 CHIETKHAULOAIMATHANG objNew = Find(objCHIETKHAULOAIMATHANG.MACHIETKHAU);
    			if(objNew !=null) return null;
    
    		 objNew =  CreateNew();
    		 				objNew.MACHIETKHAU =  objCHIETKHAULOAIMATHANG.MACHIETKHAU;
    								objNew.MALOAIMATHANG =  objCHIETKHAULOAIMATHANG.MALOAIMATHANG;
    								objNew.MUCQUYDINHTU =  objCHIETKHAULOAIMATHANG.MUCQUYDINHTU;
    								objNew.MUCQUYDINHDEN =  objCHIETKHAULOAIMATHANG.MUCQUYDINHDEN;
    								objNew.CHIETKHAU1 =  objCHIETKHAULOAIMATHANG.CHIETKHAU1;
    								objNew.CHIETKHAU2 =  objCHIETKHAULOAIMATHANG.CHIETKHAU2;
    								objNew.CHIETKHAU3 =  objCHIETKHAULOAIMATHANG.CHIETKHAU3;
    								objNew.ISUSE =  objCHIETKHAULOAIMATHANG.ISUSE;
    						  objNew.isAdd = true;
    		 return objNew;
    	}
    
    	public CHIETKHAULOAIMATHANG CloneUpdate(CHIETKHAULOAIMATHANG objCHIETKHAULOAIMATHANG)
    	{
    		if(objCHIETKHAULOAIMATHANG==null) return null;
    		 CHIETKHAULOAIMATHANG objNew = Find(objCHIETKHAULOAIMATHANG.MACHIETKHAU);
    		 if(objNew==null) return null;
    		 				objNew.MACHIETKHAU =  objCHIETKHAULOAIMATHANG.MACHIETKHAU;
    								objNew.MALOAIMATHANG =  objCHIETKHAULOAIMATHANG.MALOAIMATHANG;
    								objNew.MUCQUYDINHTU =  objCHIETKHAULOAIMATHANG.MUCQUYDINHTU;
    								objNew.MUCQUYDINHDEN =  objCHIETKHAULOAIMATHANG.MUCQUYDINHDEN;
    								objNew.CHIETKHAU1 =  objCHIETKHAULOAIMATHANG.CHIETKHAU1;
    								objNew.CHIETKHAU2 =  objCHIETKHAULOAIMATHANG.CHIETKHAU2;
    								objNew.CHIETKHAU3 =  objCHIETKHAULOAIMATHANG.CHIETKHAU3;
    								objNew.ISUSE =  objCHIETKHAULOAIMATHANG.ISUSE;
    						 objNew.isUpdate = true;
    		 return objNew;
    	}
    	public CHIETKHAULOAIMATHANG Clone(CHIETKHAULOAIMATHANG objCHIETKHAULOAIMATHANG)
    	{
    		if(objCHIETKHAULOAIMATHANG==null) return null;
    		 CHIETKHAULOAIMATHANG objNew = Find(objCHIETKHAULOAIMATHANG.MACHIETKHAU);
    		 if(objNew==null) 
    		 {
    		 objNew =  CreateNew();
    		 				objNew.MACHIETKHAU =  objCHIETKHAULOAIMATHANG.MACHIETKHAU;
    								objNew.MALOAIMATHANG =  objCHIETKHAULOAIMATHANG.MALOAIMATHANG;
    								objNew.MUCQUYDINHTU =  objCHIETKHAULOAIMATHANG.MUCQUYDINHTU;
    								objNew.MUCQUYDINHDEN =  objCHIETKHAULOAIMATHANG.MUCQUYDINHDEN;
    								objNew.CHIETKHAU1 =  objCHIETKHAULOAIMATHANG.CHIETKHAU1;
    								objNew.CHIETKHAU2 =  objCHIETKHAULOAIMATHANG.CHIETKHAU2;
    								objNew.CHIETKHAU3 =  objCHIETKHAULOAIMATHANG.CHIETKHAU3;
    								objNew.ISUSE =  objCHIETKHAULOAIMATHANG.ISUSE;
    						  objNew.isAdd = true;
    		 }
    		 else
    		 {
    		 				objNew.MALOAIMATHANG =  objCHIETKHAULOAIMATHANG.MALOAIMATHANG;
    								objNew.MUCQUYDINHTU =  objCHIETKHAULOAIMATHANG.MUCQUYDINHTU;
    								objNew.MUCQUYDINHDEN =  objCHIETKHAULOAIMATHANG.MUCQUYDINHDEN;
    								objNew.CHIETKHAU1 =  objCHIETKHAULOAIMATHANG.CHIETKHAU1;
    								objNew.CHIETKHAU2 =  objCHIETKHAULOAIMATHANG.CHIETKHAU2;
    								objNew.CHIETKHAU3 =  objCHIETKHAULOAIMATHANG.CHIETKHAU3;
    								objNew.ISUSE =  objCHIETKHAULOAIMATHANG.ISUSE;
    						 objNew.isUpdate = true;
    		  objNew.isLoaded = true;
    		 }
    		 return objNew;
    	}
    
    	public List< CHIETKHAULOAIMATHANG> Clone(IList<CHIETKHAULOAIMATHANG> listCHIETKHAULOAIMATHANGs)
    	{
    		List< CHIETKHAULOAIMATHANG> lst = new List< CHIETKHAULOAIMATHANG>();
    		if(listCHIETKHAULOAIMATHANGs == null) return lst;
    		foreach(var obj in  listCHIETKHAULOAIMATHANGs)
    		{
    			 lst.Add(Clone(obj));
    		}
    		return lst;
    	}
    
    	public CHIETKHAULOAIMATHANG getObject(string id)
    	{
    		return QueryableList().FirstOrDefault(p => p.IDUnit == id);
    	}
    
    	public CHIETKHAULOAIMATHANG getObject(Expression<Func<CHIETKHAULOAIMATHANG, bool>> predicate)
    	{
    		return  Queryable().FirstOrDefault(predicate);
    	}
    
    	 public string GetMaxCode()
         {
    		return QueryableList().Max(s=>s.IDUnit).ToString();
         }
    
    	 public List<CHIETKHAULOAIMATHANG> Search(string textSearch)
    	 {
    		List<CHIETKHAULOAIMATHANG> listIDUnit = QueryableList().Where(p=>p.IDUnit == textSearch).ToList();
    		if (listIDUnit.Count != 0)
    		{
        		return listIDUnit;
    		}
    		else
    		{
        		listIDUnit = QueryableList().Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
        		return listIDUnit.Count == 0
        		? QueryableList().Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
        		: listIDUnit;
    		}
    	 }
    
    	public List<CHIETKHAULOAIMATHANG> Search(Expression<Func<CHIETKHAULOAIMATHANG, bool>> predicate)
    	{
    		return  Queryable().Where(predicate).ToList();
    	}
    
    	public List<CHIETKHAULOAIMATHANG> Search(Expression<Func<CHIETKHAULOAIMATHANG, bool>> predicate,string textSearch)
    	{
    			List<CHIETKHAULOAIMATHANG> listIDUnit = Search(predicate).Where(p => p.IDUnit == textSearch).ToList();
                if (listIDUnit.Count != 0)
                {
                    return listIDUnit;
                }
                else
                {
                    listIDUnit = Search(predicate).Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
                    return listIDUnit.Count == 0
                    ? Search(predicate).Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
                    : listIDUnit;
                }
    	}
    }
}
