//------------------------------------------------------------------------------
// <auto-generated>
// Repository Generated
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.DataContext;
using Repository.Pattern.Ef6;
using Repository.Pattern.Repositories;
using Repository.Pattern.UnitOfWork;
using Util.Pattern;
using WH.Entity;
using System;

namespace WH.Service.Repository
{
    public partial interface ICHUCNANGRepository : IRepositoryAsync<CHUCNANG>
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<CHUCNANG, bool>> predicate);
    	CHUCNANG getObject(string id);
    	CHUCNANG getObject(Expression<Func<CHUCNANG, bool>> predicate);
    	
    
    	CHUCNANG CreateNew();
    	CHUCNANG CloneNew(CHUCNANG objCHUCNANG);
    	CHUCNANG CloneUpdate(CHUCNANG objCHUCNANG);
    	CHUCNANG Clone(CHUCNANG objCHUCNANG);
    
    	List< CHUCNANG> Clone(IList<CHUCNANG> listCHUCNANGs);
    	string GetMaxCode();
    	List<CHUCNANG> Search(string textSearch);
    	List<CHUCNANG> Search(Expression<Func<CHUCNANG, bool>> predicate);
    	List<CHUCNANG> Search(Expression<Func<CHUCNANG, bool>> predicate,string textSearch);
    }
    
    public partial class CHUCNANGRepository : Repository<CHUCNANG>, ICHUCNANGRepository
    {
    	public string DefaultCode
        {
    		get { return null; }
        }
    
        public CHUCNANGRepository(IDataContextAsync context, IUnitOfWorkAsync unitOfWork) : base(context, unitOfWork)
        {
        }
    
        public CHUCNANGRepository(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
    	public bool Exist(string id)
        {
    		return QueryableList().Any(p => p.IDUnit == id);
        }
    
    	public bool Exist(Expression<Func<CHUCNANG, bool>> predicate)
    	{
    		return Queryable().Any(predicate);
    	}
    
    	public CHUCNANG CreateNew()
        {
    		
    		CHUCNANG _obj = Create();
    
    				//_obj.NGUOIDUNG_QUYENHAN = null;//List
    		//_obj.NGUOIDUNG_QUYENHAN = new List<NGUOIDUNG_QUYENHAN>();//List
    					_obj.TENCHUCNANG = string.Empty;//string
    			        return _obj;
        }
    
    	public CHUCNANG CloneNew(CHUCNANG objCHUCNANG)
    	{
    		if(objCHUCNANG==null) return null;
    			 CHUCNANG objNew = Find(objCHUCNANG.MACHUCNANG);
    			if(objNew !=null) return null;
    
    		 objNew =  CreateNew();
    		 				objNew.MACHUCNANG =  objCHUCNANG.MACHUCNANG;
    								objNew.TENCHUCNANG =  objCHUCNANG.TENCHUCNANG;
    						  objNew.isAdd = true;
    		 return objNew;
    	}
    
    	public CHUCNANG CloneUpdate(CHUCNANG objCHUCNANG)
    	{
    		if(objCHUCNANG==null) return null;
    		 CHUCNANG objNew = Find(objCHUCNANG.MACHUCNANG);
    		 if(objNew==null) return null;
    		 				objNew.MACHUCNANG =  objCHUCNANG.MACHUCNANG;
    								objNew.TENCHUCNANG =  objCHUCNANG.TENCHUCNANG;
    						 objNew.isUpdate = true;
    		 return objNew;
    	}
    	public CHUCNANG Clone(CHUCNANG objCHUCNANG)
    	{
    		if(objCHUCNANG==null) return null;
    		 CHUCNANG objNew = Find(objCHUCNANG.MACHUCNANG);
    		 if(objNew==null) 
    		 {
    		 objNew =  CreateNew();
    		 				objNew.MACHUCNANG =  objCHUCNANG.MACHUCNANG;
    								objNew.TENCHUCNANG =  objCHUCNANG.TENCHUCNANG;
    						  objNew.isAdd = true;
    		 }
    		 else
    		 {
    		 				objNew.TENCHUCNANG =  objCHUCNANG.TENCHUCNANG;
    						 objNew.isUpdate = true;
    		  objNew.isLoaded = true;
    		 }
    		 return objNew;
    	}
    
    	public List< CHUCNANG> Clone(IList<CHUCNANG> listCHUCNANGs)
    	{
    		List< CHUCNANG> lst = new List< CHUCNANG>();
    		if(listCHUCNANGs == null) return lst;
    		foreach(var obj in  listCHUCNANGs)
    		{
    			 lst.Add(Clone(obj));
    		}
    		return lst;
    	}
    
    	public CHUCNANG getObject(string id)
    	{
    		return QueryableList().FirstOrDefault(p => p.IDUnit == id);
    	}
    
    	public CHUCNANG getObject(Expression<Func<CHUCNANG, bool>> predicate)
    	{
    		return  Queryable().FirstOrDefault(predicate);
    	}
    
    	 public string GetMaxCode()
         {
    		return QueryableList().Max(s=>s.IDUnit).ToString();
         }
    
    	 public List<CHUCNANG> Search(string textSearch)
    	 {
    		List<CHUCNANG> listIDUnit = QueryableList().Where(p=>p.IDUnit == textSearch).ToList();
    		if (listIDUnit.Count != 0)
    		{
        		return listIDUnit;
    		}
    		else
    		{
        		listIDUnit = QueryableList().Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
        		return listIDUnit.Count == 0
        		? QueryableList().Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
        		: listIDUnit;
    		}
    	 }
    
    	public List<CHUCNANG> Search(Expression<Func<CHUCNANG, bool>> predicate)
    	{
    		return  Queryable().Where(predicate).ToList();
    	}
    
    	public List<CHUCNANG> Search(Expression<Func<CHUCNANG, bool>> predicate,string textSearch)
    	{
    			List<CHUCNANG> listIDUnit = Search(predicate).Where(p => p.IDUnit == textSearch).ToList();
                if (listIDUnit.Count != 0)
                {
                    return listIDUnit;
                }
                else
                {
                    listIDUnit = Search(predicate).Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
                    return listIDUnit.Count == 0
                    ? Search(predicate).Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
                    : listIDUnit;
                }
    	}
    }
}
