//------------------------------------------------------------------------------
// <auto-generated>
// Repository Generated
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.DataContext;
using Repository.Pattern.Ef6;
using Repository.Pattern.Repositories;
using Repository.Pattern.UnitOfWork;
using Util.Pattern;
using WH.Entity;
using System;

namespace WH.Service.Repository
{
    public partial interface ICONFIG_PRINTERRepository : IRepositoryAsync<CONFIG_PRINTER>
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<CONFIG_PRINTER, bool>> predicate);
    	CONFIG_PRINTER getObject(string id);
    	CONFIG_PRINTER getObject(Expression<Func<CONFIG_PRINTER, bool>> predicate);
    	
    
    	CONFIG_PRINTER CreateNew();
    	CONFIG_PRINTER CloneNew(CONFIG_PRINTER objCONFIG_PRINTER);
    	CONFIG_PRINTER CloneUpdate(CONFIG_PRINTER objCONFIG_PRINTER);
    	CONFIG_PRINTER Clone(CONFIG_PRINTER objCONFIG_PRINTER);
    
    	List< CONFIG_PRINTER> Clone(IList<CONFIG_PRINTER> listCONFIG_PRINTERs);
    	string GetMaxCode();
    	List<CONFIG_PRINTER> Search(string textSearch);
    	List<CONFIG_PRINTER> Search(Expression<Func<CONFIG_PRINTER, bool>> predicate);
    	List<CONFIG_PRINTER> Search(Expression<Func<CONFIG_PRINTER, bool>> predicate,string textSearch);
    }
    
    public partial class CONFIG_PRINTERRepository : Repository<CONFIG_PRINTER>, ICONFIG_PRINTERRepository
    {
    	public string DefaultCode
        {
    		get { return null; }
        }
    
        public CONFIG_PRINTERRepository(IDataContextAsync context, IUnitOfWorkAsync unitOfWork) : base(context, unitOfWork)
        {
        }
    
        public CONFIG_PRINTERRepository(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
    	public bool Exist(string id)
        {
    		return QueryableList().Any(p => p.IDUnit == id);
        }
    
    	public bool Exist(Expression<Func<CONFIG_PRINTER, bool>> predicate)
    	{
    		return Queryable().Any(predicate);
    	}
    
    	public CONFIG_PRINTER CreateNew()
        {
    		
    		CONFIG_PRINTER _obj = Create();
    
    				_obj.Name = string.Empty;//string
    					_obj.IP = string.Empty;//string
    					_obj.IsUse = null;//Nullable<bool>
    									_obj.Note = string.Empty;//string
    			        return _obj;
        }
    
    	public CONFIG_PRINTER CloneNew(CONFIG_PRINTER objCONFIG_PRINTER)
    	{
    		if(objCONFIG_PRINTER==null) return null;
    			 CONFIG_PRINTER objNew = Find(objCONFIG_PRINTER.ID);
    			if(objNew !=null) return null;
    
    		 objNew =  CreateNew();
    		 				objNew.ID =  objCONFIG_PRINTER.ID;
    								objNew.Name =  objCONFIG_PRINTER.Name;
    								objNew.IP =  objCONFIG_PRINTER.IP;
    								objNew.NumberPrint =  objCONFIG_PRINTER.NumberPrint;
    								objNew.IsUse =  objCONFIG_PRINTER.IsUse;
    								objNew.Note =  objCONFIG_PRINTER.Note;
    						  objNew.isAdd = true;
    		 return objNew;
    	}
    
    	public CONFIG_PRINTER CloneUpdate(CONFIG_PRINTER objCONFIG_PRINTER)
    	{
    		if(objCONFIG_PRINTER==null) return null;
    		 CONFIG_PRINTER objNew = Find(objCONFIG_PRINTER.ID);
    		 if(objNew==null) return null;
    		 				objNew.ID =  objCONFIG_PRINTER.ID;
    								objNew.Name =  objCONFIG_PRINTER.Name;
    								objNew.IP =  objCONFIG_PRINTER.IP;
    								objNew.NumberPrint =  objCONFIG_PRINTER.NumberPrint;
    								objNew.IsUse =  objCONFIG_PRINTER.IsUse;
    								objNew.Note =  objCONFIG_PRINTER.Note;
    						 objNew.isUpdate = true;
    		 return objNew;
    	}
    	public CONFIG_PRINTER Clone(CONFIG_PRINTER objCONFIG_PRINTER)
    	{
    		if(objCONFIG_PRINTER==null) return null;
    		 CONFIG_PRINTER objNew = Find(objCONFIG_PRINTER.ID);
    		 if(objNew==null) 
    		 {
    		 objNew =  CreateNew();
    		 				objNew.ID =  objCONFIG_PRINTER.ID;
    								objNew.Name =  objCONFIG_PRINTER.Name;
    								objNew.IP =  objCONFIG_PRINTER.IP;
    								objNew.NumberPrint =  objCONFIG_PRINTER.NumberPrint;
    								objNew.IsUse =  objCONFIG_PRINTER.IsUse;
    								objNew.Note =  objCONFIG_PRINTER.Note;
    						  objNew.isAdd = true;
    		 }
    		 else
    		 {
    		 				objNew.Name =  objCONFIG_PRINTER.Name;
    								objNew.IP =  objCONFIG_PRINTER.IP;
    								objNew.NumberPrint =  objCONFIG_PRINTER.NumberPrint;
    								objNew.IsUse =  objCONFIG_PRINTER.IsUse;
    								objNew.Note =  objCONFIG_PRINTER.Note;
    						 objNew.isUpdate = true;
    		  objNew.isLoaded = true;
    		 }
    		 return objNew;
    	}
    
    	public List< CONFIG_PRINTER> Clone(IList<CONFIG_PRINTER> listCONFIG_PRINTERs)
    	{
    		List< CONFIG_PRINTER> lst = new List< CONFIG_PRINTER>();
    		if(listCONFIG_PRINTERs == null) return lst;
    		foreach(var obj in  listCONFIG_PRINTERs)
    		{
    			 lst.Add(Clone(obj));
    		}
    		return lst;
    	}
    
    	public CONFIG_PRINTER getObject(string id)
    	{
    		return QueryableList().FirstOrDefault(p => p.IDUnit == id);
    	}
    
    	public CONFIG_PRINTER getObject(Expression<Func<CONFIG_PRINTER, bool>> predicate)
    	{
    		return  Queryable().FirstOrDefault(predicate);
    	}
    
    	 public string GetMaxCode()
         {
    		return QueryableList().Max(s=>s.IDUnit).ToString();
         }
    
    	 public List<CONFIG_PRINTER> Search(string textSearch)
    	 {
    		List<CONFIG_PRINTER> listIDUnit = QueryableList().Where(p=>p.IDUnit == textSearch).ToList();
    		if (listIDUnit.Count != 0)
    		{
        		return listIDUnit;
    		}
    		else
    		{
        		listIDUnit = QueryableList().Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
        		return listIDUnit.Count == 0
        		? QueryableList().Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
        		: listIDUnit;
    		}
    	 }
    
    	public List<CONFIG_PRINTER> Search(Expression<Func<CONFIG_PRINTER, bool>> predicate)
    	{
    		return  Queryable().Where(predicate).ToList();
    	}
    
    	public List<CONFIG_PRINTER> Search(Expression<Func<CONFIG_PRINTER, bool>> predicate,string textSearch)
    	{
    			List<CONFIG_PRINTER> listIDUnit = Search(predicate).Where(p => p.IDUnit == textSearch).ToList();
                if (listIDUnit.Count != 0)
                {
                    return listIDUnit;
                }
                else
                {
                    listIDUnit = Search(predicate).Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
                    return listIDUnit.Count == 0
                    ? Search(predicate).Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
                    : listIDUnit;
                }
    	}
    }
}
