//------------------------------------------------------------------------------
// <auto-generated>
// Repository Generated
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.DataContext;
using Repository.Pattern.Ef6;
using Repository.Pattern.Repositories;
using Repository.Pattern.UnitOfWork;
using Util.Pattern;
using WH.Entity;
using System;

namespace WH.Service.Repository
{
    public partial interface IHOADONNHAPXUATCHITIETRepository : IRepositoryAsync<HOADONNHAPXUATCHITIET>
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<HOADONNHAPXUATCHITIET, bool>> predicate);
    	HOADONNHAPXUATCHITIET getObject(string id);
    	HOADONNHAPXUATCHITIET getObject(Expression<Func<HOADONNHAPXUATCHITIET, bool>> predicate);
    	
    
    	HOADONNHAPXUATCHITIET CreateNew();
    	HOADONNHAPXUATCHITIET CloneNew(HOADONNHAPXUATCHITIET objHOADONNHAPXUATCHITIET);
    	HOADONNHAPXUATCHITIET CloneUpdate(HOADONNHAPXUATCHITIET objHOADONNHAPXUATCHITIET);
    	HOADONNHAPXUATCHITIET Clone(HOADONNHAPXUATCHITIET objHOADONNHAPXUATCHITIET);
    
    	List< HOADONNHAPXUATCHITIET> Clone(IList<HOADONNHAPXUATCHITIET> listHOADONNHAPXUATCHITIETs);
    	string GetMaxCode();
    	List<HOADONNHAPXUATCHITIET> Search(string textSearch);
    	List<HOADONNHAPXUATCHITIET> Search(Expression<Func<HOADONNHAPXUATCHITIET, bool>> predicate);
    	List<HOADONNHAPXUATCHITIET> Search(Expression<Func<HOADONNHAPXUATCHITIET, bool>> predicate,string textSearch);
    }
    
    public partial class HOADONNHAPXUATCHITIETRepository : Repository<HOADONNHAPXUATCHITIET>, IHOADONNHAPXUATCHITIETRepository
    {
    	public string DefaultCode
        {
    		get { return null; }
        }
    
        public HOADONNHAPXUATCHITIETRepository(IDataContextAsync context, IUnitOfWorkAsync unitOfWork) : base(context, unitOfWork)
        {
        }
    
        public HOADONNHAPXUATCHITIETRepository(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
    	public bool Exist(string id)
        {
    		return QueryableList().Any(p => p.IDUnit == id);
        }
    
    	public bool Exist(Expression<Func<HOADONNHAPXUATCHITIET, bool>> predicate)
    	{
    		return Queryable().Any(predicate);
    	}
    
    	public HOADONNHAPXUATCHITIET CreateNew()
        {
    		
    		HOADONNHAPXUATCHITIET _obj = Create();
    
    				//_obj.HOADONNHAPXUAT = null;//object
    		_obj.MAHOADON = null;//string
    									//_obj.KHO = null;//object
    		_obj.MAKHO =  null;////Nullable<System.Guid>
    									//_obj.MATHANG = null;//object
    		_obj.MAMATHANG =  null;////Nullable<int>
    										//Primary Key
    			_obj.MACHITIETHOADON = DateTime.Now.ToString("ddMMyyyyHHmmssfff"); //string
    						
    									_obj.ISCKPHANTRAM = null;//Nullable<bool>
    									_obj.GHICHU = string.Empty;//string
    					_obj.ISDELETE = null;//Nullable<bool>
    							        return _obj;
        }
    
    	public HOADONNHAPXUATCHITIET CloneNew(HOADONNHAPXUATCHITIET objHOADONNHAPXUATCHITIET)
    	{
    		if(objHOADONNHAPXUATCHITIET==null) return null;
    			 HOADONNHAPXUATCHITIET objNew = Find(objHOADONNHAPXUATCHITIET.MACHITIETHOADON);
    			if(objNew !=null) return null;
    
    		 objNew =  CreateNew();
    		 				objNew.MACHITIETHOADON =  objHOADONNHAPXUATCHITIET.MACHITIETHOADON;
    								objNew.MAHOADON =  objHOADONNHAPXUATCHITIET.MAHOADON;
    								objNew.MAKHO =  objHOADONNHAPXUATCHITIET.MAKHO;
    								objNew.MAMATHANG =  objHOADONNHAPXUATCHITIET.MAMATHANG;
    								objNew.SOLUONGSI =  objHOADONNHAPXUATCHITIET.SOLUONGSI;
    								objNew.SOLUONGLE =  objHOADONNHAPXUATCHITIET.SOLUONGLE;
    								objNew.DONGIASI =  objHOADONNHAPXUATCHITIET.DONGIASI;
    								objNew.CHIETKHAUTHEOPHANTRAM =  objHOADONNHAPXUATCHITIET.CHIETKHAUTHEOPHANTRAM;
    								objNew.CHIETKHAUTHEOTIEN =  objHOADONNHAPXUATCHITIET.CHIETKHAUTHEOTIEN;
    								objNew.ISCKPHANTRAM =  objHOADONNHAPXUATCHITIET.ISCKPHANTRAM;
    								objNew.THANHTIENTRUOCCHIETKHAU_CT =  objHOADONNHAPXUATCHITIET.THANHTIENTRUOCCHIETKHAU_CT;
    								objNew.THANHTIENSAUCHIETKHAU_CT =  objHOADONNHAPXUATCHITIET.THANHTIENSAUCHIETKHAU_CT;
    								objNew.GHICHU =  objHOADONNHAPXUATCHITIET.GHICHU;
    								objNew.ISDELETE =  objHOADONNHAPXUATCHITIET.ISDELETE;
    						  objNew.isAdd = true;
    		 return objNew;
    	}
    
    	public HOADONNHAPXUATCHITIET CloneUpdate(HOADONNHAPXUATCHITIET objHOADONNHAPXUATCHITIET)
    	{
    		if(objHOADONNHAPXUATCHITIET==null) return null;
    		 HOADONNHAPXUATCHITIET objNew = Find(objHOADONNHAPXUATCHITIET.MACHITIETHOADON);
    		 if(objNew==null) return null;
    		 				objNew.MACHITIETHOADON =  objHOADONNHAPXUATCHITIET.MACHITIETHOADON;
    								objNew.MAHOADON =  objHOADONNHAPXUATCHITIET.MAHOADON;
    								objNew.MAKHO =  objHOADONNHAPXUATCHITIET.MAKHO;
    								objNew.MAMATHANG =  objHOADONNHAPXUATCHITIET.MAMATHANG;
    								objNew.SOLUONGSI =  objHOADONNHAPXUATCHITIET.SOLUONGSI;
    								objNew.SOLUONGLE =  objHOADONNHAPXUATCHITIET.SOLUONGLE;
    								objNew.DONGIASI =  objHOADONNHAPXUATCHITIET.DONGIASI;
    								objNew.CHIETKHAUTHEOPHANTRAM =  objHOADONNHAPXUATCHITIET.CHIETKHAUTHEOPHANTRAM;
    								objNew.CHIETKHAUTHEOTIEN =  objHOADONNHAPXUATCHITIET.CHIETKHAUTHEOTIEN;
    								objNew.ISCKPHANTRAM =  objHOADONNHAPXUATCHITIET.ISCKPHANTRAM;
    								objNew.THANHTIENTRUOCCHIETKHAU_CT =  objHOADONNHAPXUATCHITIET.THANHTIENTRUOCCHIETKHAU_CT;
    								objNew.THANHTIENSAUCHIETKHAU_CT =  objHOADONNHAPXUATCHITIET.THANHTIENSAUCHIETKHAU_CT;
    								objNew.GHICHU =  objHOADONNHAPXUATCHITIET.GHICHU;
    								objNew.ISDELETE =  objHOADONNHAPXUATCHITIET.ISDELETE;
    						 objNew.isUpdate = true;
    		 return objNew;
    	}
    	public HOADONNHAPXUATCHITIET Clone(HOADONNHAPXUATCHITIET objHOADONNHAPXUATCHITIET)
    	{
    		if(objHOADONNHAPXUATCHITIET==null) return null;
    		 HOADONNHAPXUATCHITIET objNew = Find(objHOADONNHAPXUATCHITIET.MACHITIETHOADON);
    		 if(objNew==null) 
    		 {
    		 objNew =  CreateNew();
    		 				objNew.MACHITIETHOADON =  objHOADONNHAPXUATCHITIET.MACHITIETHOADON;
    								objNew.MAHOADON =  objHOADONNHAPXUATCHITIET.MAHOADON;
    								objNew.MAKHO =  objHOADONNHAPXUATCHITIET.MAKHO;
    								objNew.MAMATHANG =  objHOADONNHAPXUATCHITIET.MAMATHANG;
    								objNew.SOLUONGSI =  objHOADONNHAPXUATCHITIET.SOLUONGSI;
    								objNew.SOLUONGLE =  objHOADONNHAPXUATCHITIET.SOLUONGLE;
    								objNew.DONGIASI =  objHOADONNHAPXUATCHITIET.DONGIASI;
    								objNew.CHIETKHAUTHEOPHANTRAM =  objHOADONNHAPXUATCHITIET.CHIETKHAUTHEOPHANTRAM;
    								objNew.CHIETKHAUTHEOTIEN =  objHOADONNHAPXUATCHITIET.CHIETKHAUTHEOTIEN;
    								objNew.ISCKPHANTRAM =  objHOADONNHAPXUATCHITIET.ISCKPHANTRAM;
    								objNew.THANHTIENTRUOCCHIETKHAU_CT =  objHOADONNHAPXUATCHITIET.THANHTIENTRUOCCHIETKHAU_CT;
    								objNew.THANHTIENSAUCHIETKHAU_CT =  objHOADONNHAPXUATCHITIET.THANHTIENSAUCHIETKHAU_CT;
    								objNew.GHICHU =  objHOADONNHAPXUATCHITIET.GHICHU;
    								objNew.ISDELETE =  objHOADONNHAPXUATCHITIET.ISDELETE;
    						  objNew.isAdd = true;
    		 }
    		 else
    		 {
    		 				objNew.MAHOADON =  objHOADONNHAPXUATCHITIET.MAHOADON;
    								objNew.MAKHO =  objHOADONNHAPXUATCHITIET.MAKHO;
    								objNew.MAMATHANG =  objHOADONNHAPXUATCHITIET.MAMATHANG;
    								objNew.SOLUONGSI =  objHOADONNHAPXUATCHITIET.SOLUONGSI;
    								objNew.SOLUONGLE =  objHOADONNHAPXUATCHITIET.SOLUONGLE;
    								objNew.DONGIASI =  objHOADONNHAPXUATCHITIET.DONGIASI;
    								objNew.CHIETKHAUTHEOPHANTRAM =  objHOADONNHAPXUATCHITIET.CHIETKHAUTHEOPHANTRAM;
    								objNew.CHIETKHAUTHEOTIEN =  objHOADONNHAPXUATCHITIET.CHIETKHAUTHEOTIEN;
    								objNew.ISCKPHANTRAM =  objHOADONNHAPXUATCHITIET.ISCKPHANTRAM;
    								objNew.THANHTIENTRUOCCHIETKHAU_CT =  objHOADONNHAPXUATCHITIET.THANHTIENTRUOCCHIETKHAU_CT;
    								objNew.THANHTIENSAUCHIETKHAU_CT =  objHOADONNHAPXUATCHITIET.THANHTIENSAUCHIETKHAU_CT;
    								objNew.GHICHU =  objHOADONNHAPXUATCHITIET.GHICHU;
    								objNew.ISDELETE =  objHOADONNHAPXUATCHITIET.ISDELETE;
    						 objNew.isUpdate = true;
    		  objNew.isLoaded = true;
    		 }
    		 return objNew;
    	}
    
    	public List< HOADONNHAPXUATCHITIET> Clone(IList<HOADONNHAPXUATCHITIET> listHOADONNHAPXUATCHITIETs)
    	{
    		List< HOADONNHAPXUATCHITIET> lst = new List< HOADONNHAPXUATCHITIET>();
    		if(listHOADONNHAPXUATCHITIETs == null) return lst;
    		foreach(var obj in  listHOADONNHAPXUATCHITIETs)
    		{
    			 lst.Add(Clone(obj));
    		}
    		return lst;
    	}
    
    	public HOADONNHAPXUATCHITIET getObject(string id)
    	{
    		return QueryableList().FirstOrDefault(p => p.IDUnit == id);
    	}
    
    	public HOADONNHAPXUATCHITIET getObject(Expression<Func<HOADONNHAPXUATCHITIET, bool>> predicate)
    	{
    		return  Queryable().FirstOrDefault(predicate);
    	}
    
    	 public string GetMaxCode()
         {
    		return QueryableList().Max(s=>s.IDUnit).ToString();
         }
    
    	 public List<HOADONNHAPXUATCHITIET> Search(string textSearch)
    	 {
    		List<HOADONNHAPXUATCHITIET> listIDUnit = QueryableList().Where(p=>p.IDUnit == textSearch).ToList();
    		if (listIDUnit.Count != 0)
    		{
        		return listIDUnit;
    		}
    		else
    		{
        		listIDUnit = QueryableList().Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
        		return listIDUnit.Count == 0
        		? QueryableList().Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
        		: listIDUnit;
    		}
    	 }
    
    	public List<HOADONNHAPXUATCHITIET> Search(Expression<Func<HOADONNHAPXUATCHITIET, bool>> predicate)
    	{
    		return  Queryable().Where(predicate).ToList();
    	}
    
    	public List<HOADONNHAPXUATCHITIET> Search(Expression<Func<HOADONNHAPXUATCHITIET, bool>> predicate,string textSearch)
    	{
    			List<HOADONNHAPXUATCHITIET> listIDUnit = Search(predicate).Where(p => p.IDUnit == textSearch).ToList();
                if (listIDUnit.Count != 0)
                {
                    return listIDUnit;
                }
                else
                {
                    listIDUnit = Search(predicate).Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
                    return listIDUnit.Count == 0
                    ? Search(predicate).Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
                    : listIDUnit;
                }
    	}
    }
}
