//------------------------------------------------------------------------------
// <auto-generated>
// Repository Generated
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.DataContext;
using Repository.Pattern.Ef6;
using Repository.Pattern.Repositories;
using Repository.Pattern.UnitOfWork;
using Util.Pattern;
using WH.Entity;
using System;

namespace WH.Service.Repository
{
    public partial interface IHOADONNHAPXUATRepository : IRepositoryAsync<HOADONNHAPXUAT>
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<HOADONNHAPXUAT, bool>> predicate);
    	HOADONNHAPXUAT getObject(string id);
    	HOADONNHAPXUAT getObject(Expression<Func<HOADONNHAPXUAT, bool>> predicate);
    	
    
    	HOADONNHAPXUAT CreateNew();
    	HOADONNHAPXUAT CloneNew(HOADONNHAPXUAT objHOADONNHAPXUAT);
    	HOADONNHAPXUAT CloneUpdate(HOADONNHAPXUAT objHOADONNHAPXUAT);
    	HOADONNHAPXUAT Clone(HOADONNHAPXUAT objHOADONNHAPXUAT);
    
    	List< HOADONNHAPXUAT> Clone(IList<HOADONNHAPXUAT> listHOADONNHAPXUATs);
    	string GetMaxCode();
    	List<HOADONNHAPXUAT> Search(string textSearch);
    	List<HOADONNHAPXUAT> Search(Expression<Func<HOADONNHAPXUAT, bool>> predicate);
    	List<HOADONNHAPXUAT> Search(Expression<Func<HOADONNHAPXUAT, bool>> predicate,string textSearch);
    }
    
    public partial class HOADONNHAPXUATRepository : Repository<HOADONNHAPXUAT>, IHOADONNHAPXUATRepository
    {
    	public string DefaultCode
        {
    		get { return null; }
        }
    
        public HOADONNHAPXUATRepository(IDataContextAsync context, IUnitOfWorkAsync unitOfWork) : base(context, unitOfWork)
        {
        }
    
        public HOADONNHAPXUATRepository(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
    	public bool Exist(string id)
        {
    		return QueryableList().Any(p => p.IDUnit == id);
        }
    
    	public bool Exist(Expression<Func<HOADONNHAPXUAT, bool>> predicate)
    	{
    		return Queryable().Any(predicate);
    	}
    
    	public HOADONNHAPXUAT CreateNew()
        {
    		
    		HOADONNHAPXUAT _obj = Create();
    
    				//_obj.HOADONNHAPXUATCHITIETs = null;//List
    		//_obj.HOADONNHAPXUATCHITIETs = new List<HOADONNHAPXUATCHITIET>();//List
    					//_obj.KHACHHANG = null;//object
    		_obj.MAKHACHHANG =  null;////Nullable<System.Guid>
    										//Primary Key
    			_obj.MAHOADON = DateTime.Now.ToString("ddMMyyyyHHmmssfff"); //string
    						
    										_obj.HANTHANHTOAN = null;//Nullable<System.DateTime>
    									_obj.GHICHU_HD = string.Empty;//string
    					_obj.DATHANHTOAN = null;//Nullable<bool>
    									_obj.NGUOITAO = string.Empty;//string
    						_obj.NGAYTAOHOADON = null;//Nullable<System.DateTime>
    									_obj.ISDELETE = null;//Nullable<bool>
    							        return _obj;
        }
    
    	public HOADONNHAPXUAT CloneNew(HOADONNHAPXUAT objHOADONNHAPXUAT)
    	{
    		if(objHOADONNHAPXUAT==null) return null;
    			 HOADONNHAPXUAT objNew = Find(objHOADONNHAPXUAT.MAHOADON);
    			if(objNew !=null) return null;
    
    		 objNew =  CreateNew();
    		 				objNew.MAHOADON =  objHOADONNHAPXUAT.MAHOADON;
    								objNew.THANHTIENCHUACK_HD =  objHOADONNHAPXUAT.THANHTIENCHUACK_HD;
    								objNew.TIENCHIETKHAU_HD =  objHOADONNHAPXUAT.TIENCHIETKHAU_HD;
    								objNew.TIENKHUYENMAI_HD =  objHOADONNHAPXUAT.TIENKHUYENMAI_HD;
    								objNew.SOTIENTHANHTOAN_HD =  objHOADONNHAPXUAT.SOTIENTHANHTOAN_HD;
    								objNew.SOTIENKHACHDUA_HD =  objHOADONNHAPXUAT.SOTIENKHACHDUA_HD;
    								objNew.LOAIHOADON =  objHOADONNHAPXUAT.LOAIHOADON;
    								objNew.HANTHANHTOAN =  objHOADONNHAPXUAT.HANTHANHTOAN;
    								objNew.GHICHU_HD =  objHOADONNHAPXUAT.GHICHU_HD;
    								objNew.DATHANHTOAN =  objHOADONNHAPXUAT.DATHANHTOAN;
    								objNew.NGUOITAO =  objHOADONNHAPXUAT.NGUOITAO;
    								objNew.NGAYTAOHOADON =  objHOADONNHAPXUAT.NGAYTAOHOADON;
    								objNew.ISDELETE =  objHOADONNHAPXUAT.ISDELETE;
    								objNew.MAKHACHHANG =  objHOADONNHAPXUAT.MAKHACHHANG;
    								objNew.MACA =  objHOADONNHAPXUAT.MACA;
    						  objNew.isAdd = true;
    		 return objNew;
    	}
    
    	public HOADONNHAPXUAT CloneUpdate(HOADONNHAPXUAT objHOADONNHAPXUAT)
    	{
    		if(objHOADONNHAPXUAT==null) return null;
    		 HOADONNHAPXUAT objNew = Find(objHOADONNHAPXUAT.MAHOADON);
    		 if(objNew==null) return null;
    		 				objNew.MAHOADON =  objHOADONNHAPXUAT.MAHOADON;
    								objNew.THANHTIENCHUACK_HD =  objHOADONNHAPXUAT.THANHTIENCHUACK_HD;
    								objNew.TIENCHIETKHAU_HD =  objHOADONNHAPXUAT.TIENCHIETKHAU_HD;
    								objNew.TIENKHUYENMAI_HD =  objHOADONNHAPXUAT.TIENKHUYENMAI_HD;
    								objNew.SOTIENTHANHTOAN_HD =  objHOADONNHAPXUAT.SOTIENTHANHTOAN_HD;
    								objNew.SOTIENKHACHDUA_HD =  objHOADONNHAPXUAT.SOTIENKHACHDUA_HD;
    								objNew.LOAIHOADON =  objHOADONNHAPXUAT.LOAIHOADON;
    								objNew.HANTHANHTOAN =  objHOADONNHAPXUAT.HANTHANHTOAN;
    								objNew.GHICHU_HD =  objHOADONNHAPXUAT.GHICHU_HD;
    								objNew.DATHANHTOAN =  objHOADONNHAPXUAT.DATHANHTOAN;
    								objNew.NGUOITAO =  objHOADONNHAPXUAT.NGUOITAO;
    								objNew.NGAYTAOHOADON =  objHOADONNHAPXUAT.NGAYTAOHOADON;
    								objNew.ISDELETE =  objHOADONNHAPXUAT.ISDELETE;
    								objNew.MAKHACHHANG =  objHOADONNHAPXUAT.MAKHACHHANG;
    								objNew.MACA =  objHOADONNHAPXUAT.MACA;
    						 objNew.isUpdate = true;
    		 return objNew;
    	}
    	public HOADONNHAPXUAT Clone(HOADONNHAPXUAT objHOADONNHAPXUAT)
    	{
    		if(objHOADONNHAPXUAT==null) return null;
    		 HOADONNHAPXUAT objNew = Find(objHOADONNHAPXUAT.MAHOADON);
    		 if(objNew==null) 
    		 {
    		 objNew =  CreateNew();
    		 				objNew.MAHOADON =  objHOADONNHAPXUAT.MAHOADON;
    								objNew.THANHTIENCHUACK_HD =  objHOADONNHAPXUAT.THANHTIENCHUACK_HD;
    								objNew.TIENCHIETKHAU_HD =  objHOADONNHAPXUAT.TIENCHIETKHAU_HD;
    								objNew.TIENKHUYENMAI_HD =  objHOADONNHAPXUAT.TIENKHUYENMAI_HD;
    								objNew.SOTIENTHANHTOAN_HD =  objHOADONNHAPXUAT.SOTIENTHANHTOAN_HD;
    								objNew.SOTIENKHACHDUA_HD =  objHOADONNHAPXUAT.SOTIENKHACHDUA_HD;
    								objNew.LOAIHOADON =  objHOADONNHAPXUAT.LOAIHOADON;
    								objNew.HANTHANHTOAN =  objHOADONNHAPXUAT.HANTHANHTOAN;
    								objNew.GHICHU_HD =  objHOADONNHAPXUAT.GHICHU_HD;
    								objNew.DATHANHTOAN =  objHOADONNHAPXUAT.DATHANHTOAN;
    								objNew.NGUOITAO =  objHOADONNHAPXUAT.NGUOITAO;
    								objNew.NGAYTAOHOADON =  objHOADONNHAPXUAT.NGAYTAOHOADON;
    								objNew.ISDELETE =  objHOADONNHAPXUAT.ISDELETE;
    								objNew.MAKHACHHANG =  objHOADONNHAPXUAT.MAKHACHHANG;
    								objNew.MACA =  objHOADONNHAPXUAT.MACA;
    						  objNew.isAdd = true;
    		 }
    		 else
    		 {
    		 				objNew.THANHTIENCHUACK_HD =  objHOADONNHAPXUAT.THANHTIENCHUACK_HD;
    								objNew.TIENCHIETKHAU_HD =  objHOADONNHAPXUAT.TIENCHIETKHAU_HD;
    								objNew.TIENKHUYENMAI_HD =  objHOADONNHAPXUAT.TIENKHUYENMAI_HD;
    								objNew.SOTIENTHANHTOAN_HD =  objHOADONNHAPXUAT.SOTIENTHANHTOAN_HD;
    								objNew.SOTIENKHACHDUA_HD =  objHOADONNHAPXUAT.SOTIENKHACHDUA_HD;
    								objNew.LOAIHOADON =  objHOADONNHAPXUAT.LOAIHOADON;
    								objNew.HANTHANHTOAN =  objHOADONNHAPXUAT.HANTHANHTOAN;
    								objNew.GHICHU_HD =  objHOADONNHAPXUAT.GHICHU_HD;
    								objNew.DATHANHTOAN =  objHOADONNHAPXUAT.DATHANHTOAN;
    								objNew.NGUOITAO =  objHOADONNHAPXUAT.NGUOITAO;
    								objNew.NGAYTAOHOADON =  objHOADONNHAPXUAT.NGAYTAOHOADON;
    								objNew.ISDELETE =  objHOADONNHAPXUAT.ISDELETE;
    								objNew.MAKHACHHANG =  objHOADONNHAPXUAT.MAKHACHHANG;
    								objNew.MACA =  objHOADONNHAPXUAT.MACA;
    						 objNew.isUpdate = true;
    		  objNew.isLoaded = true;
    		 }
    		 return objNew;
    	}
    
    	public List< HOADONNHAPXUAT> Clone(IList<HOADONNHAPXUAT> listHOADONNHAPXUATs)
    	{
    		List< HOADONNHAPXUAT> lst = new List< HOADONNHAPXUAT>();
    		if(listHOADONNHAPXUATs == null) return lst;
    		foreach(var obj in  listHOADONNHAPXUATs)
    		{
    			 lst.Add(Clone(obj));
    		}
    		return lst;
    	}
    
    	public HOADONNHAPXUAT getObject(string id)
    	{
    		return QueryableList().FirstOrDefault(p => p.IDUnit == id);
    	}
    
    	public HOADONNHAPXUAT getObject(Expression<Func<HOADONNHAPXUAT, bool>> predicate)
    	{
    		return  Queryable().FirstOrDefault(predicate);
    	}
    
    	 public string GetMaxCode()
         {
    		return QueryableList().Max(s=>s.IDUnit).ToString();
         }
    
    	 public List<HOADONNHAPXUAT> Search(string textSearch)
    	 {
    		List<HOADONNHAPXUAT> listIDUnit = QueryableList().Where(p=>p.IDUnit == textSearch).ToList();
    		if (listIDUnit.Count != 0)
    		{
        		return listIDUnit;
    		}
    		else
    		{
        		listIDUnit = QueryableList().Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
        		return listIDUnit.Count == 0
        		? QueryableList().Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
        		: listIDUnit;
    		}
    	 }
    
    	public List<HOADONNHAPXUAT> Search(Expression<Func<HOADONNHAPXUAT, bool>> predicate)
    	{
    		return  Queryable().Where(predicate).ToList();
    	}
    
    	public List<HOADONNHAPXUAT> Search(Expression<Func<HOADONNHAPXUAT, bool>> predicate,string textSearch)
    	{
    			List<HOADONNHAPXUAT> listIDUnit = Search(predicate).Where(p => p.IDUnit == textSearch).ToList();
                if (listIDUnit.Count != 0)
                {
                    return listIDUnit;
                }
                else
                {
                    listIDUnit = Search(predicate).Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
                    return listIDUnit.Count == 0
                    ? Search(predicate).Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
                    : listIDUnit;
                }
    	}
    }
}
