//------------------------------------------------------------------------------
// <auto-generated>
// Repository Generated
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.DataContext;
using Repository.Pattern.Ef6;
using Repository.Pattern.Repositories;
using Repository.Pattern.UnitOfWork;
using Util.Pattern;
using WH.Entity;
using System;

namespace WH.Service.Repository
{
    public partial interface IKHACHHANGNHOMRepository : IRepositoryAsync<KHACHHANGNHOM>
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<KHACHHANGNHOM, bool>> predicate);
    	KHACHHANGNHOM getObject(string id);
    	KHACHHANGNHOM getObject(Expression<Func<KHACHHANGNHOM, bool>> predicate);
    	
    
    	KHACHHANGNHOM CreateNew();
    	KHACHHANGNHOM CloneNew(KHACHHANGNHOM objKHACHHANGNHOM);
    	KHACHHANGNHOM CloneUpdate(KHACHHANGNHOM objKHACHHANGNHOM);
    	KHACHHANGNHOM Clone(KHACHHANGNHOM objKHACHHANGNHOM);
    
    	List< KHACHHANGNHOM> Clone(IList<KHACHHANGNHOM> listKHACHHANGNHOMs);
    	string GetMaxCode();
    	List<KHACHHANGNHOM> Search(string textSearch);
    	List<KHACHHANGNHOM> Search(Expression<Func<KHACHHANGNHOM, bool>> predicate);
    	List<KHACHHANGNHOM> Search(Expression<Func<KHACHHANGNHOM, bool>> predicate,string textSearch);
    }
    
    public partial class KHACHHANGNHOMRepository : Repository<KHACHHANGNHOM>, IKHACHHANGNHOMRepository
    {
    	public string DefaultCode
        {
    		get { return null; }
        }
    
        public KHACHHANGNHOMRepository(IDataContextAsync context, IUnitOfWorkAsync unitOfWork) : base(context, unitOfWork)
        {
        }
    
        public KHACHHANGNHOMRepository(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
    	public bool Exist(string id)
        {
    		return QueryableList().Any(p => p.IDUnit == id);
        }
    
    	public bool Exist(Expression<Func<KHACHHANGNHOM, bool>> predicate)
    	{
    		return Queryable().Any(predicate);
    	}
    
    	public KHACHHANGNHOM CreateNew()
        {
    		
    		KHACHHANGNHOM _obj = Create();
    
    				//_obj.KHACHHANGs = null;//List
    		//_obj.KHACHHANGs = new List<KHACHHANG>();//List
    					_obj.TEN = string.Empty;//string
    					_obj.GHICHU = string.Empty;//string
    			        return _obj;
        }
    
    	public KHACHHANGNHOM CloneNew(KHACHHANGNHOM objKHACHHANGNHOM)
    	{
    		if(objKHACHHANGNHOM==null) return null;
    			 KHACHHANGNHOM objNew = Find(objKHACHHANGNHOM.MANHOM);
    			if(objNew !=null) return null;
    
    		 objNew =  CreateNew();
    		 				objNew.MANHOM =  objKHACHHANGNHOM.MANHOM;
    								objNew.TEN =  objKHACHHANGNHOM.TEN;
    								objNew.GHICHU =  objKHACHHANGNHOM.GHICHU;
    						  objNew.isAdd = true;
    		 return objNew;
    	}
    
    	public KHACHHANGNHOM CloneUpdate(KHACHHANGNHOM objKHACHHANGNHOM)
    	{
    		if(objKHACHHANGNHOM==null) return null;
    		 KHACHHANGNHOM objNew = Find(objKHACHHANGNHOM.MANHOM);
    		 if(objNew==null) return null;
    		 				objNew.MANHOM =  objKHACHHANGNHOM.MANHOM;
    								objNew.TEN =  objKHACHHANGNHOM.TEN;
    								objNew.GHICHU =  objKHACHHANGNHOM.GHICHU;
    						 objNew.isUpdate = true;
    		 return objNew;
    	}
    	public KHACHHANGNHOM Clone(KHACHHANGNHOM objKHACHHANGNHOM)
    	{
    		if(objKHACHHANGNHOM==null) return null;
    		 KHACHHANGNHOM objNew = Find(objKHACHHANGNHOM.MANHOM);
    		 if(objNew==null) 
    		 {
    		 objNew =  CreateNew();
    		 				objNew.MANHOM =  objKHACHHANGNHOM.MANHOM;
    								objNew.TEN =  objKHACHHANGNHOM.TEN;
    								objNew.GHICHU =  objKHACHHANGNHOM.GHICHU;
    						  objNew.isAdd = true;
    		 }
    		 else
    		 {
    		 				objNew.TEN =  objKHACHHANGNHOM.TEN;
    								objNew.GHICHU =  objKHACHHANGNHOM.GHICHU;
    						 objNew.isUpdate = true;
    		  objNew.isLoaded = true;
    		 }
    		 return objNew;
    	}
    
    	public List< KHACHHANGNHOM> Clone(IList<KHACHHANGNHOM> listKHACHHANGNHOMs)
    	{
    		List< KHACHHANGNHOM> lst = new List< KHACHHANGNHOM>();
    		if(listKHACHHANGNHOMs == null) return lst;
    		foreach(var obj in  listKHACHHANGNHOMs)
    		{
    			 lst.Add(Clone(obj));
    		}
    		return lst;
    	}
    
    	public KHACHHANGNHOM getObject(string id)
    	{
    		return QueryableList().FirstOrDefault(p => p.IDUnit == id);
    	}
    
    	public KHACHHANGNHOM getObject(Expression<Func<KHACHHANGNHOM, bool>> predicate)
    	{
    		return  Queryable().FirstOrDefault(predicate);
    	}
    
    	 public string GetMaxCode()
         {
    		return QueryableList().Max(s=>s.IDUnit).ToString();
         }
    
    	 public List<KHACHHANGNHOM> Search(string textSearch)
    	 {
    		List<KHACHHANGNHOM> listIDUnit = QueryableList().Where(p=>p.IDUnit == textSearch).ToList();
    		if (listIDUnit.Count != 0)
    		{
        		return listIDUnit;
    		}
    		else
    		{
        		listIDUnit = QueryableList().Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
        		return listIDUnit.Count == 0
        		? QueryableList().Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
        		: listIDUnit;
    		}
    	 }
    
    	public List<KHACHHANGNHOM> Search(Expression<Func<KHACHHANGNHOM, bool>> predicate)
    	{
    		return  Queryable().Where(predicate).ToList();
    	}
    
    	public List<KHACHHANGNHOM> Search(Expression<Func<KHACHHANGNHOM, bool>> predicate,string textSearch)
    	{
    			List<KHACHHANGNHOM> listIDUnit = Search(predicate).Where(p => p.IDUnit == textSearch).ToList();
                if (listIDUnit.Count != 0)
                {
                    return listIDUnit;
                }
                else
                {
                    listIDUnit = Search(predicate).Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
                    return listIDUnit.Count == 0
                    ? Search(predicate).Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
                    : listIDUnit;
                }
    	}
    }
}
