//------------------------------------------------------------------------------
// <auto-generated>
// Repository Generated
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.DataContext;
using Repository.Pattern.Ef6;
using Repository.Pattern.Repositories;
using Repository.Pattern.UnitOfWork;
using Util.Pattern;
using WH.Entity;
using System;

namespace WH.Service.Repository
{
    public partial interface IMATHANGKHUYENMAIRepository : IRepositoryAsync<MATHANGKHUYENMAI>
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<MATHANGKHUYENMAI, bool>> predicate);
    	MATHANGKHUYENMAI getObject(string id);
    	MATHANGKHUYENMAI getObject(Expression<Func<MATHANGKHUYENMAI, bool>> predicate);
    	
    
    	MATHANGKHUYENMAI CreateNew();
    	MATHANGKHUYENMAI CloneNew(MATHANGKHUYENMAI objMATHANGKHUYENMAI);
    	MATHANGKHUYENMAI CloneUpdate(MATHANGKHUYENMAI objMATHANGKHUYENMAI);
    	MATHANGKHUYENMAI Clone(MATHANGKHUYENMAI objMATHANGKHUYENMAI);
    
    	List< MATHANGKHUYENMAI> Clone(IList<MATHANGKHUYENMAI> listMATHANGKHUYENMAIs);
    	string GetMaxCode();
    	List<MATHANGKHUYENMAI> Search(string textSearch);
    	List<MATHANGKHUYENMAI> Search(Expression<Func<MATHANGKHUYENMAI, bool>> predicate);
    	List<MATHANGKHUYENMAI> Search(Expression<Func<MATHANGKHUYENMAI, bool>> predicate,string textSearch);
    }
    
    public partial class MATHANGKHUYENMAIRepository : Repository<MATHANGKHUYENMAI>, IMATHANGKHUYENMAIRepository
    {
    	public string DefaultCode
        {
    		get { return null; }
        }
    
        public MATHANGKHUYENMAIRepository(IDataContextAsync context, IUnitOfWorkAsync unitOfWork) : base(context, unitOfWork)
        {
        }
    
        public MATHANGKHUYENMAIRepository(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
    	public bool Exist(string id)
        {
    		return QueryableList().Any(p => p.IDUnit == id);
        }
    
    	public bool Exist(Expression<Func<MATHANGKHUYENMAI, bool>> predicate)
    	{
    		return Queryable().Any(predicate);
    	}
    
    	public MATHANGKHUYENMAI CreateNew()
        {
    		
    		MATHANGKHUYENMAI _obj = Create();
    
    				//_obj.MATHANG = null;//object
    		_obj.MAMATHANG = 0;//int
    									//_obj.MATHANG = null;//object
    		_obj.MAMATHANGKHUYENMAI = 0;//int
    									_obj.ISUSE = null;//Nullable<bool>
    							        return _obj;
        }
    
    	public MATHANGKHUYENMAI CloneNew(MATHANGKHUYENMAI objMATHANGKHUYENMAI)
    	{
    		if(objMATHANGKHUYENMAI==null) return null;
    			 MATHANGKHUYENMAI objNew = Find(objMATHANGKHUYENMAI.MAMATHANG,objMATHANGKHUYENMAI.MAMATHANGKHUYENMAI);
    			if(objNew !=null) return null;
    
    		 objNew =  CreateNew();
    		 				objNew.MAMATHANG =  objMATHANGKHUYENMAI.MAMATHANG;
    								objNew.MAMATHANGKHUYENMAI =  objMATHANGKHUYENMAI.MAMATHANGKHUYENMAI;
    								objNew.SOLUONGMATHANGQUYDOI =  objMATHANGKHUYENMAI.SOLUONGMATHANGQUYDOI;
    								objNew.SOLUONGSI =  objMATHANGKHUYENMAI.SOLUONGSI;
    								objNew.SOLUONGLE =  objMATHANGKHUYENMAI.SOLUONGLE;
    								objNew.TIENKHUYENMAI =  objMATHANGKHUYENMAI.TIENKHUYENMAI;
    								objNew.TONGTIENKHUYENMAI =  objMATHANGKHUYENMAI.TONGTIENKHUYENMAI;
    								objNew.ISUSE =  objMATHANGKHUYENMAI.ISUSE;
    						  objNew.isAdd = true;
    		 return objNew;
    	}
    
    	public MATHANGKHUYENMAI CloneUpdate(MATHANGKHUYENMAI objMATHANGKHUYENMAI)
    	{
    		if(objMATHANGKHUYENMAI==null) return null;
    		 MATHANGKHUYENMAI objNew = Find(objMATHANGKHUYENMAI.MAMATHANG,objMATHANGKHUYENMAI.MAMATHANGKHUYENMAI);
    		 if(objNew==null) return null;
    		 				objNew.MAMATHANG =  objMATHANGKHUYENMAI.MAMATHANG;
    								objNew.MAMATHANGKHUYENMAI =  objMATHANGKHUYENMAI.MAMATHANGKHUYENMAI;
    								objNew.SOLUONGMATHANGQUYDOI =  objMATHANGKHUYENMAI.SOLUONGMATHANGQUYDOI;
    								objNew.SOLUONGSI =  objMATHANGKHUYENMAI.SOLUONGSI;
    								objNew.SOLUONGLE =  objMATHANGKHUYENMAI.SOLUONGLE;
    								objNew.TIENKHUYENMAI =  objMATHANGKHUYENMAI.TIENKHUYENMAI;
    								objNew.TONGTIENKHUYENMAI =  objMATHANGKHUYENMAI.TONGTIENKHUYENMAI;
    								objNew.ISUSE =  objMATHANGKHUYENMAI.ISUSE;
    						 objNew.isUpdate = true;
    		 return objNew;
    	}
    	public MATHANGKHUYENMAI Clone(MATHANGKHUYENMAI objMATHANGKHUYENMAI)
    	{
    		if(objMATHANGKHUYENMAI==null) return null;
    		 MATHANGKHUYENMAI objNew = Find(objMATHANGKHUYENMAI.MAMATHANG,objMATHANGKHUYENMAI.MAMATHANGKHUYENMAI);
    		 if(objNew==null) 
    		 {
    		 objNew =  CreateNew();
    		 				objNew.MAMATHANG =  objMATHANGKHUYENMAI.MAMATHANG;
    								objNew.MAMATHANGKHUYENMAI =  objMATHANGKHUYENMAI.MAMATHANGKHUYENMAI;
    								objNew.SOLUONGMATHANGQUYDOI =  objMATHANGKHUYENMAI.SOLUONGMATHANGQUYDOI;
    								objNew.SOLUONGSI =  objMATHANGKHUYENMAI.SOLUONGSI;
    								objNew.SOLUONGLE =  objMATHANGKHUYENMAI.SOLUONGLE;
    								objNew.TIENKHUYENMAI =  objMATHANGKHUYENMAI.TIENKHUYENMAI;
    								objNew.TONGTIENKHUYENMAI =  objMATHANGKHUYENMAI.TONGTIENKHUYENMAI;
    								objNew.ISUSE =  objMATHANGKHUYENMAI.ISUSE;
    						  objNew.isAdd = true;
    		 }
    		 else
    		 {
    		 				objNew.SOLUONGMATHANGQUYDOI =  objMATHANGKHUYENMAI.SOLUONGMATHANGQUYDOI;
    								objNew.SOLUONGSI =  objMATHANGKHUYENMAI.SOLUONGSI;
    								objNew.SOLUONGLE =  objMATHANGKHUYENMAI.SOLUONGLE;
    								objNew.TIENKHUYENMAI =  objMATHANGKHUYENMAI.TIENKHUYENMAI;
    								objNew.TONGTIENKHUYENMAI =  objMATHANGKHUYENMAI.TONGTIENKHUYENMAI;
    								objNew.ISUSE =  objMATHANGKHUYENMAI.ISUSE;
    						 objNew.isUpdate = true;
    		  objNew.isLoaded = true;
    		 }
    		 return objNew;
    	}
    
    	public List< MATHANGKHUYENMAI> Clone(IList<MATHANGKHUYENMAI> listMATHANGKHUYENMAIs)
    	{
    		List< MATHANGKHUYENMAI> lst = new List< MATHANGKHUYENMAI>();
    		if(listMATHANGKHUYENMAIs == null) return lst;
    		foreach(var obj in  listMATHANGKHUYENMAIs)
    		{
    			 lst.Add(Clone(obj));
    		}
    		return lst;
    	}
    
    	public MATHANGKHUYENMAI getObject(string id)
    	{
    		return QueryableList().FirstOrDefault(p => p.IDUnit == id);
    	}
    
    	public MATHANGKHUYENMAI getObject(Expression<Func<MATHANGKHUYENMAI, bool>> predicate)
    	{
    		return  Queryable().FirstOrDefault(predicate);
    	}
    
    	 public string GetMaxCode()
         {
    		return QueryableList().Max(s=>s.IDUnit).ToString();
         }
    
    	 public List<MATHANGKHUYENMAI> Search(string textSearch)
    	 {
    		List<MATHANGKHUYENMAI> listIDUnit = QueryableList().Where(p=>p.IDUnit == textSearch).ToList();
    		if (listIDUnit.Count != 0)
    		{
        		return listIDUnit;
    		}
    		else
    		{
        		listIDUnit = QueryableList().Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
        		return listIDUnit.Count == 0
        		? QueryableList().Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
        		: listIDUnit;
    		}
    	 }
    
    	public List<MATHANGKHUYENMAI> Search(Expression<Func<MATHANGKHUYENMAI, bool>> predicate)
    	{
    		return  Queryable().Where(predicate).ToList();
    	}
    
    	public List<MATHANGKHUYENMAI> Search(Expression<Func<MATHANGKHUYENMAI, bool>> predicate,string textSearch)
    	{
    			List<MATHANGKHUYENMAI> listIDUnit = Search(predicate).Where(p => p.IDUnit == textSearch).ToList();
                if (listIDUnit.Count != 0)
                {
                    return listIDUnit;
                }
                else
                {
                    listIDUnit = Search(predicate).Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
                    return listIDUnit.Count == 0
                    ? Search(predicate).Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
                    : listIDUnit;
                }
    	}
    }
}
