//------------------------------------------------------------------------------
// <auto-generated>
// Repository Generated
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.DataContext;
using Repository.Pattern.Ef6;
using Repository.Pattern.Repositories;
using Repository.Pattern.UnitOfWork;
using Util.Pattern;
using WH.Entity;
using System;

namespace WH.Service.Repository
{
    public partial interface INHACUNGCAPRepository : IRepositoryAsync<NHACUNGCAP>
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<NHACUNGCAP, bool>> predicate);
    	NHACUNGCAP getObject(string id);
    	NHACUNGCAP getObject(Expression<Func<NHACUNGCAP, bool>> predicate);
    	
    
    	NHACUNGCAP CreateNew();
    	NHACUNGCAP CloneNew(NHACUNGCAP objNHACUNGCAP);
    	NHACUNGCAP CloneUpdate(NHACUNGCAP objNHACUNGCAP);
    	NHACUNGCAP Clone(NHACUNGCAP objNHACUNGCAP);
    
    	List< NHACUNGCAP> Clone(IList<NHACUNGCAP> listNHACUNGCAPs);
    	string GetMaxCode();
    	List<NHACUNGCAP> Search(string textSearch);
    	List<NHACUNGCAP> Search(Expression<Func<NHACUNGCAP, bool>> predicate);
    	List<NHACUNGCAP> Search(Expression<Func<NHACUNGCAP, bool>> predicate,string textSearch);
    }
    
    public partial class NHACUNGCAPRepository : Repository<NHACUNGCAP>, INHACUNGCAPRepository
    {
    	public string DefaultCode
        {
    		get { return null; }
        }
    
        public NHACUNGCAPRepository(IDataContextAsync context, IUnitOfWorkAsync unitOfWork) : base(context, unitOfWork)
        {
        }
    
        public NHACUNGCAPRepository(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
    	public bool Exist(string id)
        {
    		return QueryableList().Any(p => p.IDUnit == id);
        }
    
    	public bool Exist(Expression<Func<NHACUNGCAP, bool>> predicate)
    	{
    		return Queryable().Any(predicate);
    	}
    
    	public NHACUNGCAP CreateNew()
        {
    		
    		NHACUNGCAP _obj = Create();
    
    				//_obj.HOADONNHAPKHOes = null;//List
    		//_obj.HOADONNHAPKHOes = new List<HOADONNHAPKHO>();//List
    					_obj.TENNHACUNGCAP = string.Empty;//string
    					_obj.DIACHI = string.Empty;//string
    					_obj.DIENTHOAI = string.Empty;//string
    					_obj.DIDONG = string.Empty;//string
    					_obj.NGUOIDAIDIEN = string.Empty;//string
    					_obj.EMAIL = string.Empty;//string
    					_obj.THEODOI = null;//Nullable<bool>
    									_obj.ISDELETE = null;//Nullable<bool>
    									_obj.GHICHU = string.Empty;//string
    			        return _obj;
        }
    
    	public NHACUNGCAP CloneNew(NHACUNGCAP objNHACUNGCAP)
    	{
    		if(objNHACUNGCAP==null) return null;
    			 NHACUNGCAP objNew = Find(objNHACUNGCAP.MANHACUNGCAP);
    			if(objNew !=null) return null;
    
    		 objNew =  CreateNew();
    		 				objNew.MANHACUNGCAP =  objNHACUNGCAP.MANHACUNGCAP;
    								objNew.TENNHACUNGCAP =  objNHACUNGCAP.TENNHACUNGCAP;
    								objNew.DIACHI =  objNHACUNGCAP.DIACHI;
    								objNew.DIENTHOAI =  objNHACUNGCAP.DIENTHOAI;
    								objNew.DIDONG =  objNHACUNGCAP.DIDONG;
    								objNew.NGUOIDAIDIEN =  objNHACUNGCAP.NGUOIDAIDIEN;
    								objNew.EMAIL =  objNHACUNGCAP.EMAIL;
    								objNew.THEODOI =  objNHACUNGCAP.THEODOI;
    								objNew.ISDELETE =  objNHACUNGCAP.ISDELETE;
    								objNew.GHICHU =  objNHACUNGCAP.GHICHU;
    						  objNew.isAdd = true;
    		 return objNew;
    	}
    
    	public NHACUNGCAP CloneUpdate(NHACUNGCAP objNHACUNGCAP)
    	{
    		if(objNHACUNGCAP==null) return null;
    		 NHACUNGCAP objNew = Find(objNHACUNGCAP.MANHACUNGCAP);
    		 if(objNew==null) return null;
    		 				objNew.MANHACUNGCAP =  objNHACUNGCAP.MANHACUNGCAP;
    								objNew.TENNHACUNGCAP =  objNHACUNGCAP.TENNHACUNGCAP;
    								objNew.DIACHI =  objNHACUNGCAP.DIACHI;
    								objNew.DIENTHOAI =  objNHACUNGCAP.DIENTHOAI;
    								objNew.DIDONG =  objNHACUNGCAP.DIDONG;
    								objNew.NGUOIDAIDIEN =  objNHACUNGCAP.NGUOIDAIDIEN;
    								objNew.EMAIL =  objNHACUNGCAP.EMAIL;
    								objNew.THEODOI =  objNHACUNGCAP.THEODOI;
    								objNew.ISDELETE =  objNHACUNGCAP.ISDELETE;
    								objNew.GHICHU =  objNHACUNGCAP.GHICHU;
    						 objNew.isUpdate = true;
    		 return objNew;
    	}
    	public NHACUNGCAP Clone(NHACUNGCAP objNHACUNGCAP)
    	{
    		if(objNHACUNGCAP==null) return null;
    		 NHACUNGCAP objNew = Find(objNHACUNGCAP.MANHACUNGCAP);
    		 if(objNew==null) 
    		 {
    		 objNew =  CreateNew();
    		 				objNew.MANHACUNGCAP =  objNHACUNGCAP.MANHACUNGCAP;
    								objNew.TENNHACUNGCAP =  objNHACUNGCAP.TENNHACUNGCAP;
    								objNew.DIACHI =  objNHACUNGCAP.DIACHI;
    								objNew.DIENTHOAI =  objNHACUNGCAP.DIENTHOAI;
    								objNew.DIDONG =  objNHACUNGCAP.DIDONG;
    								objNew.NGUOIDAIDIEN =  objNHACUNGCAP.NGUOIDAIDIEN;
    								objNew.EMAIL =  objNHACUNGCAP.EMAIL;
    								objNew.THEODOI =  objNHACUNGCAP.THEODOI;
    								objNew.ISDELETE =  objNHACUNGCAP.ISDELETE;
    								objNew.GHICHU =  objNHACUNGCAP.GHICHU;
    						  objNew.isAdd = true;
    		 }
    		 else
    		 {
    		 				objNew.TENNHACUNGCAP =  objNHACUNGCAP.TENNHACUNGCAP;
    								objNew.DIACHI =  objNHACUNGCAP.DIACHI;
    								objNew.DIENTHOAI =  objNHACUNGCAP.DIENTHOAI;
    								objNew.DIDONG =  objNHACUNGCAP.DIDONG;
    								objNew.NGUOIDAIDIEN =  objNHACUNGCAP.NGUOIDAIDIEN;
    								objNew.EMAIL =  objNHACUNGCAP.EMAIL;
    								objNew.THEODOI =  objNHACUNGCAP.THEODOI;
    								objNew.ISDELETE =  objNHACUNGCAP.ISDELETE;
    								objNew.GHICHU =  objNHACUNGCAP.GHICHU;
    						 objNew.isUpdate = true;
    		  objNew.isLoaded = true;
    		 }
    		 return objNew;
    	}
    
    	public List< NHACUNGCAP> Clone(IList<NHACUNGCAP> listNHACUNGCAPs)
    	{
    		List< NHACUNGCAP> lst = new List< NHACUNGCAP>();
    		if(listNHACUNGCAPs == null) return lst;
    		foreach(var obj in  listNHACUNGCAPs)
    		{
    			 lst.Add(Clone(obj));
    		}
    		return lst;
    	}
    
    	public NHACUNGCAP getObject(string id)
    	{
    		return QueryableList().FirstOrDefault(p => p.IDUnit == id);
    	}
    
    	public NHACUNGCAP getObject(Expression<Func<NHACUNGCAP, bool>> predicate)
    	{
    		return  Queryable().FirstOrDefault(predicate);
    	}
    
    	 public string GetMaxCode()
         {
    		return QueryableList().Max(s=>s.IDUnit).ToString();
         }
    
    	 public List<NHACUNGCAP> Search(string textSearch)
    	 {
    		List<NHACUNGCAP> listIDUnit = QueryableList().Where(p=>p.IDUnit == textSearch).ToList();
    		if (listIDUnit.Count != 0)
    		{
        		return listIDUnit;
    		}
    		else
    		{
        		listIDUnit = QueryableList().Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
        		return listIDUnit.Count == 0
        		? QueryableList().Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
        		: listIDUnit;
    		}
    	 }
    
    	public List<NHACUNGCAP> Search(Expression<Func<NHACUNGCAP, bool>> predicate)
    	{
    		return  Queryable().Where(predicate).ToList();
    	}
    
    	public List<NHACUNGCAP> Search(Expression<Func<NHACUNGCAP, bool>> predicate,string textSearch)
    	{
    			List<NHACUNGCAP> listIDUnit = Search(predicate).Where(p => p.IDUnit == textSearch).ToList();
                if (listIDUnit.Count != 0)
                {
                    return listIDUnit;
                }
                else
                {
                    listIDUnit = Search(predicate).Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
                    return listIDUnit.Count == 0
                    ? Search(predicate).Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
                    : listIDUnit;
                }
    	}
    }
}
