//------------------------------------------------------------------------------
// <auto-generated>
// Repository Generated
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.DataContext;
using Repository.Pattern.Ef6;
using Repository.Pattern.Repositories;
using Repository.Pattern.UnitOfWork;
using Util.Pattern;
using WH.Entity;
using System;

namespace WH.Service.Repository
{
    public partial interface ISETDATETIMERepository : IRepositoryAsync<SETDATETIME>
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<SETDATETIME, bool>> predicate);
    	SETDATETIME getObject(string id);
    	SETDATETIME getObject(Expression<Func<SETDATETIME, bool>> predicate);
    	
    
    	SETDATETIME CreateNew();
    	SETDATETIME CloneNew(SETDATETIME objSETDATETIME);
    	SETDATETIME CloneUpdate(SETDATETIME objSETDATETIME);
    	SETDATETIME Clone(SETDATETIME objSETDATETIME);
    
    	List< SETDATETIME> Clone(IList<SETDATETIME> listSETDATETIMEs);
    	string GetMaxCode();
    	List<SETDATETIME> Search(string textSearch);
    	List<SETDATETIME> Search(Expression<Func<SETDATETIME, bool>> predicate);
    	List<SETDATETIME> Search(Expression<Func<SETDATETIME, bool>> predicate,string textSearch);
    }
    
    public partial class SETDATETIMERepository : Repository<SETDATETIME>, ISETDATETIMERepository
    {
    	public string DefaultCode
        {
    		get { return null; }
        }
    
        public SETDATETIMERepository(IDataContextAsync context, IUnitOfWorkAsync unitOfWork) : base(context, unitOfWork)
        {
        }
    
        public SETDATETIMERepository(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
    	public bool Exist(string id)
        {
    		return QueryableList().Any(p => p.IDUnit == id);
        }
    
    	public bool Exist(Expression<Func<SETDATETIME, bool>> predicate)
    	{
    		return Queryable().Any(predicate);
    	}
    
    	public SETDATETIME CreateNew()
        {
    		
    		SETDATETIME _obj = Create();
    
    					//Primary Key
    			_obj.ID = DateTime.Now.ToString("ddMMyyyyHHmmssfff"); //string
    						
    										_obj.maxdate = null;//Nullable<System.DateTime>
    										_obj.mindate = null;//Nullable<System.DateTime>
    									_obj.active = null;//Nullable<bool>
    							        return _obj;
        }
    
    	public SETDATETIME CloneNew(SETDATETIME objSETDATETIME)
    	{
    		if(objSETDATETIME==null) return null;
    			 SETDATETIME objNew = Find(objSETDATETIME.ID);
    			if(objNew !=null) return null;
    
    		 objNew =  CreateNew();
    		 				objNew.ID =  objSETDATETIME.ID;
    								objNew.maxdate =  objSETDATETIME.maxdate;
    								objNew.mindate =  objSETDATETIME.mindate;
    								objNew.active =  objSETDATETIME.active;
    								objNew.number =  objSETDATETIME.number;
    						  objNew.isAdd = true;
    		 return objNew;
    	}
    
    	public SETDATETIME CloneUpdate(SETDATETIME objSETDATETIME)
    	{
    		if(objSETDATETIME==null) return null;
    		 SETDATETIME objNew = Find(objSETDATETIME.ID);
    		 if(objNew==null) return null;
    		 				objNew.ID =  objSETDATETIME.ID;
    								objNew.maxdate =  objSETDATETIME.maxdate;
    								objNew.mindate =  objSETDATETIME.mindate;
    								objNew.active =  objSETDATETIME.active;
    								objNew.number =  objSETDATETIME.number;
    						 objNew.isUpdate = true;
    		 return objNew;
    	}
    	public SETDATETIME Clone(SETDATETIME objSETDATETIME)
    	{
    		if(objSETDATETIME==null) return null;
    		 SETDATETIME objNew = Find(objSETDATETIME.ID);
    		 if(objNew==null) 
    		 {
    		 objNew =  CreateNew();
    		 				objNew.ID =  objSETDATETIME.ID;
    								objNew.maxdate =  objSETDATETIME.maxdate;
    								objNew.mindate =  objSETDATETIME.mindate;
    								objNew.active =  objSETDATETIME.active;
    								objNew.number =  objSETDATETIME.number;
    						  objNew.isAdd = true;
    		 }
    		 else
    		 {
    		 				objNew.maxdate =  objSETDATETIME.maxdate;
    								objNew.mindate =  objSETDATETIME.mindate;
    								objNew.active =  objSETDATETIME.active;
    								objNew.number =  objSETDATETIME.number;
    						 objNew.isUpdate = true;
    		  objNew.isLoaded = true;
    		 }
    		 return objNew;
    	}
    
    	public List< SETDATETIME> Clone(IList<SETDATETIME> listSETDATETIMEs)
    	{
    		List< SETDATETIME> lst = new List< SETDATETIME>();
    		if(listSETDATETIMEs == null) return lst;
    		foreach(var obj in  listSETDATETIMEs)
    		{
    			 lst.Add(Clone(obj));
    		}
    		return lst;
    	}
    
    	public SETDATETIME getObject(string id)
    	{
    		return QueryableList().FirstOrDefault(p => p.IDUnit == id);
    	}
    
    	public SETDATETIME getObject(Expression<Func<SETDATETIME, bool>> predicate)
    	{
    		return  Queryable().FirstOrDefault(predicate);
    	}
    
    	 public string GetMaxCode()
         {
    		return QueryableList().Max(s=>s.IDUnit).ToString();
         }
    
    	 public List<SETDATETIME> Search(string textSearch)
    	 {
    		List<SETDATETIME> listIDUnit = QueryableList().Where(p=>p.IDUnit == textSearch).ToList();
    		if (listIDUnit.Count != 0)
    		{
        		return listIDUnit;
    		}
    		else
    		{
        		listIDUnit = QueryableList().Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
        		return listIDUnit.Count == 0
        		? QueryableList().Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
        		: listIDUnit;
    		}
    	 }
    
    	public List<SETDATETIME> Search(Expression<Func<SETDATETIME, bool>> predicate)
    	{
    		return  Queryable().Where(predicate).ToList();
    	}
    
    	public List<SETDATETIME> Search(Expression<Func<SETDATETIME, bool>> predicate,string textSearch)
    	{
    			List<SETDATETIME> listIDUnit = Search(predicate).Where(p => p.IDUnit == textSearch).ToList();
                if (listIDUnit.Count != 0)
                {
                    return listIDUnit;
                }
                else
                {
                    listIDUnit = Search(predicate).Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
                    return listIDUnit.Count == 0
                    ? Search(predicate).Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
                    : listIDUnit;
                }
    	}
    }
}
