//------------------------------------------------------------------------------
// <auto-generated>
// Repository Generated
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.DataContext;
using Repository.Pattern.Ef6;
using Repository.Pattern.Repositories;
using Repository.Pattern.UnitOfWork;
using Util.Pattern;
using WH.Entity;
using System;

namespace WH.Service.Repository
{
    public partial interface ITEMP_HOADONXUATKHOCHITIETRepository : IRepositoryAsync<TEMP_HOADONXUATKHOCHITIET>
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate);
    	TEMP_HOADONXUATKHOCHITIET getObject(string id);
    	TEMP_HOADONXUATKHOCHITIET getObject(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate);
    	
    
    	TEMP_HOADONXUATKHOCHITIET CreateNew();
    	TEMP_HOADONXUATKHOCHITIET CloneNew(TEMP_HOADONXUATKHOCHITIET objTEMP_HOADONXUATKHOCHITIET);
    	TEMP_HOADONXUATKHOCHITIET CloneUpdate(TEMP_HOADONXUATKHOCHITIET objTEMP_HOADONXUATKHOCHITIET);
    	TEMP_HOADONXUATKHOCHITIET Clone(TEMP_HOADONXUATKHOCHITIET objTEMP_HOADONXUATKHOCHITIET);
    
    	List< TEMP_HOADONXUATKHOCHITIET> Clone(IList<TEMP_HOADONXUATKHOCHITIET> listTEMP_HOADONXUATKHOCHITIETs);
    	string GetMaxCode();
    	List<TEMP_HOADONXUATKHOCHITIET> Search(string textSearch);
    	List<TEMP_HOADONXUATKHOCHITIET> Search(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate);
    	List<TEMP_HOADONXUATKHOCHITIET> Search(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate,string textSearch);
    }
    
    public partial class TEMP_HOADONXUATKHOCHITIETRepository : Repository<TEMP_HOADONXUATKHOCHITIET>, ITEMP_HOADONXUATKHOCHITIETRepository
    {
    	public string DefaultCode
        {
    		get { return null; }
        }
    
        public TEMP_HOADONXUATKHOCHITIETRepository(IDataContextAsync context, IUnitOfWorkAsync unitOfWork) : base(context, unitOfWork)
        {
        }
    
        public TEMP_HOADONXUATKHOCHITIETRepository(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
    	public bool Exist(string id)
        {
    		return QueryableList().Any(p => p.IDUnit == id);
        }
    
    	public bool Exist(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate)
    	{
    		return Queryable().Any(predicate);
    	}
    
    	public TEMP_HOADONXUATKHOCHITIET CreateNew()
        {
    		
    		TEMP_HOADONXUATKHOCHITIET _obj = Create();
    
    					//Primary Key
    			_obj.MACHITIETHOADON = DateTime.Now.ToString("ddMMyyyyHHmmssfff"); //string
    						
    									_obj.MAHOADON = string.Empty;//string
    					_obj.MAKHO = null;//Nullable<System.Guid>
    									_obj.ISCKPHANTRAM = null;//Nullable<bool>
    									_obj.GHICHU = string.Empty;//string
    					_obj.ISDELETE = null;//Nullable<bool>
    							        return _obj;
        }
    
    	public TEMP_HOADONXUATKHOCHITIET CloneNew(TEMP_HOADONXUATKHOCHITIET objTEMP_HOADONXUATKHOCHITIET)
    	{
    		if(objTEMP_HOADONXUATKHOCHITIET==null) return null;
    			 TEMP_HOADONXUATKHOCHITIET objNew = Find(objTEMP_HOADONXUATKHOCHITIET.MACHITIETHOADON);
    			if(objNew !=null) return null;
    
    		 objNew =  CreateNew();
    		 				objNew.MACHITIETHOADON =  objTEMP_HOADONXUATKHOCHITIET.MACHITIETHOADON;
    								objNew.MAHOADON =  objTEMP_HOADONXUATKHOCHITIET.MAHOADON;
    								objNew.MAKHO =  objTEMP_HOADONXUATKHOCHITIET.MAKHO;
    								objNew.MAMATHANG =  objTEMP_HOADONXUATKHOCHITIET.MAMATHANG;
    								objNew.SOLUONGSI =  objTEMP_HOADONXUATKHOCHITIET.SOLUONGSI;
    								objNew.SOLUONGLE =  objTEMP_HOADONXUATKHOCHITIET.SOLUONGLE;
    								objNew.DONGIASI =  objTEMP_HOADONXUATKHOCHITIET.DONGIASI;
    								objNew.CHIETKHAUTHEOPHANTRAM =  objTEMP_HOADONXUATKHOCHITIET.CHIETKHAUTHEOPHANTRAM;
    								objNew.CHIETKHAUTHEOTIEN =  objTEMP_HOADONXUATKHOCHITIET.CHIETKHAUTHEOTIEN;
    								objNew.ISCKPHANTRAM =  objTEMP_HOADONXUATKHOCHITIET.ISCKPHANTRAM;
    								objNew.THANHTIENTRUOCCHIETKHAU_CT =  objTEMP_HOADONXUATKHOCHITIET.THANHTIENTRUOCCHIETKHAU_CT;
    								objNew.THANHTIENSAUCHIETKHAU_CT =  objTEMP_HOADONXUATKHOCHITIET.THANHTIENSAUCHIETKHAU_CT;
    								objNew.GHICHU =  objTEMP_HOADONXUATKHOCHITIET.GHICHU;
    								objNew.ISDELETE =  objTEMP_HOADONXUATKHOCHITIET.ISDELETE;
    						  objNew.isAdd = true;
    		 return objNew;
    	}
    
    	public TEMP_HOADONXUATKHOCHITIET CloneUpdate(TEMP_HOADONXUATKHOCHITIET objTEMP_HOADONXUATKHOCHITIET)
    	{
    		if(objTEMP_HOADONXUATKHOCHITIET==null) return null;
    		 TEMP_HOADONXUATKHOCHITIET objNew = Find(objTEMP_HOADONXUATKHOCHITIET.MACHITIETHOADON);
    		 if(objNew==null) return null;
    		 				objNew.MACHITIETHOADON =  objTEMP_HOADONXUATKHOCHITIET.MACHITIETHOADON;
    								objNew.MAHOADON =  objTEMP_HOADONXUATKHOCHITIET.MAHOADON;
    								objNew.MAKHO =  objTEMP_HOADONXUATKHOCHITIET.MAKHO;
    								objNew.MAMATHANG =  objTEMP_HOADONXUATKHOCHITIET.MAMATHANG;
    								objNew.SOLUONGSI =  objTEMP_HOADONXUATKHOCHITIET.SOLUONGSI;
    								objNew.SOLUONGLE =  objTEMP_HOADONXUATKHOCHITIET.SOLUONGLE;
    								objNew.DONGIASI =  objTEMP_HOADONXUATKHOCHITIET.DONGIASI;
    								objNew.CHIETKHAUTHEOPHANTRAM =  objTEMP_HOADONXUATKHOCHITIET.CHIETKHAUTHEOPHANTRAM;
    								objNew.CHIETKHAUTHEOTIEN =  objTEMP_HOADONXUATKHOCHITIET.CHIETKHAUTHEOTIEN;
    								objNew.ISCKPHANTRAM =  objTEMP_HOADONXUATKHOCHITIET.ISCKPHANTRAM;
    								objNew.THANHTIENTRUOCCHIETKHAU_CT =  objTEMP_HOADONXUATKHOCHITIET.THANHTIENTRUOCCHIETKHAU_CT;
    								objNew.THANHTIENSAUCHIETKHAU_CT =  objTEMP_HOADONXUATKHOCHITIET.THANHTIENSAUCHIETKHAU_CT;
    								objNew.GHICHU =  objTEMP_HOADONXUATKHOCHITIET.GHICHU;
    								objNew.ISDELETE =  objTEMP_HOADONXUATKHOCHITIET.ISDELETE;
    						 objNew.isUpdate = true;
    		 return objNew;
    	}
    	public TEMP_HOADONXUATKHOCHITIET Clone(TEMP_HOADONXUATKHOCHITIET objTEMP_HOADONXUATKHOCHITIET)
    	{
    		if(objTEMP_HOADONXUATKHOCHITIET==null) return null;
    		 TEMP_HOADONXUATKHOCHITIET objNew = Find(objTEMP_HOADONXUATKHOCHITIET.MACHITIETHOADON);
    		 if(objNew==null) 
    		 {
    		 objNew =  CreateNew();
    		 				objNew.MACHITIETHOADON =  objTEMP_HOADONXUATKHOCHITIET.MACHITIETHOADON;
    								objNew.MAHOADON =  objTEMP_HOADONXUATKHOCHITIET.MAHOADON;
    								objNew.MAKHO =  objTEMP_HOADONXUATKHOCHITIET.MAKHO;
    								objNew.MAMATHANG =  objTEMP_HOADONXUATKHOCHITIET.MAMATHANG;
    								objNew.SOLUONGSI =  objTEMP_HOADONXUATKHOCHITIET.SOLUONGSI;
    								objNew.SOLUONGLE =  objTEMP_HOADONXUATKHOCHITIET.SOLUONGLE;
    								objNew.DONGIASI =  objTEMP_HOADONXUATKHOCHITIET.DONGIASI;
    								objNew.CHIETKHAUTHEOPHANTRAM =  objTEMP_HOADONXUATKHOCHITIET.CHIETKHAUTHEOPHANTRAM;
    								objNew.CHIETKHAUTHEOTIEN =  objTEMP_HOADONXUATKHOCHITIET.CHIETKHAUTHEOTIEN;
    								objNew.ISCKPHANTRAM =  objTEMP_HOADONXUATKHOCHITIET.ISCKPHANTRAM;
    								objNew.THANHTIENTRUOCCHIETKHAU_CT =  objTEMP_HOADONXUATKHOCHITIET.THANHTIENTRUOCCHIETKHAU_CT;
    								objNew.THANHTIENSAUCHIETKHAU_CT =  objTEMP_HOADONXUATKHOCHITIET.THANHTIENSAUCHIETKHAU_CT;
    								objNew.GHICHU =  objTEMP_HOADONXUATKHOCHITIET.GHICHU;
    								objNew.ISDELETE =  objTEMP_HOADONXUATKHOCHITIET.ISDELETE;
    						  objNew.isAdd = true;
    		 }
    		 else
    		 {
    		 				objNew.MAHOADON =  objTEMP_HOADONXUATKHOCHITIET.MAHOADON;
    								objNew.MAKHO =  objTEMP_HOADONXUATKHOCHITIET.MAKHO;
    								objNew.MAMATHANG =  objTEMP_HOADONXUATKHOCHITIET.MAMATHANG;
    								objNew.SOLUONGSI =  objTEMP_HOADONXUATKHOCHITIET.SOLUONGSI;
    								objNew.SOLUONGLE =  objTEMP_HOADONXUATKHOCHITIET.SOLUONGLE;
    								objNew.DONGIASI =  objTEMP_HOADONXUATKHOCHITIET.DONGIASI;
    								objNew.CHIETKHAUTHEOPHANTRAM =  objTEMP_HOADONXUATKHOCHITIET.CHIETKHAUTHEOPHANTRAM;
    								objNew.CHIETKHAUTHEOTIEN =  objTEMP_HOADONXUATKHOCHITIET.CHIETKHAUTHEOTIEN;
    								objNew.ISCKPHANTRAM =  objTEMP_HOADONXUATKHOCHITIET.ISCKPHANTRAM;
    								objNew.THANHTIENTRUOCCHIETKHAU_CT =  objTEMP_HOADONXUATKHOCHITIET.THANHTIENTRUOCCHIETKHAU_CT;
    								objNew.THANHTIENSAUCHIETKHAU_CT =  objTEMP_HOADONXUATKHOCHITIET.THANHTIENSAUCHIETKHAU_CT;
    								objNew.GHICHU =  objTEMP_HOADONXUATKHOCHITIET.GHICHU;
    								objNew.ISDELETE =  objTEMP_HOADONXUATKHOCHITIET.ISDELETE;
    						 objNew.isUpdate = true;
    		  objNew.isLoaded = true;
    		 }
    		 return objNew;
    	}
    
    	public List< TEMP_HOADONXUATKHOCHITIET> Clone(IList<TEMP_HOADONXUATKHOCHITIET> listTEMP_HOADONXUATKHOCHITIETs)
    	{
    		List< TEMP_HOADONXUATKHOCHITIET> lst = new List< TEMP_HOADONXUATKHOCHITIET>();
    		if(listTEMP_HOADONXUATKHOCHITIETs == null) return lst;
    		foreach(var obj in  listTEMP_HOADONXUATKHOCHITIETs)
    		{
    			 lst.Add(Clone(obj));
    		}
    		return lst;
    	}
    
    	public TEMP_HOADONXUATKHOCHITIET getObject(string id)
    	{
    		return QueryableList().FirstOrDefault(p => p.IDUnit == id);
    	}
    
    	public TEMP_HOADONXUATKHOCHITIET getObject(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate)
    	{
    		return  Queryable().FirstOrDefault(predicate);
    	}
    
    	 public string GetMaxCode()
         {
    		return QueryableList().Max(s=>s.IDUnit).ToString();
         }
    
    	 public List<TEMP_HOADONXUATKHOCHITIET> Search(string textSearch)
    	 {
    		List<TEMP_HOADONXUATKHOCHITIET> listIDUnit = QueryableList().Where(p=>p.IDUnit == textSearch).ToList();
    		if (listIDUnit.Count != 0)
    		{
        		return listIDUnit;
    		}
    		else
    		{
        		listIDUnit = QueryableList().Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
        		return listIDUnit.Count == 0
        		? QueryableList().Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
        		: listIDUnit;
    		}
    	 }
    
    	public List<TEMP_HOADONXUATKHOCHITIET> Search(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate)
    	{
    		return  Queryable().Where(predicate).ToList();
    	}
    
    	public List<TEMP_HOADONXUATKHOCHITIET> Search(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate,string textSearch)
    	{
    			List<TEMP_HOADONXUATKHOCHITIET> listIDUnit = Search(predicate).Where(p => p.IDUnit == textSearch).ToList();
                if (listIDUnit.Count != 0)
                {
                    return listIDUnit;
                }
                else
                {
                    listIDUnit = Search(predicate).Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
                    return listIDUnit.Count == 0
                    ? Search(predicate).Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
                    : listIDUnit;
                }
    	}
    }
}
