//------------------------------------------------------------------------------
// <auto-generated>
// Repository Generated
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.DataContext;
using Repository.Pattern.Ef6;
using Repository.Pattern.Repositories;
using Repository.Pattern.UnitOfWork;
using Util.Pattern;
using WH.Entity;
using System;

namespace WH.Service.Repository
{
    public partial interface ITEMP_HOADONHAPKHOCHITIETRepository : IRepositoryAsync<TEMP_HOADONHAPKHOCHITIET>
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<TEMP_HOADONHAPKHOCHITIET, bool>> predicate);
    	TEMP_HOADONHAPKHOCHITIET getObject(string id);
    	TEMP_HOADONHAPKHOCHITIET getObject(Expression<Func<TEMP_HOADONHAPKHOCHITIET, bool>> predicate);
    	
    
    	TEMP_HOADONHAPKHOCHITIET CreateNew();
    	TEMP_HOADONHAPKHOCHITIET CloneNew(TEMP_HOADONHAPKHOCHITIET objTEMP_HOADONHAPKHOCHITIET);
    	TEMP_HOADONHAPKHOCHITIET CloneUpdate(TEMP_HOADONHAPKHOCHITIET objTEMP_HOADONHAPKHOCHITIET);
    	TEMP_HOADONHAPKHOCHITIET Clone(TEMP_HOADONHAPKHOCHITIET objTEMP_HOADONHAPKHOCHITIET);
    
    	List< TEMP_HOADONHAPKHOCHITIET> Clone(IList<TEMP_HOADONHAPKHOCHITIET> listTEMP_HOADONHAPKHOCHITIETs);
    	string GetMaxCode();
    	List<TEMP_HOADONHAPKHOCHITIET> Search(string textSearch);
    	List<TEMP_HOADONHAPKHOCHITIET> Search(Expression<Func<TEMP_HOADONHAPKHOCHITIET, bool>> predicate);
    	List<TEMP_HOADONHAPKHOCHITIET> Search(Expression<Func<TEMP_HOADONHAPKHOCHITIET, bool>> predicate,string textSearch);
    }
    
    public partial class TEMP_HOADONHAPKHOCHITIETRepository : Repository<TEMP_HOADONHAPKHOCHITIET>, ITEMP_HOADONHAPKHOCHITIETRepository
    {
    	public string DefaultCode
        {
    		get { return null; }
        }
    
        public TEMP_HOADONHAPKHOCHITIETRepository(IDataContextAsync context, IUnitOfWorkAsync unitOfWork) : base(context, unitOfWork)
        {
        }
    
        public TEMP_HOADONHAPKHOCHITIETRepository(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
    	public bool Exist(string id)
        {
    		return QueryableList().Any(p => p.IDUnit == id);
        }
    
    	public bool Exist(Expression<Func<TEMP_HOADONHAPKHOCHITIET, bool>> predicate)
    	{
    		return Queryable().Any(predicate);
    	}
    
    	public TEMP_HOADONHAPKHOCHITIET CreateNew()
        {
    		
    		TEMP_HOADONHAPKHOCHITIET _obj = Create();
    
    					//Primary Key
    			_obj.MACHITIETHOADON = DateTime.Now.ToString("ddMMyyyyHHmmssfff"); //string
    						
    									_obj.MAHOADON = string.Empty;//string
    					_obj.MAKHO = null;//Nullable<System.Guid>
    									_obj.GHICHU_CT = string.Empty;//string
    					_obj.ISDELETE = null;//Nullable<bool>
    							        return _obj;
        }
    
    	public TEMP_HOADONHAPKHOCHITIET CloneNew(TEMP_HOADONHAPKHOCHITIET objTEMP_HOADONHAPKHOCHITIET)
    	{
    		if(objTEMP_HOADONHAPKHOCHITIET==null) return null;
    			 TEMP_HOADONHAPKHOCHITIET objNew = Find(objTEMP_HOADONHAPKHOCHITIET.MACHITIETHOADON);
    			if(objNew !=null) return null;
    
    		 objNew =  CreateNew();
    		 				objNew.MACHITIETHOADON =  objTEMP_HOADONHAPKHOCHITIET.MACHITIETHOADON;
    								objNew.MAHOADON =  objTEMP_HOADONHAPKHOCHITIET.MAHOADON;
    								objNew.MAKHO =  objTEMP_HOADONHAPKHOCHITIET.MAKHO;
    								objNew.MAMATHANG =  objTEMP_HOADONHAPKHOCHITIET.MAMATHANG;
    								objNew.SOLUONGSI =  objTEMP_HOADONHAPKHOCHITIET.SOLUONGSI;
    								objNew.SOLUONGLE =  objTEMP_HOADONHAPKHOCHITIET.SOLUONGLE;
    								objNew.DONGIA =  objTEMP_HOADONHAPKHOCHITIET.DONGIA;
    								objNew.TIENVAT =  objTEMP_HOADONHAPKHOCHITIET.TIENVAT;
    								objNew.THANHTIENTRUOCCHIETKHAU_CT =  objTEMP_HOADONHAPKHOCHITIET.THANHTIENTRUOCCHIETKHAU_CT;
    								objNew.THANHTIENSAUCHIETKHAU_CT =  objTEMP_HOADONHAPKHOCHITIET.THANHTIENSAUCHIETKHAU_CT;
    								objNew.GHICHU_CT =  objTEMP_HOADONHAPKHOCHITIET.GHICHU_CT;
    								objNew.ISDELETE =  objTEMP_HOADONHAPKHOCHITIET.ISDELETE;
    						  objNew.isAdd = true;
    		 return objNew;
    	}
    
    	public TEMP_HOADONHAPKHOCHITIET CloneUpdate(TEMP_HOADONHAPKHOCHITIET objTEMP_HOADONHAPKHOCHITIET)
    	{
    		if(objTEMP_HOADONHAPKHOCHITIET==null) return null;
    		 TEMP_HOADONHAPKHOCHITIET objNew = Find(objTEMP_HOADONHAPKHOCHITIET.MACHITIETHOADON);
    		 if(objNew==null) return null;
    		 				objNew.MACHITIETHOADON =  objTEMP_HOADONHAPKHOCHITIET.MACHITIETHOADON;
    								objNew.MAHOADON =  objTEMP_HOADONHAPKHOCHITIET.MAHOADON;
    								objNew.MAKHO =  objTEMP_HOADONHAPKHOCHITIET.MAKHO;
    								objNew.MAMATHANG =  objTEMP_HOADONHAPKHOCHITIET.MAMATHANG;
    								objNew.SOLUONGSI =  objTEMP_HOADONHAPKHOCHITIET.SOLUONGSI;
    								objNew.SOLUONGLE =  objTEMP_HOADONHAPKHOCHITIET.SOLUONGLE;
    								objNew.DONGIA =  objTEMP_HOADONHAPKHOCHITIET.DONGIA;
    								objNew.TIENVAT =  objTEMP_HOADONHAPKHOCHITIET.TIENVAT;
    								objNew.THANHTIENTRUOCCHIETKHAU_CT =  objTEMP_HOADONHAPKHOCHITIET.THANHTIENTRUOCCHIETKHAU_CT;
    								objNew.THANHTIENSAUCHIETKHAU_CT =  objTEMP_HOADONHAPKHOCHITIET.THANHTIENSAUCHIETKHAU_CT;
    								objNew.GHICHU_CT =  objTEMP_HOADONHAPKHOCHITIET.GHICHU_CT;
    								objNew.ISDELETE =  objTEMP_HOADONHAPKHOCHITIET.ISDELETE;
    						 objNew.isUpdate = true;
    		 return objNew;
    	}
    	public TEMP_HOADONHAPKHOCHITIET Clone(TEMP_HOADONHAPKHOCHITIET objTEMP_HOADONHAPKHOCHITIET)
    	{
    		if(objTEMP_HOADONHAPKHOCHITIET==null) return null;
    		 TEMP_HOADONHAPKHOCHITIET objNew = Find(objTEMP_HOADONHAPKHOCHITIET.MACHITIETHOADON);
    		 if(objNew==null) 
    		 {
    		 objNew =  CreateNew();
    		 				objNew.MACHITIETHOADON =  objTEMP_HOADONHAPKHOCHITIET.MACHITIETHOADON;
    								objNew.MAHOADON =  objTEMP_HOADONHAPKHOCHITIET.MAHOADON;
    								objNew.MAKHO =  objTEMP_HOADONHAPKHOCHITIET.MAKHO;
    								objNew.MAMATHANG =  objTEMP_HOADONHAPKHOCHITIET.MAMATHANG;
    								objNew.SOLUONGSI =  objTEMP_HOADONHAPKHOCHITIET.SOLUONGSI;
    								objNew.SOLUONGLE =  objTEMP_HOADONHAPKHOCHITIET.SOLUONGLE;
    								objNew.DONGIA =  objTEMP_HOADONHAPKHOCHITIET.DONGIA;
    								objNew.TIENVAT =  objTEMP_HOADONHAPKHOCHITIET.TIENVAT;
    								objNew.THANHTIENTRUOCCHIETKHAU_CT =  objTEMP_HOADONHAPKHOCHITIET.THANHTIENTRUOCCHIETKHAU_CT;
    								objNew.THANHTIENSAUCHIETKHAU_CT =  objTEMP_HOADONHAPKHOCHITIET.THANHTIENSAUCHIETKHAU_CT;
    								objNew.GHICHU_CT =  objTEMP_HOADONHAPKHOCHITIET.GHICHU_CT;
    								objNew.ISDELETE =  objTEMP_HOADONHAPKHOCHITIET.ISDELETE;
    						  objNew.isAdd = true;
    		 }
    		 else
    		 {
    		 				objNew.MAHOADON =  objTEMP_HOADONHAPKHOCHITIET.MAHOADON;
    								objNew.MAKHO =  objTEMP_HOADONHAPKHOCHITIET.MAKHO;
    								objNew.MAMATHANG =  objTEMP_HOADONHAPKHOCHITIET.MAMATHANG;
    								objNew.SOLUONGSI =  objTEMP_HOADONHAPKHOCHITIET.SOLUONGSI;
    								objNew.SOLUONGLE =  objTEMP_HOADONHAPKHOCHITIET.SOLUONGLE;
    								objNew.DONGIA =  objTEMP_HOADONHAPKHOCHITIET.DONGIA;
    								objNew.TIENVAT =  objTEMP_HOADONHAPKHOCHITIET.TIENVAT;
    								objNew.THANHTIENTRUOCCHIETKHAU_CT =  objTEMP_HOADONHAPKHOCHITIET.THANHTIENTRUOCCHIETKHAU_CT;
    								objNew.THANHTIENSAUCHIETKHAU_CT =  objTEMP_HOADONHAPKHOCHITIET.THANHTIENSAUCHIETKHAU_CT;
    								objNew.GHICHU_CT =  objTEMP_HOADONHAPKHOCHITIET.GHICHU_CT;
    								objNew.ISDELETE =  objTEMP_HOADONHAPKHOCHITIET.ISDELETE;
    						 objNew.isUpdate = true;
    		  objNew.isLoaded = true;
    		 }
    		 return objNew;
    	}
    
    	public List< TEMP_HOADONHAPKHOCHITIET> Clone(IList<TEMP_HOADONHAPKHOCHITIET> listTEMP_HOADONHAPKHOCHITIETs)
    	{
    		List< TEMP_HOADONHAPKHOCHITIET> lst = new List< TEMP_HOADONHAPKHOCHITIET>();
    		if(listTEMP_HOADONHAPKHOCHITIETs == null) return lst;
    		foreach(var obj in  listTEMP_HOADONHAPKHOCHITIETs)
    		{
    			 lst.Add(Clone(obj));
    		}
    		return lst;
    	}
    
    	public TEMP_HOADONHAPKHOCHITIET getObject(string id)
    	{
    		return QueryableList().FirstOrDefault(p => p.IDUnit == id);
    	}
    
    	public TEMP_HOADONHAPKHOCHITIET getObject(Expression<Func<TEMP_HOADONHAPKHOCHITIET, bool>> predicate)
    	{
    		return  Queryable().FirstOrDefault(predicate);
    	}
    
    	 public string GetMaxCode()
         {
    		return QueryableList().Max(s=>s.IDUnit).ToString();
         }
    
    	 public List<TEMP_HOADONHAPKHOCHITIET> Search(string textSearch)
    	 {
    		List<TEMP_HOADONHAPKHOCHITIET> listIDUnit = QueryableList().Where(p=>p.IDUnit == textSearch).ToList();
    		if (listIDUnit.Count != 0)
    		{
        		return listIDUnit;
    		}
    		else
    		{
        		listIDUnit = QueryableList().Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
        		return listIDUnit.Count == 0
        		? QueryableList().Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
        		: listIDUnit;
    		}
    	 }
    
    	public List<TEMP_HOADONHAPKHOCHITIET> Search(Expression<Func<TEMP_HOADONHAPKHOCHITIET, bool>> predicate)
    	{
    		return  Queryable().Where(predicate).ToList();
    	}
    
    	public List<TEMP_HOADONHAPKHOCHITIET> Search(Expression<Func<TEMP_HOADONHAPKHOCHITIET, bool>> predicate,string textSearch)
    	{
    			List<TEMP_HOADONHAPKHOCHITIET> listIDUnit = Search(predicate).Where(p => p.IDUnit == textSearch).ToList();
                if (listIDUnit.Count != 0)
                {
                    return listIDUnit;
                }
                else
                {
                    listIDUnit = Search(predicate).Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
                    return listIDUnit.Count == 0
                    ? Search(predicate).Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
                    : listIDUnit;
                }
    	}
    }
}
