//------------------------------------------------------------------------------
// <auto-generated>
// Repository Generated
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.DataContext;
using Repository.Pattern.Ef6;
using Repository.Pattern.Repositories;
using Repository.Pattern.UnitOfWork;
using Util.Pattern;
using WH.Entity;
using System;

namespace WH.Service.Repository
{
    public partial interface ITHONGTINTHERepository : IRepositoryAsync<THONGTINTHE>
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<THONGTINTHE, bool>> predicate);
    	THONGTINTHE getObject(string id);
    	THONGTINTHE getObject(Expression<Func<THONGTINTHE, bool>> predicate);
    	
    
    	THONGTINTHE CreateNew();
    	THONGTINTHE CloneNew(THONGTINTHE objTHONGTINTHE);
    	THONGTINTHE CloneUpdate(THONGTINTHE objTHONGTINTHE);
    	THONGTINTHE Clone(THONGTINTHE objTHONGTINTHE);
    
    	List< THONGTINTHE> Clone(IList<THONGTINTHE> listTHONGTINTHEs);
    	string GetMaxCode();
    	List<THONGTINTHE> Search(string textSearch);
    	List<THONGTINTHE> Search(Expression<Func<THONGTINTHE, bool>> predicate);
    	List<THONGTINTHE> Search(Expression<Func<THONGTINTHE, bool>> predicate,string textSearch);
    }
    
    public partial class THONGTINTHERepository : Repository<THONGTINTHE>, ITHONGTINTHERepository
    {
    	public string DefaultCode
        {
    		get { return null; }
        }
    
        public THONGTINTHERepository(IDataContextAsync context, IUnitOfWorkAsync unitOfWork) : base(context, unitOfWork)
        {
        }
    
        public THONGTINTHERepository(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
    	public bool Exist(string id)
        {
    		return QueryableList().Any(p => p.IDUnit == id);
        }
    
    	public bool Exist(Expression<Func<THONGTINTHE, bool>> predicate)
    	{
    		return Queryable().Any(predicate);
    	}
    
    	public THONGTINTHE CreateNew()
        {
    		
    		THONGTINTHE _obj = Create();
    
    				//_obj.QUANLYTHETHEOKHACHHANGs = null;//List
    		//_obj.QUANLYTHETHEOKHACHHANGs = new List<QUANLYTHETHEOKHACHHANG>();//List
    						//Primary Key
    			_obj.MATHE = DateTime.Now.ToString("ddMMyyyyHHmmssfff"); //string
    						
    									_obj.TEN = string.Empty;//string
    					_obj.ISUSE = null;//Nullable<bool>
    									_obj.ISDELETE = null;//Nullable<bool>
    							        return _obj;
        }
    
    	public THONGTINTHE CloneNew(THONGTINTHE objTHONGTINTHE)
    	{
    		if(objTHONGTINTHE==null) return null;
    			 THONGTINTHE objNew = Find(objTHONGTINTHE.MATHE);
    			if(objNew !=null) return null;
    
    		 objNew =  CreateNew();
    		 				objNew.MATHE =  objTHONGTINTHE.MATHE;
    								objNew.TEN =  objTHONGTINTHE.TEN;
    								objNew.TUMUC =  objTHONGTINTHE.TUMUC;
    								objNew.DENMUC =  objTHONGTINTHE.DENMUC;
    								objNew.TILEGIAMGIA =  objTHONGTINTHE.TILEGIAMGIA;
    								objNew.ISUSE =  objTHONGTINTHE.ISUSE;
    								objNew.ISDELETE =  objTHONGTINTHE.ISDELETE;
    						  objNew.isAdd = true;
    		 return objNew;
    	}
    
    	public THONGTINTHE CloneUpdate(THONGTINTHE objTHONGTINTHE)
    	{
    		if(objTHONGTINTHE==null) return null;
    		 THONGTINTHE objNew = Find(objTHONGTINTHE.MATHE);
    		 if(objNew==null) return null;
    		 				objNew.MATHE =  objTHONGTINTHE.MATHE;
    								objNew.TEN =  objTHONGTINTHE.TEN;
    								objNew.TUMUC =  objTHONGTINTHE.TUMUC;
    								objNew.DENMUC =  objTHONGTINTHE.DENMUC;
    								objNew.TILEGIAMGIA =  objTHONGTINTHE.TILEGIAMGIA;
    								objNew.ISUSE =  objTHONGTINTHE.ISUSE;
    								objNew.ISDELETE =  objTHONGTINTHE.ISDELETE;
    						 objNew.isUpdate = true;
    		 return objNew;
    	}
    	public THONGTINTHE Clone(THONGTINTHE objTHONGTINTHE)
    	{
    		if(objTHONGTINTHE==null) return null;
    		 THONGTINTHE objNew = Find(objTHONGTINTHE.MATHE);
    		 if(objNew==null) 
    		 {
    		 objNew =  CreateNew();
    		 				objNew.MATHE =  objTHONGTINTHE.MATHE;
    								objNew.TEN =  objTHONGTINTHE.TEN;
    								objNew.TUMUC =  objTHONGTINTHE.TUMUC;
    								objNew.DENMUC =  objTHONGTINTHE.DENMUC;
    								objNew.TILEGIAMGIA =  objTHONGTINTHE.TILEGIAMGIA;
    								objNew.ISUSE =  objTHONGTINTHE.ISUSE;
    								objNew.ISDELETE =  objTHONGTINTHE.ISDELETE;
    						  objNew.isAdd = true;
    		 }
    		 else
    		 {
    		 				objNew.TEN =  objTHONGTINTHE.TEN;
    								objNew.TUMUC =  objTHONGTINTHE.TUMUC;
    								objNew.DENMUC =  objTHONGTINTHE.DENMUC;
    								objNew.TILEGIAMGIA =  objTHONGTINTHE.TILEGIAMGIA;
    								objNew.ISUSE =  objTHONGTINTHE.ISUSE;
    								objNew.ISDELETE =  objTHONGTINTHE.ISDELETE;
    						 objNew.isUpdate = true;
    		  objNew.isLoaded = true;
    		 }
    		 return objNew;
    	}
    
    	public List< THONGTINTHE> Clone(IList<THONGTINTHE> listTHONGTINTHEs)
    	{
    		List< THONGTINTHE> lst = new List< THONGTINTHE>();
    		if(listTHONGTINTHEs == null) return lst;
    		foreach(var obj in  listTHONGTINTHEs)
    		{
    			 lst.Add(Clone(obj));
    		}
    		return lst;
    	}
    
    	public THONGTINTHE getObject(string id)
    	{
    		return QueryableList().FirstOrDefault(p => p.IDUnit == id);
    	}
    
    	public THONGTINTHE getObject(Expression<Func<THONGTINTHE, bool>> predicate)
    	{
    		return  Queryable().FirstOrDefault(predicate);
    	}
    
    	 public string GetMaxCode()
         {
    		return QueryableList().Max(s=>s.IDUnit).ToString();
         }
    
    	 public List<THONGTINTHE> Search(string textSearch)
    	 {
    		List<THONGTINTHE> listIDUnit = QueryableList().Where(p=>p.IDUnit == textSearch).ToList();
    		if (listIDUnit.Count != 0)
    		{
        		return listIDUnit;
    		}
    		else
    		{
        		listIDUnit = QueryableList().Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
        		return listIDUnit.Count == 0
        		? QueryableList().Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
        		: listIDUnit;
    		}
    	 }
    
    	public List<THONGTINTHE> Search(Expression<Func<THONGTINTHE, bool>> predicate)
    	{
    		return  Queryable().Where(predicate).ToList();
    	}
    
    	public List<THONGTINTHE> Search(Expression<Func<THONGTINTHE, bool>> predicate,string textSearch)
    	{
    			List<THONGTINTHE> listIDUnit = Search(predicate).Where(p => p.IDUnit == textSearch).ToList();
                if (listIDUnit.Count != 0)
                {
                    return listIDUnit;
                }
                else
                {
                    listIDUnit = Search(predicate).Where(p => p.TextSearchCoDau.Contains(textSearch.Replace(" ", "").ToLower())).ToList();
                    return listIDUnit.Count == 0
                    ? Search(predicate).Where(p => p.TIMKIEM.Contains(textSearch.ToUnsign().Replace(" ", "").ToLower())).ToList()
                    : listIDUnit;
                }
    	}
    }
}
