use QUANLYKHO_V3
GO
DROP Table [dbo].[HOADONNHAPXUATCHITIET]
GO
DROP Table [dbo].[HOADONNHAPXUAT]
GO
CREATE TABLE [dbo].[HOADONNHAPXUAT](
	[MAHOADON] [varchar](100) primary key NOT NULL,
	[THANHTIENCHUACK_HD] [decimal](18, 0) NULL,
	[TIENCHIETKHAU_HD] [decimal](18, 0) NULL,
	[TIENKHUYENMAI_HD] [decimal](18, 0) NULL,
	[SOTIENTHANHTOAN_HD] [decimal](18, 0) NULL,
	[SOTIENKHACHDUA_HD] [decimal](18, 0) NULL,
	[LOAIHOADON] [int] NULL,
	[HANTHANHTOAN] [datetime] NULL,
	[GHICHU_HD] [nvarchar](500) NULL,
	[DATHANHTOAN] [bit] NULL,
	[NGUOITAO] [nvarchar](100) NULL,
	[NGAYTAOHOADON] [datetime] NULL,
	[ISDELETE] [bit] NULL,
	[MAKHACHHANG] [uniqueidentifier] NULL,
	[MACA] [int] NULL,
	FOREIGN KEY([MAKHACHHANG]) REFERENCES [KHACHHANG] ([MAKHACHHANG]))
	GO
	CREATE TABLE [dbo].[HOADONNHAPXUATCHITIET](
	[MACHITIETHOADON] [varchar](100) primary key  NOT NULL,
	[MAHOADON] [varchar](100) NULL,
	[MAKHO] [uniqueidentifier] NULL,
	[MAMATHANG] [int] NULL,
	[SOLUONGSI] [decimal](18, 0) NULL,
	[SOLUONGLE] [decimal](18, 0) NULL,
	[DONGIASI] [decimal](18, 0) NULL,
	[CHIETKHAUTHEOPHANTRAM] [float] NULL,
	[CHIETKHAUTHEOTIEN] [decimal](18, 0) NULL,
	[ISCKPHANTRAM] [bit] NULL,
	[THANHTIENTRUOCCHIETKHAU_CT] [decimal](18, 0) NULL,
	[THANHTIENSAUCHIETKHAU_CT] [decimal](18, 0) NULL,
	[GHICHU] [nvarchar](500) NULL,
	[ISDELETE] [bit] NULL,
	FOREIGN KEY([MAHOADON]) REFERENCES [HOADONNHAPXUAT] ([MAHOADON]),
	FOREIGN KEY([MAMATHANG]) REFERENCES [MATHANG] ([MAMATHANG]),
	FOREIGN KEY([MAKHO]) REFERENCES [KHO] ([MAKHO]))