use QUANLYKHO_V3
Go
Update HOADONNHAPXUATCHITIET 
set THANHTIENTRUOCCHIETKHAU_CT = (DONGIASI * SOLUONGLE),
 CHIETKHAUTHEOTIEN =  (DONGIASI * SOLUONGLE * CHIETKHAUTHEOPHANTRAM),
 THANHTIENSAUCHIETKHAU_CT = (DONGIASI * SOLUONGLE) - (DONGIASI * SOLUONGLE * CHIETKHAUTHEOPHANTRAM)
 

 Update HOADONXUATKHOCHITIET 
set THANHTIENTRUOCCHIETKHAU_CT = (DONGIASI * SOLUONGLE),
 CHIETKHAUTHEOTIEN =  (DONGIASI * SOLUONGLE * CHIETKHAUTHEOPHANTRAM),
 THANHTIENSAUCHIETKHAU_CT = (DONGIASI * SOLUONGLE) - (DONGIASI * SOLUONGLE * CHIETKHAUTHEOPHANTRAM)

  Update HOADONHAPKHOCHITIET 
set THANHTIENTRUOCCHIETKHAU_CT = (DONGIA * SOLUONGLE),
 THANHTIENSAUCHIETKHAU_CT = (DONGIA * SOLUONGLE)