//------------------------------------------------------------------------------
// <auto-generated>
// Service Generated By Nick Nguyen
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.UnitOfWork;
using Service.Pattern;
using WH.Entity;
using WH.Model;
using WH.Service.Repository;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;
using WH.Service.Service;
namespace WH.Service.Service
{
    public partial interface IHOADONNHAPXUATService : IService
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<HOADONNHAPXUAT, bool>> predicate);
    
    	HOADONNHAPXUAT CreateNew();
        List<HOADONNHAPXUAT> FindAll();
    	List<HOADONNHAPXUAT> Search(string textSearch);
    	List<HOADONNHAPXUAT> Search(Expression<Func<HOADONNHAPXUAT, bool>> predicate,string textSearch);
        List<HOADONNHAPXUAT> Search(Expression<Func<HOADONNHAPXUAT, bool>> predicate);
    	
    	HOADONNHAPXUAT Find(string idUnit);
    	HOADONNHAPXUAT Find(Expression<Func<HOADONNHAPXUAT, bool>> predicate);
    
    	//HOADONNHAPXUAT CloneNew(HOADONNHAPXUAT objHOADONNHAPXUAT);
    	//HOADONNHAPXUAT CloneUpdate(HOADONNHAPXUAT objHOADONNHAPXUAT);
    	HOADONNHAPXUAT Clone(HOADONNHAPXUAT objHOADONNHAPXUAT);
    	List< HOADONNHAPXUAT> Clone(IList<HOADONNHAPXUAT> listHOADONNHAPXUATs);
    
        MethodResult Add(HOADONNHAPXUAT model, bool isCommited = false,bool isAddChild = false);
        MethodResult Modify(HOADONNHAPXUAT model, bool isCommited= false,bool isModifyChild = false);
    	MethodResult Remove(HOADONNHAPXUAT model, bool isCommited = false,bool isRemoveChild = false);
        MethodResult Remove(string idUnit, bool isCommited = false,bool isRemoveChild = false);
    }
    
    public partial class HOADONNHAPXUATService : global::Service.Pattern.Service, IHOADONNHAPXUATService
    {
    	protected string userId = SessionModel.CurrentSession?.UserId;
    	protected IHOADONNHAPXUATRepository _HOADONNHAPXUATRepository;
    		protected IHOADONNHAPXUATCHITIETRepository  _HOADONNHAPXUATCHITIETRepository;
	
    
    	public HOADONNHAPXUATService(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
        protected override void InitRepositories()
        {
            _HOADONNHAPXUATRepository = new HOADONNHAPXUATRepository(this._dataContext, this._unitOfWork);
    			_HOADONNHAPXUATCHITIETRepository = new HOADONNHAPXUATCHITIETRepository(this._dataContext, this._unitOfWork);
		
        }
    	
    	public bool Exist(string id)
        {
    		return _HOADONNHAPXUATRepository.Exist(id);
        }
    
    	public bool Exist(Expression<Func<HOADONNHAPXUAT, bool>> predicate)
    	{
    		return _HOADONNHAPXUATRepository.Exist(predicate);
    	}
    
        public HOADONNHAPXUAT CreateNew()
        {
            return _HOADONNHAPXUATRepository.CreateNew();
        }
    
    	public List<HOADONNHAPXUAT> FindAll()
    	{
    		return _HOADONNHAPXUATRepository.FindAll();
    	}
    
    	public List<HOADONNHAPXUAT> Search(string textSearch)
        {
            return _HOADONNHAPXUATRepository.Search(textSearch);
        }
    
    	public List<HOADONNHAPXUAT> Search(Expression<Func<HOADONNHAPXUAT, bool>> predicate,string textSearch)
    	{
    		  return _HOADONNHAPXUATRepository.Search(predicate, textSearch);
    	}
    
    		public HOADONNHAPXUAT Find(Expression<Func<HOADONNHAPXUAT, bool>> predicate)
            {
               return _HOADONNHAPXUATRepository.getObject(predicate);
            }
    
            public List<HOADONNHAPXUAT> Search(Expression<Func<HOADONNHAPXUAT, bool>> predicate)
            {
                return _HOADONNHAPXUATRepository.Search(predicate);
            }
    
            //public HOADONNHAPXUAT CloneNew(HOADONNHAPXUAT objHOADONNHAPXUAT)
           // {
           //     return _HOADONNHAPXUATRepository.CloneNew(objHOADONNHAPXUAT);
           // }
    
    	//	public HOADONNHAPXUAT CloneUpdate(HOADONNHAPXUAT objHOADONNHAPXUAT)
    	//	{
    	//		  return _HOADONNHAPXUATRepository.CloneUpdate(objHOADONNHAPXUAT);
    	//	}
    
    		public HOADONNHAPXUAT Clone(HOADONNHAPXUAT objHOADONNHAPXUAT)
    		{
    			return _HOADONNHAPXUATRepository.Clone(objHOADONNHAPXUAT);
    		}
    
            public List<HOADONNHAPXUAT> Clone(IList<HOADONNHAPXUAT> listHOADONNHAPXUATs)
            {
                return _HOADONNHAPXUATRepository.Clone(listHOADONNHAPXUATs);
            }
    
        public HOADONNHAPXUAT Find(string idUnit)
        {
    		return _HOADONNHAPXUATRepository.getObject(idUnit);
        }
    
    	public MethodResult Add(HOADONNHAPXUAT entity, bool isCommited,bool isAddChild)
        {
    		MethodResult result = MethodResult.Succeed;
    		try
    		{
    			if(isCommited)
    				_unitOfWork.BeginTransaction();
    
    			entity.Validate();
    
    			_HOADONNHAPXUATRepository.Insert(Clone(entity));
    			if (SaveChanges() <= 0)
    			{
    				ThrowException("Không thể thêm dữ liệu 'HOADONNHAPXUAT'.");
    			}
    
    			if(isAddChild)
    			{
    			List<HOADONNHAPXUATCHITIET> lstHOADONNHAPXUATCHITIETs = _HOADONNHAPXUATCHITIETRepository.Clone(entity.HOADONNHAPXUATCHITIETs);
	 foreach( var obj in lstHOADONNHAPXUATCHITIETs ) 
{
HOADONNHAPXUATCHITIET objHOADONNHAPXUATCHITIET = _HOADONNHAPXUATCHITIETRepository.CloneNew(obj);
 if (objHOADONNHAPXUATCHITIET != null)
{
 _HOADONNHAPXUATCHITIETRepository.Insert(objHOADONNHAPXUATCHITIET);
}
}


    
    				if (SaveChanges() <= 0)
    				{
    					ThrowException("Không thể thêm dữ liệu con 'HOADONNHAPXUAT'.");
    				}
    			}
    
    			if(isCommited)
    					_unitOfWork.Commit();
            }
    		catch (DbEntityValidationException exception)
    		{
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
    		 }
    		catch (DbUpdateException exception)
    		{
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
    		}
            return result;
        }
    
    	public MethodResult Modify(HOADONNHAPXUAT entity, bool isCommited,bool isModifyChild)
    	{
                MethodResult result = MethodResult.Succeed;
                try
                {
    
                 if(isCommited)
    				_unitOfWork.BeginTransaction();
    
                    entity.Validate();
    
                    _HOADONNHAPXUATRepository.Update(Clone(entity));
    				if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể sửa dữ liệu 'HOADONNHAPXUAT'.");
                    }
    
    				if(isModifyChild)
    				{
    				List<HOADONNHAPXUATCHITIET> lstHOADONNHAPXUATCHITIETs = _HOADONNHAPXUATCHITIETRepository.Clone(entity.HOADONNHAPXUATCHITIETs);
	 foreach( var obj in lstHOADONNHAPXUATCHITIETs ) 
{
HOADONNHAPXUATCHITIET objHOADONNHAPXUATCHITIET = _HOADONNHAPXUATCHITIETRepository.CloneUpdate(obj);
 if (objHOADONNHAPXUATCHITIET != null)
{
 _HOADONNHAPXUATCHITIETRepository.Update(objHOADONNHAPXUATCHITIET);
}
}


    
    					 if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể sửa dữ liệu con 'HOADONNHAPXUAT'.");
    					}
    				}
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
            public MethodResult Remove(string idUnit, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
    				if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    HOADONNHAPXUAT entity = Find(idUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'HOADONNHAPXUAT' này không tồn tại trong hệ thống.");
                    }
    				if(isRemoveChild)
    				{
    				List<HOADONNHAPXUATCHITIET> lstHOADONNHAPXUATCHITIETs = _HOADONNHAPXUATCHITIETRepository.Clone(entity.HOADONNHAPXUATCHITIETs);
	 foreach( var obj in lstHOADONNHAPXUATCHITIETs ) 
{
HOADONNHAPXUATCHITIET objHOADONNHAPXUATCHITIET = _HOADONNHAPXUATCHITIETRepository.Clone(obj);
 if (objHOADONNHAPXUATCHITIET != null)
{
 _HOADONNHAPXUATCHITIETRepository.Delete(objHOADONNHAPXUATCHITIET);
}
}


    
    				    if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'HOADONNHAPXUAT'.");
    					}
    				}
    
                    _HOADONNHAPXUATRepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'HOADONNHAPXUAT'.");
                    }
    
    				if(isCommited)
    						_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
    		public MethodResult Remove(HOADONNHAPXUAT model, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
                    if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    HOADONNHAPXUAT entity = Find(model.IDUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'HOADONNHAPXUAT' này không tồn tại trong hệ thống.");
                    }
    
    				if(isRemoveChild)
    				{
    				List<HOADONNHAPXUATCHITIET> lstHOADONNHAPXUATCHITIETs = _HOADONNHAPXUATCHITIETRepository.Clone(entity.HOADONNHAPXUATCHITIETs);
	 foreach( var obj in lstHOADONNHAPXUATCHITIETs ) 
{
HOADONNHAPXUATCHITIET objHOADONNHAPXUATCHITIET = _HOADONNHAPXUATCHITIETRepository.Clone(obj);
 if (objHOADONNHAPXUATCHITIET != null)
{
 _HOADONNHAPXUATCHITIETRepository.Delete(objHOADONNHAPXUATCHITIET);
}
}


    
    					if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'HOADONNHAPXUAT'.");
    					}
    				}
                    _HOADONNHAPXUATRepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'HOADONNHAPXUAT'.");
                    }
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    }
}
