//------------------------------------------------------------------------------
// <auto-generated>
// Service Generated By Nick Nguyen
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.UnitOfWork;
using Service.Pattern;
using WH.Entity;
using WH.Model;
using WH.Service.Repository;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;
using WH.Service.Service;
namespace WH.Service.Service
{
    public partial interface IHOADONNHAPKHOService : IService
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<HOADONNHAPKHO, bool>> predicate);
    
    	HOADONNHAPKHO CreateNew();
        List<HOADONNHAPKHO> FindAll();
    	List<HOADONNHAPKHO> Search(string textSearch);
    	List<HOADONNHAPKHO> Search(Expression<Func<HOADONNHAPKHO, bool>> predicate,string textSearch);
        List<HOADONNHAPKHO> Search(Expression<Func<HOADONNHAPKHO, bool>> predicate);
    	
    	HOADONNHAPKHO Find(string idUnit);
    	HOADONNHAPKHO Find(Expression<Func<HOADONNHAPKHO, bool>> predicate);
    
    	//HOADONNHAPKHO CloneNew(HOADONNHAPKHO objHOADONNHAPKHO);
    	//HOADONNHAPKHO CloneUpdate(HOADONNHAPKHO objHOADONNHAPKHO);
    	HOADONNHAPKHO Clone(HOADONNHAPKHO objHOADONNHAPKHO);
    	List< HOADONNHAPKHO> Clone(IList<HOADONNHAPKHO> listHOADONNHAPKHOs);
    
        MethodResult Add(HOADONNHAPKHO model, bool isCommited = false,bool isAddChild = false);
        MethodResult Modify(HOADONNHAPKHO model, bool isCommited= false,bool isModifyChild = false);
    	MethodResult Remove(HOADONNHAPKHO model, bool isCommited = false,bool isRemoveChild = false);
        MethodResult Remove(string idUnit, bool isCommited = false,bool isRemoveChild = false);
    }
    
    public partial class HOADONNHAPKHOService : global::Service.Pattern.Service, IHOADONNHAPKHOService
    {
    	protected string userId = SessionModel.CurrentSession?.UserId;
    	protected IHOADONNHAPKHORepository _HOADONNHAPKHORepository;
    		protected IHOADONHAPKHOCHITIETRepository  _HOADONHAPKHOCHITIETRepository;
		protected IPHIEUCHIRepository  _PHIEUCHIRepository;
	
    
    	public HOADONNHAPKHOService(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
        protected override void InitRepositories()
        {
            _HOADONNHAPKHORepository = new HOADONNHAPKHORepository(this._dataContext, this._unitOfWork);
    			_HOADONHAPKHOCHITIETRepository = new HOADONHAPKHOCHITIETRepository(this._dataContext, this._unitOfWork);
			_PHIEUCHIRepository = new PHIEUCHIRepository(this._dataContext, this._unitOfWork);
		
        }
    	
    	public bool Exist(string id)
        {
    		return _HOADONNHAPKHORepository.Exist(id);
        }
    
    	public bool Exist(Expression<Func<HOADONNHAPKHO, bool>> predicate)
    	{
    		return _HOADONNHAPKHORepository.Exist(predicate);
    	}
    
        public HOADONNHAPKHO CreateNew()
        {
            return _HOADONNHAPKHORepository.CreateNew();
        }
    
    	public List<HOADONNHAPKHO> FindAll()
    	{
    		return _HOADONNHAPKHORepository.FindAll();
    	}
    
    	public List<HOADONNHAPKHO> Search(string textSearch)
        {
            return _HOADONNHAPKHORepository.Search(textSearch);
        }
    
    	public List<HOADONNHAPKHO> Search(Expression<Func<HOADONNHAPKHO, bool>> predicate,string textSearch)
    	{
    		  return _HOADONNHAPKHORepository.Search(predicate, textSearch);
    	}
    
    		public HOADONNHAPKHO Find(Expression<Func<HOADONNHAPKHO, bool>> predicate)
            {
               return _HOADONNHAPKHORepository.getObject(predicate);
            }
    
            public List<HOADONNHAPKHO> Search(Expression<Func<HOADONNHAPKHO, bool>> predicate)
            {
                return _HOADONNHAPKHORepository.Search(predicate);
            }
    
            //public HOADONNHAPKHO CloneNew(HOADONNHAPKHO objHOADONNHAPKHO)
           // {
           //     return _HOADONNHAPKHORepository.CloneNew(objHOADONNHAPKHO);
           // }
    
    	//	public HOADONNHAPKHO CloneUpdate(HOADONNHAPKHO objHOADONNHAPKHO)
    	//	{
    	//		  return _HOADONNHAPKHORepository.CloneUpdate(objHOADONNHAPKHO);
    	//	}
    
    		public HOADONNHAPKHO Clone(HOADONNHAPKHO objHOADONNHAPKHO)
    		{
    			return _HOADONNHAPKHORepository.Clone(objHOADONNHAPKHO);
    		}
    
            public List<HOADONNHAPKHO> Clone(IList<HOADONNHAPKHO> listHOADONNHAPKHOs)
            {
                return _HOADONNHAPKHORepository.Clone(listHOADONNHAPKHOs);
            }
    
        public HOADONNHAPKHO Find(string idUnit)
        {
    		return _HOADONNHAPKHORepository.getObject(idUnit);
        }
    
    	public MethodResult Add(HOADONNHAPKHO entity, bool isCommited,bool isAddChild)
        {
    		MethodResult result = MethodResult.Succeed;
    		try
    		{
    			if(isCommited)
    				_unitOfWork.BeginTransaction();
    
    			entity.Validate();
    
    			_HOADONNHAPKHORepository.Insert(Clone(entity));
    			if (SaveChanges() <= 0)
    			{
    				ThrowException("Không thể thêm dữ liệu 'HOADONNHAPKHO'.");
    			}
    
    			if(isAddChild)
    			{
    			List<HOADONHAPKHOCHITIET> lstHOADONHAPKHOCHITIETs = _HOADONHAPKHOCHITIETRepository.Clone(entity.HOADONHAPKHOCHITIETs);
	 foreach( var obj in lstHOADONHAPKHOCHITIETs ) 
{
HOADONHAPKHOCHITIET objHOADONHAPKHOCHITIET = _HOADONHAPKHOCHITIETRepository.CloneNew(obj);
 if (objHOADONHAPKHOCHITIET != null)
{
 _HOADONHAPKHOCHITIETRepository.Insert(objHOADONHAPKHOCHITIET);
}
}

List<PHIEUCHI> lstPHIEUCHIs = _PHIEUCHIRepository.Clone(entity.PHIEUCHIs);
	 foreach( var obj in lstPHIEUCHIs ) 
{
PHIEUCHI objPHIEUCHI = _PHIEUCHIRepository.CloneNew(obj);
 if (objPHIEUCHI != null)
{
 _PHIEUCHIRepository.Insert(objPHIEUCHI);
}
}


    
    				if (SaveChanges() <= 0)
    				{
    					ThrowException("Không thể thêm dữ liệu con 'HOADONNHAPKHO'.");
    				}
    			}
    
    			if(isCommited)
    					_unitOfWork.Commit();
            }
    		catch (DbEntityValidationException exception)
    		{
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
    		 }
    		catch (DbUpdateException exception)
    		{
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
    		}
            return result;
        }
    
    	public MethodResult Modify(HOADONNHAPKHO entity, bool isCommited,bool isModifyChild)
    	{
                MethodResult result = MethodResult.Succeed;
                try
                {
    
                 if(isCommited)
    				_unitOfWork.BeginTransaction();
    
                    entity.Validate();
    
                    _HOADONNHAPKHORepository.Update(Clone(entity));
    				if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể sửa dữ liệu 'HOADONNHAPKHO'.");
                    }
    
    				if(isModifyChild)
    				{
    				List<HOADONHAPKHOCHITIET> lstHOADONHAPKHOCHITIETs = _HOADONHAPKHOCHITIETRepository.Clone(entity.HOADONHAPKHOCHITIETs);
	 foreach( var obj in lstHOADONHAPKHOCHITIETs ) 
{
HOADONHAPKHOCHITIET objHOADONHAPKHOCHITIET = _HOADONHAPKHOCHITIETRepository.CloneUpdate(obj);
 if (objHOADONHAPKHOCHITIET != null)
{
 _HOADONHAPKHOCHITIETRepository.Update(objHOADONHAPKHOCHITIET);
}
}

List<PHIEUCHI> lstPHIEUCHIs = _PHIEUCHIRepository.Clone(entity.PHIEUCHIs);
	 foreach( var obj in lstPHIEUCHIs ) 
{
PHIEUCHI objPHIEUCHI = _PHIEUCHIRepository.CloneUpdate(obj);
 if (objPHIEUCHI != null)
{
 _PHIEUCHIRepository.Update(objPHIEUCHI);
}
}


    
    					 if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể sửa dữ liệu con 'HOADONNHAPKHO'.");
    					}
    				}
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
            public MethodResult Remove(string idUnit, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
    				if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    HOADONNHAPKHO entity = Find(idUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'HOADONNHAPKHO' này không tồn tại trong hệ thống.");
                    }
    				if(isRemoveChild)
    				{
    				List<HOADONHAPKHOCHITIET> lstHOADONHAPKHOCHITIETs = _HOADONHAPKHOCHITIETRepository.Clone(entity.HOADONHAPKHOCHITIETs);
	 foreach( var obj in lstHOADONHAPKHOCHITIETs ) 
{
HOADONHAPKHOCHITIET objHOADONHAPKHOCHITIET = _HOADONHAPKHOCHITIETRepository.Clone(obj);
 if (objHOADONHAPKHOCHITIET != null)
{
 _HOADONHAPKHOCHITIETRepository.Delete(objHOADONHAPKHOCHITIET);
}
}

List<PHIEUCHI> lstPHIEUCHIs = _PHIEUCHIRepository.Clone(entity.PHIEUCHIs);
	 foreach( var obj in lstPHIEUCHIs ) 
{
PHIEUCHI objPHIEUCHI = _PHIEUCHIRepository.Clone(obj);
 if (objPHIEUCHI != null)
{
 _PHIEUCHIRepository.Delete(objPHIEUCHI);
}
}


    
    				    if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'HOADONNHAPKHO'.");
    					}
    				}
    
                    _HOADONNHAPKHORepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'HOADONNHAPKHO'.");
                    }
    
    				if(isCommited)
    						_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
    		public MethodResult Remove(HOADONNHAPKHO model, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
                    if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    HOADONNHAPKHO entity = Find(model.IDUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'HOADONNHAPKHO' này không tồn tại trong hệ thống.");
                    }
    
    				if(isRemoveChild)
    				{
    				List<HOADONHAPKHOCHITIET> lstHOADONHAPKHOCHITIETs = _HOADONHAPKHOCHITIETRepository.Clone(entity.HOADONHAPKHOCHITIETs);
	 foreach( var obj in lstHOADONHAPKHOCHITIETs ) 
{
HOADONHAPKHOCHITIET objHOADONHAPKHOCHITIET = _HOADONHAPKHOCHITIETRepository.Clone(obj);
 if (objHOADONHAPKHOCHITIET != null)
{
 _HOADONHAPKHOCHITIETRepository.Delete(objHOADONHAPKHOCHITIET);
}
}

List<PHIEUCHI> lstPHIEUCHIs = _PHIEUCHIRepository.Clone(entity.PHIEUCHIs);
	 foreach( var obj in lstPHIEUCHIs ) 
{
PHIEUCHI objPHIEUCHI = _PHIEUCHIRepository.Clone(obj);
 if (objPHIEUCHI != null)
{
 _PHIEUCHIRepository.Delete(objPHIEUCHI);
}
}


    
    					if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'HOADONNHAPKHO'.");
    					}
    				}
                    _HOADONNHAPKHORepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'HOADONNHAPKHO'.");
                    }
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    }
}
