//------------------------------------------------------------------------------
// <auto-generated>
// Service Generated By Nick Nguyen
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.UnitOfWork;
using Service.Pattern;
using WH.Entity;
using WH.Model;
using WH.Service.Repository;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;
using WH.Service.Service;
namespace WH.Service.Service
{
    public partial interface ILOAIKHACHHANGService : IService
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<LOAIKHACHHANG, bool>> predicate);
    
    	LOAIKHACHHANG CreateNew();
        List<LOAIKHACHHANG> FindAll();
    	List<LOAIKHACHHANG> Search(string textSearch);
    	List<LOAIKHACHHANG> Search(Expression<Func<LOAIKHACHHANG, bool>> predicate,string textSearch);
        List<LOAIKHACHHANG> Search(Expression<Func<LOAIKHACHHANG, bool>> predicate);
    	
    	LOAIKHACHHANG Find(string idUnit);
    	LOAIKHACHHANG Find(Expression<Func<LOAIKHACHHANG, bool>> predicate);
    
    	//LOAIKHACHHANG CloneNew(LOAIKHACHHANG objLOAIKHACHHANG);
    	//LOAIKHACHHANG CloneUpdate(LOAIKHACHHANG objLOAIKHACHHANG);
    	LOAIKHACHHANG Clone(LOAIKHACHHANG objLOAIKHACHHANG);
    	List< LOAIKHACHHANG> Clone(IList<LOAIKHACHHANG> listLOAIKHACHHANGs);
    
        MethodResult Add(LOAIKHACHHANG model, bool isCommited = false,bool isAddChild = false);
        MethodResult Modify(LOAIKHACHHANG model, bool isCommited= false,bool isModifyChild = false);
    	MethodResult Remove(LOAIKHACHHANG model, bool isCommited = false,bool isRemoveChild = false);
        MethodResult Remove(string idUnit, bool isCommited = false,bool isRemoveChild = false);
    }
    
    public partial class LOAIKHACHHANGService : global::Service.Pattern.Service, ILOAIKHACHHANGService
    {
    	protected string userId = SessionModel.CurrentSession?.UserId;
    	protected ILOAIKHACHHANGRepository _LOAIKHACHHANGRepository;
    		protected IKHACHHANGRepository  _KHACHHANGRepository;
	
    
    	public LOAIKHACHHANGService(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
        protected override void InitRepositories()
        {
            _LOAIKHACHHANGRepository = new LOAIKHACHHANGRepository(this._dataContext, this._unitOfWork);
    			_KHACHHANGRepository = new KHACHHANGRepository(this._dataContext, this._unitOfWork);
		
        }
    	
    	public bool Exist(string id)
        {
    		return _LOAIKHACHHANGRepository.Exist(id);
        }
    
    	public bool Exist(Expression<Func<LOAIKHACHHANG, bool>> predicate)
    	{
    		return _LOAIKHACHHANGRepository.Exist(predicate);
    	}
    
        public LOAIKHACHHANG CreateNew()
        {
            return _LOAIKHACHHANGRepository.CreateNew();
        }
    
    	public List<LOAIKHACHHANG> FindAll()
    	{
    		return _LOAIKHACHHANGRepository.FindAll();
    	}
    
    	public List<LOAIKHACHHANG> Search(string textSearch)
        {
            return _LOAIKHACHHANGRepository.Search(textSearch);
        }
    
    	public List<LOAIKHACHHANG> Search(Expression<Func<LOAIKHACHHANG, bool>> predicate,string textSearch)
    	{
    		  return _LOAIKHACHHANGRepository.Search(predicate, textSearch);
    	}
    
    		public LOAIKHACHHANG Find(Expression<Func<LOAIKHACHHANG, bool>> predicate)
            {
               return _LOAIKHACHHANGRepository.getObject(predicate);
            }
    
            public List<LOAIKHACHHANG> Search(Expression<Func<LOAIKHACHHANG, bool>> predicate)
            {
                return _LOAIKHACHHANGRepository.Search(predicate);
            }
    
            //public LOAIKHACHHANG CloneNew(LOAIKHACHHANG objLOAIKHACHHANG)
           // {
           //     return _LOAIKHACHHANGRepository.CloneNew(objLOAIKHACHHANG);
           // }
    
    	//	public LOAIKHACHHANG CloneUpdate(LOAIKHACHHANG objLOAIKHACHHANG)
    	//	{
    	//		  return _LOAIKHACHHANGRepository.CloneUpdate(objLOAIKHACHHANG);
    	//	}
    
    		public LOAIKHACHHANG Clone(LOAIKHACHHANG objLOAIKHACHHANG)
    		{
    			return _LOAIKHACHHANGRepository.Clone(objLOAIKHACHHANG);
    		}
    
            public List<LOAIKHACHHANG> Clone(IList<LOAIKHACHHANG> listLOAIKHACHHANGs)
            {
                return _LOAIKHACHHANGRepository.Clone(listLOAIKHACHHANGs);
            }
    
        public LOAIKHACHHANG Find(string idUnit)
        {
    		return _LOAIKHACHHANGRepository.getObject(idUnit);
        }
    
    	public MethodResult Add(LOAIKHACHHANG entity, bool isCommited,bool isAddChild)
        {
    		MethodResult result = MethodResult.Succeed;
    		try
    		{
    			if(isCommited)
    				_unitOfWork.BeginTransaction();
    
    			entity.Validate();
    
    			_LOAIKHACHHANGRepository.Insert(Clone(entity));
    			if (SaveChanges() <= 0)
    			{
    				ThrowException("Không thể thêm dữ liệu 'LOAIKHACHHANG'.");
    			}
    
    			if(isAddChild)
    			{
    			List<KHACHHANG> lstKHACHHANGs = _KHACHHANGRepository.Clone(entity.KHACHHANGs);
	 foreach( var obj in lstKHACHHANGs ) 
{
KHACHHANG objKHACHHANG = _KHACHHANGRepository.CloneNew(obj);
 if (objKHACHHANG != null)
{
 _KHACHHANGRepository.Insert(objKHACHHANG);
}
}


    
    				if (SaveChanges() <= 0)
    				{
    					ThrowException("Không thể thêm dữ liệu con 'LOAIKHACHHANG'.");
    				}
    			}
    
    			if(isCommited)
    					_unitOfWork.Commit();
            }
    		catch (DbEntityValidationException exception)
    		{
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
    		 }
    		catch (DbUpdateException exception)
    		{
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
    		}
            return result;
        }
    
    	public MethodResult Modify(LOAIKHACHHANG entity, bool isCommited,bool isModifyChild)
    	{
                MethodResult result = MethodResult.Succeed;
                try
                {
    
                 if(isCommited)
    				_unitOfWork.BeginTransaction();
    
                    entity.Validate();
    
                    _LOAIKHACHHANGRepository.Update(Clone(entity));
    				if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể sửa dữ liệu 'LOAIKHACHHANG'.");
                    }
    
    				if(isModifyChild)
    				{
    				List<KHACHHANG> lstKHACHHANGs = _KHACHHANGRepository.Clone(entity.KHACHHANGs);
	 foreach( var obj in lstKHACHHANGs ) 
{
KHACHHANG objKHACHHANG = _KHACHHANGRepository.CloneUpdate(obj);
 if (objKHACHHANG != null)
{
 _KHACHHANGRepository.Update(objKHACHHANG);
}
}


    
    					 if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể sửa dữ liệu con 'LOAIKHACHHANG'.");
    					}
    				}
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
            public MethodResult Remove(string idUnit, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
    				if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    LOAIKHACHHANG entity = Find(idUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'LOAIKHACHHANG' này không tồn tại trong hệ thống.");
                    }
    				if(isRemoveChild)
    				{
    				List<KHACHHANG> lstKHACHHANGs = _KHACHHANGRepository.Clone(entity.KHACHHANGs);
	 foreach( var obj in lstKHACHHANGs ) 
{
KHACHHANG objKHACHHANG = _KHACHHANGRepository.Clone(obj);
 if (objKHACHHANG != null)
{
 _KHACHHANGRepository.Delete(objKHACHHANG);
}
}


    
    				    if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'LOAIKHACHHANG'.");
    					}
    				}
    
                    _LOAIKHACHHANGRepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'LOAIKHACHHANG'.");
                    }
    
    				if(isCommited)
    						_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
    		public MethodResult Remove(LOAIKHACHHANG model, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
                    if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    LOAIKHACHHANG entity = Find(model.IDUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'LOAIKHACHHANG' này không tồn tại trong hệ thống.");
                    }
    
    				if(isRemoveChild)
    				{
    				List<KHACHHANG> lstKHACHHANGs = _KHACHHANGRepository.Clone(entity.KHACHHANGs);
	 foreach( var obj in lstKHACHHANGs ) 
{
KHACHHANG objKHACHHANG = _KHACHHANGRepository.Clone(obj);
 if (objKHACHHANG != null)
{
 _KHACHHANGRepository.Delete(objKHACHHANG);
}
}


    
    					if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'LOAIKHACHHANG'.");
    					}
    				}
                    _LOAIKHACHHANGRepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'LOAIKHACHHANG'.");
                    }
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    }
}
