//------------------------------------------------------------------------------
// <auto-generated>
// Service Generated By Nick Nguyen
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.UnitOfWork;
using Service.Pattern;
using WH.Entity;
using WH.Model;
using WH.Service.Repository;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;
using WH.Service.Service;
namespace WH.Service.Service
{
    public partial interface ILOAIMATHANGService : IService
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<LOAIMATHANG, bool>> predicate);
    
    	LOAIMATHANG CreateNew();
        List<LOAIMATHANG> FindAll();
    	List<LOAIMATHANG> Search(string textSearch);
    	List<LOAIMATHANG> Search(Expression<Func<LOAIMATHANG, bool>> predicate,string textSearch);
        List<LOAIMATHANG> Search(Expression<Func<LOAIMATHANG, bool>> predicate);
    	
    	LOAIMATHANG Find(string idUnit);
    	LOAIMATHANG Find(Expression<Func<LOAIMATHANG, bool>> predicate);
    
    	//LOAIMATHANG CloneNew(LOAIMATHANG objLOAIMATHANG);
    	//LOAIMATHANG CloneUpdate(LOAIMATHANG objLOAIMATHANG);
    	LOAIMATHANG Clone(LOAIMATHANG objLOAIMATHANG);
    	List< LOAIMATHANG> Clone(IList<LOAIMATHANG> listLOAIMATHANGs);
    
        MethodResult Add(LOAIMATHANG model, bool isCommited = false,bool isAddChild = false);
        MethodResult Modify(LOAIMATHANG model, bool isCommited= false,bool isModifyChild = false);
    	MethodResult Remove(LOAIMATHANG model, bool isCommited = false,bool isRemoveChild = false);
        MethodResult Remove(string idUnit, bool isCommited = false,bool isRemoveChild = false);
    }
    
    public partial class LOAIMATHANGService : global::Service.Pattern.Service, ILOAIMATHANGService
    {
    	protected string userId = SessionModel.CurrentSession?.UserId;
    	protected ILOAIMATHANGRepository _LOAIMATHANGRepository;
    		protected ICHIETKHAULOAIMATHANGRepository  _CHIETKHAULOAIMATHANGRepository;
		protected IMATHANGRepository  _MATHANGRepository;
	
    
    	public LOAIMATHANGService(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
        protected override void InitRepositories()
        {
            _LOAIMATHANGRepository = new LOAIMATHANGRepository(this._dataContext, this._unitOfWork);
    			_CHIETKHAULOAIMATHANGRepository = new CHIETKHAULOAIMATHANGRepository(this._dataContext, this._unitOfWork);
			_MATHANGRepository = new MATHANGRepository(this._dataContext, this._unitOfWork);
		
        }
    	
    	public bool Exist(string id)
        {
    		return _LOAIMATHANGRepository.Exist(id);
        }
    
    	public bool Exist(Expression<Func<LOAIMATHANG, bool>> predicate)
    	{
    		return _LOAIMATHANGRepository.Exist(predicate);
    	}
    
        public LOAIMATHANG CreateNew()
        {
            return _LOAIMATHANGRepository.CreateNew();
        }
    
    	public List<LOAIMATHANG> FindAll()
    	{
    		return _LOAIMATHANGRepository.FindAll();
    	}
    
    	public List<LOAIMATHANG> Search(string textSearch)
        {
            return _LOAIMATHANGRepository.Search(textSearch);
        }
    
    	public List<LOAIMATHANG> Search(Expression<Func<LOAIMATHANG, bool>> predicate,string textSearch)
    	{
    		  return _LOAIMATHANGRepository.Search(predicate, textSearch);
    	}
    
    		public LOAIMATHANG Find(Expression<Func<LOAIMATHANG, bool>> predicate)
            {
               return _LOAIMATHANGRepository.getObject(predicate);
            }
    
            public List<LOAIMATHANG> Search(Expression<Func<LOAIMATHANG, bool>> predicate)
            {
                return _LOAIMATHANGRepository.Search(predicate);
            }
    
            //public LOAIMATHANG CloneNew(LOAIMATHANG objLOAIMATHANG)
           // {
           //     return _LOAIMATHANGRepository.CloneNew(objLOAIMATHANG);
           // }
    
    	//	public LOAIMATHANG CloneUpdate(LOAIMATHANG objLOAIMATHANG)
    	//	{
    	//		  return _LOAIMATHANGRepository.CloneUpdate(objLOAIMATHANG);
    	//	}
    
    		public LOAIMATHANG Clone(LOAIMATHANG objLOAIMATHANG)
    		{
    			return _LOAIMATHANGRepository.Clone(objLOAIMATHANG);
    		}
    
            public List<LOAIMATHANG> Clone(IList<LOAIMATHANG> listLOAIMATHANGs)
            {
                return _LOAIMATHANGRepository.Clone(listLOAIMATHANGs);
            }
    
        public LOAIMATHANG Find(string idUnit)
        {
    		return _LOAIMATHANGRepository.getObject(idUnit);
        }
    
    	public MethodResult Add(LOAIMATHANG entity, bool isCommited,bool isAddChild)
        {
    		MethodResult result = MethodResult.Succeed;
    		try
    		{
    			if(isCommited)
    				_unitOfWork.BeginTransaction();
    
    			entity.Validate();
    
    			_LOAIMATHANGRepository.Insert(Clone(entity));
    			if (SaveChanges() <= 0)
    			{
    				ThrowException("Không thể thêm dữ liệu 'LOAIMATHANG'.");
    			}
    
    			if(isAddChild)
    			{
    			List<CHIETKHAULOAIMATHANG> lstCHIETKHAULOAIMATHANGs = _CHIETKHAULOAIMATHANGRepository.Clone(entity.CHIETKHAULOAIMATHANGs);
	 foreach( var obj in lstCHIETKHAULOAIMATHANGs ) 
{
CHIETKHAULOAIMATHANG objCHIETKHAULOAIMATHANG = _CHIETKHAULOAIMATHANGRepository.CloneNew(obj);
 if (objCHIETKHAULOAIMATHANG != null)
{
 _CHIETKHAULOAIMATHANGRepository.Insert(objCHIETKHAULOAIMATHANG);
}
}

List<MATHANG> lstMATHANGs = _MATHANGRepository.Clone(entity.MATHANGs);
	 foreach( var obj in lstMATHANGs ) 
{
MATHANG objMATHANG = _MATHANGRepository.CloneNew(obj);
 if (objMATHANG != null)
{
 _MATHANGRepository.Insert(objMATHANG);
}
}


    
    				if (SaveChanges() <= 0)
    				{
    					ThrowException("Không thể thêm dữ liệu con 'LOAIMATHANG'.");
    				}
    			}
    
    			if(isCommited)
    					_unitOfWork.Commit();
            }
    		catch (DbEntityValidationException exception)
    		{
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
    		 }
    		catch (DbUpdateException exception)
    		{
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
    		}
            return result;
        }
    
    	public MethodResult Modify(LOAIMATHANG entity, bool isCommited,bool isModifyChild)
    	{
                MethodResult result = MethodResult.Succeed;
                try
                {
    
                 if(isCommited)
    				_unitOfWork.BeginTransaction();
    
                    entity.Validate();
    
                    _LOAIMATHANGRepository.Update(Clone(entity));
    				if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể sửa dữ liệu 'LOAIMATHANG'.");
                    }
    
    				if(isModifyChild)
    				{
    				List<CHIETKHAULOAIMATHANG> lstCHIETKHAULOAIMATHANGs = _CHIETKHAULOAIMATHANGRepository.Clone(entity.CHIETKHAULOAIMATHANGs);
	 foreach( var obj in lstCHIETKHAULOAIMATHANGs ) 
{
CHIETKHAULOAIMATHANG objCHIETKHAULOAIMATHANG = _CHIETKHAULOAIMATHANGRepository.CloneUpdate(obj);
 if (objCHIETKHAULOAIMATHANG != null)
{
 _CHIETKHAULOAIMATHANGRepository.Update(objCHIETKHAULOAIMATHANG);
}
}

List<MATHANG> lstMATHANGs = _MATHANGRepository.Clone(entity.MATHANGs);
	 foreach( var obj in lstMATHANGs ) 
{
MATHANG objMATHANG = _MATHANGRepository.CloneUpdate(obj);
 if (objMATHANG != null)
{
 _MATHANGRepository.Update(objMATHANG);
}
}


    
    					 if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể sửa dữ liệu con 'LOAIMATHANG'.");
    					}
    				}
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
            public MethodResult Remove(string idUnit, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
    				if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    LOAIMATHANG entity = Find(idUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'LOAIMATHANG' này không tồn tại trong hệ thống.");
                    }
    				if(isRemoveChild)
    				{
    				List<CHIETKHAULOAIMATHANG> lstCHIETKHAULOAIMATHANGs = _CHIETKHAULOAIMATHANGRepository.Clone(entity.CHIETKHAULOAIMATHANGs);
	 foreach( var obj in lstCHIETKHAULOAIMATHANGs ) 
{
CHIETKHAULOAIMATHANG objCHIETKHAULOAIMATHANG = _CHIETKHAULOAIMATHANGRepository.Clone(obj);
 if (objCHIETKHAULOAIMATHANG != null)
{
 _CHIETKHAULOAIMATHANGRepository.Delete(objCHIETKHAULOAIMATHANG);
}
}

List<MATHANG> lstMATHANGs = _MATHANGRepository.Clone(entity.MATHANGs);
	 foreach( var obj in lstMATHANGs ) 
{
MATHANG objMATHANG = _MATHANGRepository.Clone(obj);
 if (objMATHANG != null)
{
 _MATHANGRepository.Delete(objMATHANG);
}
}


    
    				    if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'LOAIMATHANG'.");
    					}
    				}
    
                    _LOAIMATHANGRepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'LOAIMATHANG'.");
                    }
    
    				if(isCommited)
    						_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
    		public MethodResult Remove(LOAIMATHANG model, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
                    if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    LOAIMATHANG entity = Find(model.IDUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'LOAIMATHANG' này không tồn tại trong hệ thống.");
                    }
    
    				if(isRemoveChild)
    				{
    				List<CHIETKHAULOAIMATHANG> lstCHIETKHAULOAIMATHANGs = _CHIETKHAULOAIMATHANGRepository.Clone(entity.CHIETKHAULOAIMATHANGs);
	 foreach( var obj in lstCHIETKHAULOAIMATHANGs ) 
{
CHIETKHAULOAIMATHANG objCHIETKHAULOAIMATHANG = _CHIETKHAULOAIMATHANGRepository.Clone(obj);
 if (objCHIETKHAULOAIMATHANG != null)
{
 _CHIETKHAULOAIMATHANGRepository.Delete(objCHIETKHAULOAIMATHANG);
}
}

List<MATHANG> lstMATHANGs = _MATHANGRepository.Clone(entity.MATHANGs);
	 foreach( var obj in lstMATHANGs ) 
{
MATHANG objMATHANG = _MATHANGRepository.Clone(obj);
 if (objMATHANG != null)
{
 _MATHANGRepository.Delete(objMATHANG);
}
}


    
    					if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'LOAIMATHANG'.");
    					}
    				}
                    _LOAIMATHANGRepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'LOAIMATHANG'.");
                    }
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    }
}
