//------------------------------------------------------------------------------
// <auto-generated>
// Service Generated By Nick Nguyen
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.UnitOfWork;
using Service.Pattern;
using WH.Entity;
using WH.Model;
using WH.Service.Repository;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;
using WH.Service.Service;
namespace WH.Service.Service
{
    public partial interface INGUOIDUNG_QUYENHANService : IService
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<NGUOIDUNG_QUYENHAN, bool>> predicate);
    
    	NGUOIDUNG_QUYENHAN CreateNew();
        List<NGUOIDUNG_QUYENHAN> FindAll();
    	List<NGUOIDUNG_QUYENHAN> Search(string textSearch);
    	List<NGUOIDUNG_QUYENHAN> Search(Expression<Func<NGUOIDUNG_QUYENHAN, bool>> predicate,string textSearch);
        List<NGUOIDUNG_QUYENHAN> Search(Expression<Func<NGUOIDUNG_QUYENHAN, bool>> predicate);
    	
    	NGUOIDUNG_QUYENHAN Find(string idUnit);
    	NGUOIDUNG_QUYENHAN Find(Expression<Func<NGUOIDUNG_QUYENHAN, bool>> predicate);
    
    	//NGUOIDUNG_QUYENHAN CloneNew(NGUOIDUNG_QUYENHAN objNGUOIDUNG_QUYENHAN);
    	//NGUOIDUNG_QUYENHAN CloneUpdate(NGUOIDUNG_QUYENHAN objNGUOIDUNG_QUYENHAN);
    	NGUOIDUNG_QUYENHAN Clone(NGUOIDUNG_QUYENHAN objNGUOIDUNG_QUYENHAN);
    	List< NGUOIDUNG_QUYENHAN> Clone(IList<NGUOIDUNG_QUYENHAN> listNGUOIDUNG_QUYENHANs);
    
        MethodResult Add(NGUOIDUNG_QUYENHAN model, bool isCommited = false,bool isAddChild = false);
        MethodResult Modify(NGUOIDUNG_QUYENHAN model, bool isCommited= false,bool isModifyChild = false);
    	MethodResult Remove(NGUOIDUNG_QUYENHAN model, bool isCommited = false,bool isRemoveChild = false);
        MethodResult Remove(string idUnit, bool isCommited = false,bool isRemoveChild = false);
    }
    
    public partial class NGUOIDUNG_QUYENHANService : global::Service.Pattern.Service, INGUOIDUNG_QUYENHANService
    {
    	protected string userId = SessionModel.CurrentSession?.UserId;
    	protected INGUOIDUNG_QUYENHANRepository _NGUOIDUNG_QUYENHANRepository;
    	
    
    	public NGUOIDUNG_QUYENHANService(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
        protected override void InitRepositories()
        {
            _NGUOIDUNG_QUYENHANRepository = new NGUOIDUNG_QUYENHANRepository(this._dataContext, this._unitOfWork);
    		
        }
    	
    	public bool Exist(string id)
        {
    		return _NGUOIDUNG_QUYENHANRepository.Exist(id);
        }
    
    	public bool Exist(Expression<Func<NGUOIDUNG_QUYENHAN, bool>> predicate)
    	{
    		return _NGUOIDUNG_QUYENHANRepository.Exist(predicate);
    	}
    
        public NGUOIDUNG_QUYENHAN CreateNew()
        {
            return _NGUOIDUNG_QUYENHANRepository.CreateNew();
        }
    
    	public List<NGUOIDUNG_QUYENHAN> FindAll()
    	{
    		return _NGUOIDUNG_QUYENHANRepository.FindAll();
    	}
    
    	public List<NGUOIDUNG_QUYENHAN> Search(string textSearch)
        {
            return _NGUOIDUNG_QUYENHANRepository.Search(textSearch);
        }
    
    	public List<NGUOIDUNG_QUYENHAN> Search(Expression<Func<NGUOIDUNG_QUYENHAN, bool>> predicate,string textSearch)
    	{
    		  return _NGUOIDUNG_QUYENHANRepository.Search(predicate, textSearch);
    	}
    
    		public NGUOIDUNG_QUYENHAN Find(Expression<Func<NGUOIDUNG_QUYENHAN, bool>> predicate)
            {
               return _NGUOIDUNG_QUYENHANRepository.getObject(predicate);
            }
    
            public List<NGUOIDUNG_QUYENHAN> Search(Expression<Func<NGUOIDUNG_QUYENHAN, bool>> predicate)
            {
                return _NGUOIDUNG_QUYENHANRepository.Search(predicate);
            }
    
            //public NGUOIDUNG_QUYENHAN CloneNew(NGUOIDUNG_QUYENHAN objNGUOIDUNG_QUYENHAN)
           // {
           //     return _NGUOIDUNG_QUYENHANRepository.CloneNew(objNGUOIDUNG_QUYENHAN);
           // }
    
    	//	public NGUOIDUNG_QUYENHAN CloneUpdate(NGUOIDUNG_QUYENHAN objNGUOIDUNG_QUYENHAN)
    	//	{
    	//		  return _NGUOIDUNG_QUYENHANRepository.CloneUpdate(objNGUOIDUNG_QUYENHAN);
    	//	}
    
    		public NGUOIDUNG_QUYENHAN Clone(NGUOIDUNG_QUYENHAN objNGUOIDUNG_QUYENHAN)
    		{
    			return _NGUOIDUNG_QUYENHANRepository.Clone(objNGUOIDUNG_QUYENHAN);
    		}
    
            public List<NGUOIDUNG_QUYENHAN> Clone(IList<NGUOIDUNG_QUYENHAN> listNGUOIDUNG_QUYENHANs)
            {
                return _NGUOIDUNG_QUYENHANRepository.Clone(listNGUOIDUNG_QUYENHANs);
            }
    
        public NGUOIDUNG_QUYENHAN Find(string idUnit)
        {
    		return _NGUOIDUNG_QUYENHANRepository.getObject(idUnit);
        }
    
    	public MethodResult Add(NGUOIDUNG_QUYENHAN entity, bool isCommited,bool isAddChild)
        {
    		MethodResult result = MethodResult.Succeed;
    		try
    		{
    			if(isCommited)
    				_unitOfWork.BeginTransaction();
    
    			entity.Validate();
    
    			_NGUOIDUNG_QUYENHANRepository.Insert(Clone(entity));
    			if (SaveChanges() <= 0)
    			{
    				ThrowException("Không thể thêm dữ liệu 'NGUOIDUNG_QUYENHAN'.");
    			}
    
    			if(isAddChild)
    			{
    			
    
    				if (SaveChanges() <= 0)
    				{
    					ThrowException("Không thể thêm dữ liệu con 'NGUOIDUNG_QUYENHAN'.");
    				}
    			}
    
    			if(isCommited)
    					_unitOfWork.Commit();
            }
    		catch (DbEntityValidationException exception)
    		{
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
    		 }
    		catch (DbUpdateException exception)
    		{
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
    		}
            return result;
        }
    
    	public MethodResult Modify(NGUOIDUNG_QUYENHAN entity, bool isCommited,bool isModifyChild)
    	{
                MethodResult result = MethodResult.Succeed;
                try
                {
    
                 if(isCommited)
    				_unitOfWork.BeginTransaction();
    
                    entity.Validate();
    
                    _NGUOIDUNG_QUYENHANRepository.Update(Clone(entity));
    				if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể sửa dữ liệu 'NGUOIDUNG_QUYENHAN'.");
                    }
    
    				if(isModifyChild)
    				{
    				
    
    					 if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể sửa dữ liệu con 'NGUOIDUNG_QUYENHAN'.");
    					}
    				}
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
            public MethodResult Remove(string idUnit, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
    				if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    NGUOIDUNG_QUYENHAN entity = Find(idUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'NGUOIDUNG_QUYENHAN' này không tồn tại trong hệ thống.");
                    }
    				if(isRemoveChild)
    				{
    				
    
    				    if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'NGUOIDUNG_QUYENHAN'.");
    					}
    				}
    
                    _NGUOIDUNG_QUYENHANRepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'NGUOIDUNG_QUYENHAN'.");
                    }
    
    				if(isCommited)
    						_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
    		public MethodResult Remove(NGUOIDUNG_QUYENHAN model, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
                    if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    NGUOIDUNG_QUYENHAN entity = Find(model.IDUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'NGUOIDUNG_QUYENHAN' này không tồn tại trong hệ thống.");
                    }
    
    				if(isRemoveChild)
    				{
    				
    
    					if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'NGUOIDUNG_QUYENHAN'.");
    					}
    				}
                    _NGUOIDUNG_QUYENHANRepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'NGUOIDUNG_QUYENHAN'.");
                    }
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    }
}
