//------------------------------------------------------------------------------
// <auto-generated>
// Service Generated By Nick Nguyen
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.UnitOfWork;
using Service.Pattern;
using WH.Entity;
using WH.Model;
using WH.Service.Repository;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;
using WH.Service.Service;
namespace WH.Service.Service
{
    public partial interface INGUOIDUNGService : IService
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<NGUOIDUNG, bool>> predicate);
    
    	NGUOIDUNG CreateNew();
        List<NGUOIDUNG> FindAll();
    	List<NGUOIDUNG> Search(string textSearch);
    	List<NGUOIDUNG> Search(Expression<Func<NGUOIDUNG, bool>> predicate,string textSearch);
        List<NGUOIDUNG> Search(Expression<Func<NGUOIDUNG, bool>> predicate);
    	
    	NGUOIDUNG Find(string idUnit);
    	NGUOIDUNG Find(Expression<Func<NGUOIDUNG, bool>> predicate);
    
    	//NGUOIDUNG CloneNew(NGUOIDUNG objNGUOIDUNG);
    	//NGUOIDUNG CloneUpdate(NGUOIDUNG objNGUOIDUNG);
    	NGUOIDUNG Clone(NGUOIDUNG objNGUOIDUNG);
    	List< NGUOIDUNG> Clone(IList<NGUOIDUNG> listNGUOIDUNGs);
    
        MethodResult Add(NGUOIDUNG model, bool isCommited = false,bool isAddChild = false);
        MethodResult Modify(NGUOIDUNG model, bool isCommited= false,bool isModifyChild = false);
    	MethodResult Remove(NGUOIDUNG model, bool isCommited = false,bool isRemoveChild = false);
        MethodResult Remove(string idUnit, bool isCommited = false,bool isRemoveChild = false);
    }
    
    public partial class NGUOIDUNGService : global::Service.Pattern.Service, INGUOIDUNGService
    {
    	protected string userId = SessionModel.CurrentSession?.UserId;
    	protected INGUOIDUNGRepository _NGUOIDUNGRepository;
    		protected INGUOIDUNG_QUYENHANRepository  _NGUOIDUNG_QUYENHANRepository;
	
    
    	public NGUOIDUNGService(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
        protected override void InitRepositories()
        {
            _NGUOIDUNGRepository = new NGUOIDUNGRepository(this._dataContext, this._unitOfWork);
    			_NGUOIDUNG_QUYENHANRepository = new NGUOIDUNG_QUYENHANRepository(this._dataContext, this._unitOfWork);
		
        }
    	
    	public bool Exist(string id)
        {
    		return _NGUOIDUNGRepository.Exist(id);
        }
    
    	public bool Exist(Expression<Func<NGUOIDUNG, bool>> predicate)
    	{
    		return _NGUOIDUNGRepository.Exist(predicate);
    	}
    
        public NGUOIDUNG CreateNew()
        {
            return _NGUOIDUNGRepository.CreateNew();
        }
    
    	public List<NGUOIDUNG> FindAll()
    	{
    		return _NGUOIDUNGRepository.FindAll();
    	}
    
    	public List<NGUOIDUNG> Search(string textSearch)
        {
            return _NGUOIDUNGRepository.Search(textSearch);
        }
    
    	public List<NGUOIDUNG> Search(Expression<Func<NGUOIDUNG, bool>> predicate,string textSearch)
    	{
    		  return _NGUOIDUNGRepository.Search(predicate, textSearch);
    	}
    
    		public NGUOIDUNG Find(Expression<Func<NGUOIDUNG, bool>> predicate)
            {
               return _NGUOIDUNGRepository.getObject(predicate);
            }
    
            public List<NGUOIDUNG> Search(Expression<Func<NGUOIDUNG, bool>> predicate)
            {
                return _NGUOIDUNGRepository.Search(predicate);
            }
    
            //public NGUOIDUNG CloneNew(NGUOIDUNG objNGUOIDUNG)
           // {
           //     return _NGUOIDUNGRepository.CloneNew(objNGUOIDUNG);
           // }
    
    	//	public NGUOIDUNG CloneUpdate(NGUOIDUNG objNGUOIDUNG)
    	//	{
    	//		  return _NGUOIDUNGRepository.CloneUpdate(objNGUOIDUNG);
    	//	}
    
    		public NGUOIDUNG Clone(NGUOIDUNG objNGUOIDUNG)
    		{
    			return _NGUOIDUNGRepository.Clone(objNGUOIDUNG);
    		}
    
            public List<NGUOIDUNG> Clone(IList<NGUOIDUNG> listNGUOIDUNGs)
            {
                return _NGUOIDUNGRepository.Clone(listNGUOIDUNGs);
            }
    
        public NGUOIDUNG Find(string idUnit)
        {
    		return _NGUOIDUNGRepository.getObject(idUnit);
        }
    
    	public MethodResult Add(NGUOIDUNG entity, bool isCommited,bool isAddChild)
        {
    		MethodResult result = MethodResult.Succeed;
    		try
    		{
    			if(isCommited)
    				_unitOfWork.BeginTransaction();
    
    			entity.Validate();
    
    			_NGUOIDUNGRepository.Insert(Clone(entity));
    			if (SaveChanges() <= 0)
    			{
    				ThrowException("Không thể thêm dữ liệu 'NGUOIDUNG'.");
    			}
    
    			if(isAddChild)
    			{
    			List<NGUOIDUNG_QUYENHAN> lstNGUOIDUNG_QUYENHAN = _NGUOIDUNG_QUYENHANRepository.Clone(entity.NGUOIDUNG_QUYENHAN);
	 foreach( var obj in lstNGUOIDUNG_QUYENHAN ) 
{
NGUOIDUNG_QUYENHAN objNGUOIDUNG_QUYENHAN = _NGUOIDUNG_QUYENHANRepository.CloneNew(obj);
 if (objNGUOIDUNG_QUYENHAN != null)
{
 _NGUOIDUNG_QUYENHANRepository.Insert(objNGUOIDUNG_QUYENHAN);
}
}


    
    				if (SaveChanges() <= 0)
    				{
    					ThrowException("Không thể thêm dữ liệu con 'NGUOIDUNG'.");
    				}
    			}
    
    			if(isCommited)
    					_unitOfWork.Commit();
            }
    		catch (DbEntityValidationException exception)
    		{
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
    		 }
    		catch (DbUpdateException exception)
    		{
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
    		}
            return result;
        }
    
    	public MethodResult Modify(NGUOIDUNG entity, bool isCommited,bool isModifyChild)
    	{
                MethodResult result = MethodResult.Succeed;
                try
                {
    
                 if(isCommited)
    				_unitOfWork.BeginTransaction();
    
                    entity.Validate();
    
                    _NGUOIDUNGRepository.Update(Clone(entity));
    				if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể sửa dữ liệu 'NGUOIDUNG'.");
                    }
    
    				if(isModifyChild)
    				{
    				List<NGUOIDUNG_QUYENHAN> lstNGUOIDUNG_QUYENHAN = _NGUOIDUNG_QUYENHANRepository.Clone(entity.NGUOIDUNG_QUYENHAN);
	 foreach( var obj in lstNGUOIDUNG_QUYENHAN ) 
{
NGUOIDUNG_QUYENHAN objNGUOIDUNG_QUYENHAN = _NGUOIDUNG_QUYENHANRepository.CloneUpdate(obj);
 if (objNGUOIDUNG_QUYENHAN != null)
{
 _NGUOIDUNG_QUYENHANRepository.Update(objNGUOIDUNG_QUYENHAN);
}
}


    
    					 if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể sửa dữ liệu con 'NGUOIDUNG'.");
    					}
    				}
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
            public MethodResult Remove(string idUnit, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
    				if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    NGUOIDUNG entity = Find(idUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'NGUOIDUNG' này không tồn tại trong hệ thống.");
                    }
    				if(isRemoveChild)
    				{
    				List<NGUOIDUNG_QUYENHAN> lstNGUOIDUNG_QUYENHAN = _NGUOIDUNG_QUYENHANRepository.Clone(entity.NGUOIDUNG_QUYENHAN);
	 foreach( var obj in lstNGUOIDUNG_QUYENHAN ) 
{
NGUOIDUNG_QUYENHAN objNGUOIDUNG_QUYENHAN = _NGUOIDUNG_QUYENHANRepository.Clone(obj);
 if (objNGUOIDUNG_QUYENHAN != null)
{
 _NGUOIDUNG_QUYENHANRepository.Delete(objNGUOIDUNG_QUYENHAN);
}
}


    
    				    if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'NGUOIDUNG'.");
    					}
    				}
    
                    _NGUOIDUNGRepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'NGUOIDUNG'.");
                    }
    
    				if(isCommited)
    						_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
    		public MethodResult Remove(NGUOIDUNG model, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
                    if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    NGUOIDUNG entity = Find(model.IDUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'NGUOIDUNG' này không tồn tại trong hệ thống.");
                    }
    
    				if(isRemoveChild)
    				{
    				List<NGUOIDUNG_QUYENHAN> lstNGUOIDUNG_QUYENHAN = _NGUOIDUNG_QUYENHANRepository.Clone(entity.NGUOIDUNG_QUYENHAN);
	 foreach( var obj in lstNGUOIDUNG_QUYENHAN ) 
{
NGUOIDUNG_QUYENHAN objNGUOIDUNG_QUYENHAN = _NGUOIDUNG_QUYENHANRepository.Clone(obj);
 if (objNGUOIDUNG_QUYENHAN != null)
{
 _NGUOIDUNG_QUYENHANRepository.Delete(objNGUOIDUNG_QUYENHAN);
}
}


    
    					if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'NGUOIDUNG'.");
    					}
    				}
                    _NGUOIDUNGRepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'NGUOIDUNG'.");
                    }
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    }
}
