//------------------------------------------------------------------------------
// <auto-generated>
// Service Generated By Nick Nguyen
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.UnitOfWork;
using Service.Pattern;
using WH.Entity;
using WH.Model;
using WH.Service.Repository;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;
using WH.Service.Service;
namespace WH.Service.Service
{
    public partial interface ITEMP_HOADONXUATKHOService : IService
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<TEMP_HOADONXUATKHO, bool>> predicate);
    
    	TEMP_HOADONXUATKHO CreateNew();
        List<TEMP_HOADONXUATKHO> FindAll();
    	List<TEMP_HOADONXUATKHO> Search(string textSearch);
    	List<TEMP_HOADONXUATKHO> Search(Expression<Func<TEMP_HOADONXUATKHO, bool>> predicate,string textSearch);
        List<TEMP_HOADONXUATKHO> Search(Expression<Func<TEMP_HOADONXUATKHO, bool>> predicate);
    	
    	TEMP_HOADONXUATKHO Find(string idUnit);
    	TEMP_HOADONXUATKHO Find(Expression<Func<TEMP_HOADONXUATKHO, bool>> predicate);
    
    	//TEMP_HOADONXUATKHO CloneNew(TEMP_HOADONXUATKHO objTEMP_HOADONXUATKHO);
    	//TEMP_HOADONXUATKHO CloneUpdate(TEMP_HOADONXUATKHO objTEMP_HOADONXUATKHO);
    	TEMP_HOADONXUATKHO Clone(TEMP_HOADONXUATKHO objTEMP_HOADONXUATKHO);
    	List< TEMP_HOADONXUATKHO> Clone(IList<TEMP_HOADONXUATKHO> listTEMP_HOADONXUATKHOs);
    
        MethodResult Add(TEMP_HOADONXUATKHO model, bool isCommited = false,bool isAddChild = false);
        MethodResult Modify(TEMP_HOADONXUATKHO model, bool isCommited= false,bool isModifyChild = false);
    	MethodResult Remove(TEMP_HOADONXUATKHO model, bool isCommited = false,bool isRemoveChild = false);
        MethodResult Remove(string idUnit, bool isCommited = false,bool isRemoveChild = false);
    }
    
    public partial class TEMP_HOADONXUATKHOService : global::Service.Pattern.Service, ITEMP_HOADONXUATKHOService
    {
    	protected string userId = SessionModel.CurrentSession?.UserId;
    	protected ITEMP_HOADONXUATKHORepository _TEMP_HOADONXUATKHORepository;
    	
    
    	public TEMP_HOADONXUATKHOService(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
        protected override void InitRepositories()
        {
            _TEMP_HOADONXUATKHORepository = new TEMP_HOADONXUATKHORepository(this._dataContext, this._unitOfWork);
    		
        }
    	
    	public bool Exist(string id)
        {
    		return _TEMP_HOADONXUATKHORepository.Exist(id);
        }
    
    	public bool Exist(Expression<Func<TEMP_HOADONXUATKHO, bool>> predicate)
    	{
    		return _TEMP_HOADONXUATKHORepository.Exist(predicate);
    	}
    
        public TEMP_HOADONXUATKHO CreateNew()
        {
            return _TEMP_HOADONXUATKHORepository.CreateNew();
        }
    
    	public List<TEMP_HOADONXUATKHO> FindAll()
    	{
    		return _TEMP_HOADONXUATKHORepository.FindAll();
    	}
    
    	public List<TEMP_HOADONXUATKHO> Search(string textSearch)
        {
            return _TEMP_HOADONXUATKHORepository.Search(textSearch);
        }
    
    	public List<TEMP_HOADONXUATKHO> Search(Expression<Func<TEMP_HOADONXUATKHO, bool>> predicate,string textSearch)
    	{
    		  return _TEMP_HOADONXUATKHORepository.Search(predicate, textSearch);
    	}
    
    		public TEMP_HOADONXUATKHO Find(Expression<Func<TEMP_HOADONXUATKHO, bool>> predicate)
            {
               return _TEMP_HOADONXUATKHORepository.getObject(predicate);
            }
    
            public List<TEMP_HOADONXUATKHO> Search(Expression<Func<TEMP_HOADONXUATKHO, bool>> predicate)
            {
                return _TEMP_HOADONXUATKHORepository.Search(predicate);
            }
    
            //public TEMP_HOADONXUATKHO CloneNew(TEMP_HOADONXUATKHO objTEMP_HOADONXUATKHO)
           // {
           //     return _TEMP_HOADONXUATKHORepository.CloneNew(objTEMP_HOADONXUATKHO);
           // }
    
    	//	public TEMP_HOADONXUATKHO CloneUpdate(TEMP_HOADONXUATKHO objTEMP_HOADONXUATKHO)
    	//	{
    	//		  return _TEMP_HOADONXUATKHORepository.CloneUpdate(objTEMP_HOADONXUATKHO);
    	//	}
    
    		public TEMP_HOADONXUATKHO Clone(TEMP_HOADONXUATKHO objTEMP_HOADONXUATKHO)
    		{
    			return _TEMP_HOADONXUATKHORepository.Clone(objTEMP_HOADONXUATKHO);
    		}
    
            public List<TEMP_HOADONXUATKHO> Clone(IList<TEMP_HOADONXUATKHO> listTEMP_HOADONXUATKHOs)
            {
                return _TEMP_HOADONXUATKHORepository.Clone(listTEMP_HOADONXUATKHOs);
            }
    
        public TEMP_HOADONXUATKHO Find(string idUnit)
        {
    		return _TEMP_HOADONXUATKHORepository.getObject(idUnit);
        }
    
    	public MethodResult Add(TEMP_HOADONXUATKHO entity, bool isCommited,bool isAddChild)
        {
    		MethodResult result = MethodResult.Succeed;
    		try
    		{
    			if(isCommited)
    				_unitOfWork.BeginTransaction();
    
    			entity.Validate();
    
    			_TEMP_HOADONXUATKHORepository.Insert(Clone(entity));
    			if (SaveChanges() <= 0)
    			{
    				ThrowException("Không thể thêm dữ liệu 'TEMP_HOADONXUATKHO'.");
    			}
    
    			if(isAddChild)
    			{
    			
    
    				if (SaveChanges() <= 0)
    				{
    					ThrowException("Không thể thêm dữ liệu con 'TEMP_HOADONXUATKHO'.");
    				}
    			}
    
    			if(isCommited)
    					_unitOfWork.Commit();
            }
    		catch (DbEntityValidationException exception)
    		{
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
    		 }
    		catch (DbUpdateException exception)
    		{
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
    		}
            return result;
        }
    
    	public MethodResult Modify(TEMP_HOADONXUATKHO entity, bool isCommited,bool isModifyChild)
    	{
                MethodResult result = MethodResult.Succeed;
                try
                {
    
                 if(isCommited)
    				_unitOfWork.BeginTransaction();
    
                    entity.Validate();
    
                    _TEMP_HOADONXUATKHORepository.Update(Clone(entity));
    				if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể sửa dữ liệu 'TEMP_HOADONXUATKHO'.");
                    }
    
    				if(isModifyChild)
    				{
    				
    
    					 if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể sửa dữ liệu con 'TEMP_HOADONXUATKHO'.");
    					}
    				}
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
            public MethodResult Remove(string idUnit, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
    				if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    TEMP_HOADONXUATKHO entity = Find(idUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'TEMP_HOADONXUATKHO' này không tồn tại trong hệ thống.");
                    }
    				if(isRemoveChild)
    				{
    				
    
    				    if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'TEMP_HOADONXUATKHO'.");
    					}
    				}
    
                    _TEMP_HOADONXUATKHORepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'TEMP_HOADONXUATKHO'.");
                    }
    
    				if(isCommited)
    						_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
    		public MethodResult Remove(TEMP_HOADONXUATKHO model, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
                    if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    TEMP_HOADONXUATKHO entity = Find(model.IDUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'TEMP_HOADONXUATKHO' này không tồn tại trong hệ thống.");
                    }
    
    				if(isRemoveChild)
    				{
    				
    
    					if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'TEMP_HOADONXUATKHO'.");
    					}
    				}
                    _TEMP_HOADONXUATKHORepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'TEMP_HOADONXUATKHO'.");
                    }
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    }
}
