//------------------------------------------------------------------------------
// <auto-generated>
// Service Generated By Nick Nguyen
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Repository.Pattern.UnitOfWork;
using Service.Pattern;
using WH.Entity;
using WH.Model;
using WH.Service.Repository;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;
using WH.Service.Service;
namespace WH.Service.Service
{
    public partial interface ITEMP_HOADONXUATKHOCHITIETService : IService
    {
    	bool Exist(string id);
    	bool Exist(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate);
    
    	TEMP_HOADONXUATKHOCHITIET CreateNew();
        List<TEMP_HOADONXUATKHOCHITIET> FindAll();
    	List<TEMP_HOADONXUATKHOCHITIET> Search(string textSearch);
    	List<TEMP_HOADONXUATKHOCHITIET> Search(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate,string textSearch);
        List<TEMP_HOADONXUATKHOCHITIET> Search(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate);
    	
    	TEMP_HOADONXUATKHOCHITIET Find(string idUnit);
    	TEMP_HOADONXUATKHOCHITIET Find(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate);
    
    	//TEMP_HOADONXUATKHOCHITIET CloneNew(TEMP_HOADONXUATKHOCHITIET objTEMP_HOADONXUATKHOCHITIET);
    	//TEMP_HOADONXUATKHOCHITIET CloneUpdate(TEMP_HOADONXUATKHOCHITIET objTEMP_HOADONXUATKHOCHITIET);
    	TEMP_HOADONXUATKHOCHITIET Clone(TEMP_HOADONXUATKHOCHITIET objTEMP_HOADONXUATKHOCHITIET);
    	List< TEMP_HOADONXUATKHOCHITIET> Clone(IList<TEMP_HOADONXUATKHOCHITIET> listTEMP_HOADONXUATKHOCHITIETs);
    
        MethodResult Add(TEMP_HOADONXUATKHOCHITIET model, bool isCommited = false,bool isAddChild = false);
        MethodResult Modify(TEMP_HOADONXUATKHOCHITIET model, bool isCommited= false,bool isModifyChild = false);
    	MethodResult Remove(TEMP_HOADONXUATKHOCHITIET model, bool isCommited = false,bool isRemoveChild = false);
        MethodResult Remove(string idUnit, bool isCommited = false,bool isRemoveChild = false);
    }
    
    public partial class TEMP_HOADONXUATKHOCHITIETService : global::Service.Pattern.Service, ITEMP_HOADONXUATKHOCHITIETService
    {
    	protected string userId = SessionModel.CurrentSession?.UserId;
    	protected ITEMP_HOADONXUATKHOCHITIETRepository _TEMP_HOADONXUATKHOCHITIETRepository;
    	
    
    	public TEMP_HOADONXUATKHOCHITIETService(IUnitOfWorkAsync unitOfWork)
                : base(unitOfWork)
        {
        }
    
        protected override void InitRepositories()
        {
            _TEMP_HOADONXUATKHOCHITIETRepository = new TEMP_HOADONXUATKHOCHITIETRepository(this._dataContext, this._unitOfWork);
    		
        }
    	
    	public bool Exist(string id)
        {
    		return _TEMP_HOADONXUATKHOCHITIETRepository.Exist(id);
        }
    
    	public bool Exist(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate)
    	{
    		return _TEMP_HOADONXUATKHOCHITIETRepository.Exist(predicate);
    	}
    
        public TEMP_HOADONXUATKHOCHITIET CreateNew()
        {
            return _TEMP_HOADONXUATKHOCHITIETRepository.CreateNew();
        }
    
    	public List<TEMP_HOADONXUATKHOCHITIET> FindAll()
    	{
    		return _TEMP_HOADONXUATKHOCHITIETRepository.FindAll();
    	}
    
    	public List<TEMP_HOADONXUATKHOCHITIET> Search(string textSearch)
        {
            return _TEMP_HOADONXUATKHOCHITIETRepository.Search(textSearch);
        }
    
    	public List<TEMP_HOADONXUATKHOCHITIET> Search(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate,string textSearch)
    	{
    		  return _TEMP_HOADONXUATKHOCHITIETRepository.Search(predicate, textSearch);
    	}
    
    		public TEMP_HOADONXUATKHOCHITIET Find(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate)
            {
               return _TEMP_HOADONXUATKHOCHITIETRepository.getObject(predicate);
            }
    
            public List<TEMP_HOADONXUATKHOCHITIET> Search(Expression<Func<TEMP_HOADONXUATKHOCHITIET, bool>> predicate)
            {
                return _TEMP_HOADONXUATKHOCHITIETRepository.Search(predicate);
            }
    
            //public TEMP_HOADONXUATKHOCHITIET CloneNew(TEMP_HOADONXUATKHOCHITIET objTEMP_HOADONXUATKHOCHITIET)
           // {
           //     return _TEMP_HOADONXUATKHOCHITIETRepository.CloneNew(objTEMP_HOADONXUATKHOCHITIET);
           // }
    
    	//	public TEMP_HOADONXUATKHOCHITIET CloneUpdate(TEMP_HOADONXUATKHOCHITIET objTEMP_HOADONXUATKHOCHITIET)
    	//	{
    	//		  return _TEMP_HOADONXUATKHOCHITIETRepository.CloneUpdate(objTEMP_HOADONXUATKHOCHITIET);
    	//	}
    
    		public TEMP_HOADONXUATKHOCHITIET Clone(TEMP_HOADONXUATKHOCHITIET objTEMP_HOADONXUATKHOCHITIET)
    		{
    			return _TEMP_HOADONXUATKHOCHITIETRepository.Clone(objTEMP_HOADONXUATKHOCHITIET);
    		}
    
            public List<TEMP_HOADONXUATKHOCHITIET> Clone(IList<TEMP_HOADONXUATKHOCHITIET> listTEMP_HOADONXUATKHOCHITIETs)
            {
                return _TEMP_HOADONXUATKHOCHITIETRepository.Clone(listTEMP_HOADONXUATKHOCHITIETs);
            }
    
        public TEMP_HOADONXUATKHOCHITIET Find(string idUnit)
        {
    		return _TEMP_HOADONXUATKHOCHITIETRepository.getObject(idUnit);
        }
    
    	public MethodResult Add(TEMP_HOADONXUATKHOCHITIET entity, bool isCommited,bool isAddChild)
        {
    		MethodResult result = MethodResult.Succeed;
    		try
    		{
    			if(isCommited)
    				_unitOfWork.BeginTransaction();
    
    			entity.Validate();
    
    			_TEMP_HOADONXUATKHOCHITIETRepository.Insert(Clone(entity));
    			if (SaveChanges() <= 0)
    			{
    				ThrowException("Không thể thêm dữ liệu 'TEMP_HOADONXUATKHOCHITIET'.");
    			}
    
    			if(isAddChild)
    			{
    			
    
    				if (SaveChanges() <= 0)
    				{
    					ThrowException("Không thể thêm dữ liệu con 'TEMP_HOADONXUATKHOCHITIET'.");
    				}
    			}
    
    			if(isCommited)
    					_unitOfWork.Commit();
            }
    		catch (DbEntityValidationException exception)
    		{
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
    		 }
    		catch (DbUpdateException exception)
    		{
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
    		}
            return result;
        }

        public MethodResult Modify(TEMP_HOADONXUATKHOCHITIET entity, bool isCommited,bool isModifyChild)
    	{
                MethodResult result = MethodResult.Succeed;
                try
                {
    
                 if(isCommited)
    				_unitOfWork.BeginTransaction();
    
                    entity.Validate();
    
                    _TEMP_HOADONXUATKHOCHITIETRepository.Update(Clone(entity));
    				if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể sửa dữ liệu 'TEMP_HOADONXUATKHOCHITIET'.");
                    }
    
    				if(isModifyChild)
    				{
    				
    
    					 if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể sửa dữ liệu con 'TEMP_HOADONXUATKHOCHITIET'.");
    					}
    				}
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
            public MethodResult Remove(string idUnit, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
    				if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    TEMP_HOADONXUATKHOCHITIET entity = Find(idUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'TEMP_HOADONXUATKHOCHITIET' này không tồn tại trong hệ thống.");
                    }
    				if(isRemoveChild)
    				{
    				
    
    				    if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'TEMP_HOADONXUATKHOCHITIET'.");
    					}
    				}
    
                    _TEMP_HOADONXUATKHOCHITIETRepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'TEMP_HOADONXUATKHOCHITIET'.");
                    }
    
    				if(isCommited)
    						_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    
    		public MethodResult Remove(TEMP_HOADONXUATKHOCHITIET model, bool isCommited,bool isRemoveChild)
            {
                MethodResult result = MethodResult.Succeed;
    
                try
                {
                    if(isCommited)
    						_unitOfWork.BeginTransaction();
    
    
                    TEMP_HOADONXUATKHOCHITIET entity = Find(model.IDUnit);
    
                    if (entity == null)
                    {
                        ThrowException("Dữ liệu 'TEMP_HOADONXUATKHOCHITIET' này không tồn tại trong hệ thống.");
                    }
    
    				if(isRemoveChild)
    				{
    				
    
    					if (SaveChanges() <= 0)
    					{
    						ThrowException("Không thể xóa dữ liệu con 'TEMP_HOADONXUATKHOCHITIET'.");
    					}
    				}
                    _TEMP_HOADONXUATKHOCHITIETRepository.Delete(Clone(entity));
    
                    if (SaveChanges() <= 0)
                    {
                        ThrowException("Không thể xóa dữ liệu 'TEMP_HOADONXUATKHOCHITIET'.");
                    }
    
                   	if(isCommited)
    					_unitOfWork.Commit();
                }
                catch (DbEntityValidationException exception)
        	    {
        	        var ex = HandleDbEntityValidationException(exception);
    
        	        if (_unitOfWork != null) _unitOfWork.Rollback();
        	        ErrMsg = ex.Message;
        	        result = MethodResult.Failed;
        	    }
        	    catch (DbUpdateException exception)
        	    {
                    var ex = HandleDbUpdateException(exception);
    
                    if (_unitOfWork != null) _unitOfWork.Rollback();
                    ErrMsg = ex.Message;
                    result = MethodResult.Failed;
                }
                return result;
            }
    }
}
